import time
import sys
import os

#######################################################
# list of all possible histograms we want filled      #


HISTLIST = []


HISTLIST.append('QCD')
HISTLIST.append('QCD_CMS_htt_QCDShape_etau_btag_8TeVDown')
HISTLIST.append('QCD_CMS_htt_QCDShape_etau_btag_8TeVUp')
HISTLIST.append('QCD_CMS_htt_QCDShape_mutau_btag_8TeVDown')
HISTLIST.append('QCD_CMS_htt_QCDShape_mutau_btag_8TeVUp')
HISTLIST.append('QCD_CMS_htt_QCDfrShape_etau_8TeVDown')
HISTLIST.append('QCD_CMS_htt_QCDfrShape_etau_8TeVUp')
HISTLIST.append('QCD_CMS_htt_QCDfrShape_mutau_8TeVDown')
HISTLIST.append('QCD_CMS_htt_QCDfrShape_mutau_8TeVUp')

HISTLIST.append('TT')
#HISTLIST.append('TT_CMS_htt_ttbarJetFake_8TeVDown')
#HISTLIST.append('TT_CMS_htt_ttbarJetFake_8TeVUp')
HISTLIST.append('TT_CMS_htt_ttbarPtReweight_8TeVDown')
HISTLIST.append('TT_CMS_htt_ttbarPtReweight_8TeVUp')
HISTLIST.append('TT_CMS_scale_t_etau_8TeVDown')
HISTLIST.append('TT_CMS_scale_t_etau_8TeVUp')
HISTLIST.append('TT_CMS_scale_t_mutau_8TeVDown')
HISTLIST.append('TT_CMS_scale_t_mutau_8TeVUp')

HISTLIST.append('VH_SM125')
HISTLIST.append('VH_SM125_CMS_scale_t_etau_8TeVDown')
HISTLIST.append('VH_SM125_CMS_scale_t_etau_8TeVUp')
HISTLIST.append('VH_SM125_CMS_scale_t_mutau_8TeVDown')
HISTLIST.append('VH_SM125_CMS_scale_t_mutau_8TeVUp')

HISTLIST.append('qqH_SM125')
HISTLIST.append('qqH_SM125_CMS_scale_t_etau_8TeVDown')
HISTLIST.append('qqH_SM125_CMS_scale_t_etau_8TeVUp')
HISTLIST.append('qqH_SM125_CMS_scale_t_mutau_8TeVDown')
HISTLIST.append('qqH_SM125_CMS_scale_t_mutau_8TeVUp')


HISTLIST.append('VV')
HISTLIST.append('VV_CMS_scale_t_etau_8TeVDown')
HISTLIST.append('VV_CMS_scale_t_etau_8TeVUp')
HISTLIST.append('VV_CMS_scale_t_mutau_8TeVDown')
HISTLIST.append('VV_CMS_scale_t_mutau_8TeVUp')

HISTLIST.append('W')
HISTLIST.append('W_CMS_htt_WShape_etau_btag_8TeVDown')
HISTLIST.append('W_CMS_htt_WShape_etau_btag_8TeVUp')
HISTLIST.append('W_CMS_htt_WShape_mutau_btag_8TeVDown')
HISTLIST.append('W_CMS_htt_WShape_mutau_btag_8TeVUp')
HISTLIST.append('W_CMS_scale_t_etau_8TeVDown')
HISTLIST.append('W_CMS_scale_t_etau_8TeVUp')
HISTLIST.append('W_CMS_scale_t_mutau_8TeVDown')
HISTLIST.append('W_CMS_scale_t_mutau_8TeVUp')

HISTLIST.append('ZJ')
HISTLIST.append('ZJ_CMS_scale_t_etau_8TeVDown')
HISTLIST.append('ZJ_CMS_scale_t_etau_8TeVUp')
HISTLIST.append('ZJ_CMS_scale_t_mutau_8TeVDown')
HISTLIST.append('ZJ_CMS_scale_t_mutau_8TeVUp')

HISTLIST.append('ZL')
HISTLIST.append('ZL_CMS_htt_ZLScale_etau_8TeVDown')
HISTLIST.append('ZL_CMS_htt_ZLScale_etau_8TeVUp')
HISTLIST.append('ZL_CMS_htt_ZLScale_mutau_8TeVDown')
HISTLIST.append('ZL_CMS_htt_ZLScale_mutau_8TeVUp')
HISTLIST.append('ZL_CMS_scale_t_etau_8TeVDown')
HISTLIST.append('ZL_CMS_scale_t_etau_8TeVUp')
HISTLIST.append('ZL_CMS_scale_t_mutau_8TeVDown')
HISTLIST.append('ZL_CMS_scale_t_mutau_8TeVUp')

HISTLIST.append('ZTT')
HISTLIST.append('ZTT_CMS_scale_t_etau_8TeVDown')
HISTLIST.append('ZTT_CMS_scale_t_etau_8TeVUp')
HISTLIST.append('ZTT_CMS_scale_t_mutau_8TeVDown')
HISTLIST.append('ZTT_CMS_scale_t_mutau_8TeVUp')

HISTLIST.append('ZTT_lowMass')
HISTLIST.append('ZTT_lowMass_CMS_scale_t_etau_8TeVDown')
HISTLIST.append('ZTT_lowMass_CMS_scale_t_etau_8TeVUp')
HISTLIST.append('ZTT_lowMass_CMS_scale_t_mutau_8TeVDown')
HISTLIST.append('ZTT_lowMass_CMS_scale_t_mutau_8TeVUp')

HISTLIST.append('data_obs')

HISTLIST.append('ggH_SM125')
HISTLIST.append('ggH_SM125_CMS_scale_t_etau_8TeVDown')
HISTLIST.append('ggH_SM125_CMS_scale_t_etau_8TeVUp')
HISTLIST.append('ggH_SM125_CMS_scale_t_mutau_8TeVDown')
HISTLIST.append('ggH_SM125_CMS_scale_t_mutau_8TeVUp')

HISTLIST.append('bba125')
HISTLIST.append('bba125_CMS_scale_t_etau_8TeVDown')
HISTLIST.append('bba125_CMS_scale_t_etau_8TeVUp')
HISTLIST.append('bba125_CMS_scale_t_mutau_8TeVDown')
HISTLIST.append('bba125_CMS_scale_t_mutau_8TeVUp')
HISTLIST.append('bba130')
HISTLIST.append('bba130_CMS_scale_t_etau_8TeVDown')
HISTLIST.append('bba130_CMS_scale_t_etau_8TeVUp')
HISTLIST.append('bba130_CMS_scale_t_mutau_8TeVDown')
HISTLIST.append('bba130_CMS_scale_t_mutau_8TeVUp')
HISTLIST.append('bba135')
HISTLIST.append('bba135_CMS_scale_t_etau_8TeVDown')
HISTLIST.append('bba135_CMS_scale_t_etau_8TeVUp')
HISTLIST.append('bba135_CMS_scale_t_mutau_8TeVDown')
HISTLIST.append('bba135_CMS_scale_t_mutau_8TeVUp')
HISTLIST.append('bba140')
HISTLIST.append('bba140_CMS_scale_t_etau_8TeVDown')
HISTLIST.append('bba140_CMS_scale_t_etau_8TeVUp')
HISTLIST.append('bba140_CMS_scale_t_mutau_8TeVDown')
HISTLIST.append('bba140_CMS_scale_t_mutau_8TeVUp')
HISTLIST.append('bba145')
HISTLIST.append('bba145_CMS_scale_t_etau_8TeVDown')
HISTLIST.append('bba145_CMS_scale_t_etau_8TeVUp')
HISTLIST.append('bba145_CMS_scale_t_mutau_8TeVDown')
HISTLIST.append('bba145_CMS_scale_t_mutau_8TeVUp')
HISTLIST.append('bba150')
HISTLIST.append('bba150_CMS_scale_t_etau_8TeVDown')
HISTLIST.append('bba150_CMS_scale_t_etau_8TeVUp')
HISTLIST.append('bba150_CMS_scale_t_mutau_8TeVDown')
HISTLIST.append('bba150_CMS_scale_t_mutau_8TeVUp')
HISTLIST.append('bba155')
HISTLIST.append('bba155_CMS_scale_t_etau_8TeVDown')
HISTLIST.append('bba155_CMS_scale_t_etau_8TeVUp')
HISTLIST.append('bba155_CMS_scale_t_mutau_8TeVDown')
HISTLIST.append('bba155_CMS_scale_t_mutau_8TeVUp')
HISTLIST.append('bba160')
HISTLIST.append('bba160_CMS_scale_t_etau_8TeVDown')
HISTLIST.append('bba160_CMS_scale_t_etau_8TeVUp')
HISTLIST.append('bba160_CMS_scale_t_mutau_8TeVDown')
HISTLIST.append('bba160_CMS_scale_t_mutau_8TeVUp')
HISTLIST.append('bba165')
HISTLIST.append('bba165_CMS_scale_t_etau_8TeVDown')
HISTLIST.append('bba165_CMS_scale_t_etau_8TeVUp')
HISTLIST.append('bba165_CMS_scale_t_mutau_8TeVDown')
HISTLIST.append('bba165_CMS_scale_t_mutau_8TeVUp')
HISTLIST.append('bba170')
HISTLIST.append('bba170_CMS_scale_t_etau_8TeVDown')
HISTLIST.append('bba170_CMS_scale_t_etau_8TeVUp')
HISTLIST.append('bba170_CMS_scale_t_mutau_8TeVDown')
HISTLIST.append('bba170_CMS_scale_t_mutau_8TeVUp')
HISTLIST.append('bba175')
HISTLIST.append('bba175_CMS_scale_t_etau_8TeVDown')
HISTLIST.append('bba175_CMS_scale_t_etau_8TeVUp')
HISTLIST.append('bba175_CMS_scale_t_mutau_8TeVDown')
HISTLIST.append('bba175_CMS_scale_t_mutau_8TeVUp')
HISTLIST.append('bba180')
HISTLIST.append('bba180_CMS_scale_t_etau_8TeVDown')
HISTLIST.append('bba180_CMS_scale_t_etau_8TeVUp')
HISTLIST.append('bba180_CMS_scale_t_mutau_8TeVDown')
HISTLIST.append('bba180_CMS_scale_t_mutau_8TeVUp')

