import time
import sys
import os

############
# due to 3 crashing events
# impose the following SF
# bbSUSY900 GEV (997674-2217)/997674.0 = 9.97777831235453716e-01
# ggHSUSY 250 GeV (1000441-2223)/1000441.0 = 9.97777979910859258e-01
# ggHSUSY 900 GeV (975744-2168.)/975744 = 9.97778105732651133e-01

from ROOT import gROOT,TChain, TLorentzVector, TSelector, TTree, TF1, TH1F, TCanvas, gStyle, TFile
from ROOT import TApplication,TTreeCache


################
# some global settings

UseNewTriggers = False
OnlyCheckEmbeddedTriggers = False

Verbose = False
SmallRun = False

PrintEvents = False
check_events = []
#check_events.append('1-287-187567')




chain = TChain('*/FlatTuple')

listOfFiles = []

#listOfFiles.append('./HOLDER/SUSY_BB800.root')

listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM1000_FLATv9Xntup/FlatTuple_10_1_CSV_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM1000_FLATv9Xntup/FlatTuple_11_1_yAk_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM1000_FLATv9Xntup/FlatTuple_12_1_zRE_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM1000_FLATv9Xntup/FlatTuple_13_1_2YL_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM1000_FLATv9Xntup/FlatTuple_14_1_iar_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM1000_FLATv9Xntup/FlatTuple_15_1_UNl_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM1000_FLATv9Xntup/FlatTuple_16_1_s2q_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM1000_FLATv9Xntup/FlatTuple_17_1_C6z_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM1000_FLATv9Xntup/FlatTuple_18_1_XO8_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM1000_FLATv9Xntup/FlatTuple_19_1_jCA_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM1000_FLATv9Xntup/FlatTuple_1_1_BBk_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM1000_FLATv9Xntup/FlatTuple_20_1_LyI_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM1000_FLATv9Xntup/FlatTuple_21_1_Aah_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM1000_FLATv9Xntup/FlatTuple_22_1_Ekq_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM1000_FLATv9Xntup/FlatTuple_23_1_7wc_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM1000_FLATv9Xntup/FlatTuple_24_1_Ohb_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM1000_FLATv9Xntup/FlatTuple_25_1_fGz_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM1000_FLATv9Xntup/FlatTuple_2_1_quG_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM1000_FLATv9Xntup/FlatTuple_3_1_Ywa_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM1000_FLATv9Xntup/FlatTuple_4_1_VKg_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM1000_FLATv9Xntup/FlatTuple_5_1_mq9_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM1000_FLATv9Xntup/FlatTuple_6_1_6BE_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM1000_FLATv9Xntup/FlatTuple_7_1_frs_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM1000_FLATv9Xntup/FlatTuple_8_1_R6F_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM1000_FLATv9Xntup/FlatTuple_9_1_xP3_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM100_FLATv9Xntup/FlatTuple_10_1_2yk_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM100_FLATv9Xntup/FlatTuple_11_1_GHW_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM100_FLATv9Xntup/FlatTuple_12_1_t1A_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM100_FLATv9Xntup/FlatTuple_13_1_d9E_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM100_FLATv9Xntup/FlatTuple_14_1_2xc_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM100_FLATv9Xntup/FlatTuple_15_1_qn1_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM100_FLATv9Xntup/FlatTuple_16_1_vk2_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM100_FLATv9Xntup/FlatTuple_17_1_PIy_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM100_FLATv9Xntup/FlatTuple_18_1_grA_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM100_FLATv9Xntup/FlatTuple_19_1_7Sb_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM100_FLATv9Xntup/FlatTuple_1_1_GX6_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM100_FLATv9Xntup/FlatTuple_20_1_0pC_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM100_FLATv9Xntup/FlatTuple_21_1_4wK_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM100_FLATv9Xntup/FlatTuple_22_1_XHx_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM100_FLATv9Xntup/FlatTuple_23_1_ZLy_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM100_FLATv9Xntup/FlatTuple_24_1_mqq_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM100_FLATv9Xntup/FlatTuple_25_1_Yvv_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM100_FLATv9Xntup/FlatTuple_26_1_nCQ_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM100_FLATv9Xntup/FlatTuple_2_1_NXY_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM100_FLATv9Xntup/FlatTuple_3_1_dFW_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM100_FLATv9Xntup/FlatTuple_4_1_OpV_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM100_FLATv9Xntup/FlatTuple_5_1_8Cs_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM100_FLATv9Xntup/FlatTuple_6_1_PrZ_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM100_FLATv9Xntup/FlatTuple_7_1_mlk_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM100_FLATv9Xntup/FlatTuple_8_1_sX9_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM100_FLATv9Xntup/FlatTuple_9_1_QoZ_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM110_FLATv9Xntup/FlatTuple_10_1_ZDF_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM110_FLATv9Xntup/FlatTuple_11_1_JHy_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM110_FLATv9Xntup/FlatTuple_12_1_O9h_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM110_FLATv9Xntup/FlatTuple_13_1_GZX_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM110_FLATv9Xntup/FlatTuple_14_1_UVj_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM110_FLATv9Xntup/FlatTuple_15_1_Hkd_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM110_FLATv9Xntup/FlatTuple_16_1_Yod_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM110_FLATv9Xntup/FlatTuple_17_1_inO_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM110_FLATv9Xntup/FlatTuple_18_1_YJY_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM110_FLATv9Xntup/FlatTuple_19_1_FId_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM110_FLATv9Xntup/FlatTuple_1_1_jsb_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM110_FLATv9Xntup/FlatTuple_20_1_iUE_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM110_FLATv9Xntup/FlatTuple_21_1_EWP_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM110_FLATv9Xntup/FlatTuple_22_1_FZJ_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM110_FLATv9Xntup/FlatTuple_23_1_9p9_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM110_FLATv9Xntup/FlatTuple_24_1_rTb_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM110_FLATv9Xntup/FlatTuple_25_1_AEG_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM110_FLATv9Xntup/FlatTuple_26_1_djA_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM110_FLATv9Xntup/FlatTuple_2_1_3Pk_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM110_FLATv9Xntup/FlatTuple_3_1_ksQ_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM110_FLATv9Xntup/FlatTuple_4_1_5Fy_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM110_FLATv9Xntup/FlatTuple_5_1_B5k_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM110_FLATv9Xntup/FlatTuple_6_1_mI1_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM110_FLATv9Xntup/FlatTuple_7_1_kdY_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM110_FLATv9Xntup/FlatTuple_8_1_FE9_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM110_FLATv9Xntup/FlatTuple_9_1_BZN_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM120_FLATv9Xntup/FlatTuple_10_1_EVX_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM120_FLATv9Xntup/FlatTuple_11_1_TZS_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM120_FLATv9Xntup/FlatTuple_12_1_pzq_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM120_FLATv9Xntup/FlatTuple_13_1_qb8_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM120_FLATv9Xntup/FlatTuple_14_1_8FU_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM120_FLATv9Xntup/FlatTuple_15_1_ddg_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM120_FLATv9Xntup/FlatTuple_16_1_kAS_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM120_FLATv9Xntup/FlatTuple_17_1_oPq_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM120_FLATv9Xntup/FlatTuple_18_1_uFK_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM120_FLATv9Xntup/FlatTuple_19_1_8Ow_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM120_FLATv9Xntup/FlatTuple_1_1_XAA_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM120_FLATv9Xntup/FlatTuple_20_1_Srn_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM120_FLATv9Xntup/FlatTuple_21_1_B9u_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM120_FLATv9Xntup/FlatTuple_22_1_3NR_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM120_FLATv9Xntup/FlatTuple_23_1_s4Z_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM120_FLATv9Xntup/FlatTuple_24_1_5CL_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM120_FLATv9Xntup/FlatTuple_25_1_5wt_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM120_FLATv9Xntup/FlatTuple_26_1_ZD5_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM120_FLATv9Xntup/FlatTuple_2_1_bM2_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM120_FLATv9Xntup/FlatTuple_3_1_EAy_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM120_FLATv9Xntup/FlatTuple_4_1_CNz_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM120_FLATv9Xntup/FlatTuple_5_1_8Z1_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM120_FLATv9Xntup/FlatTuple_6_1_ACd_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM120_FLATv9Xntup/FlatTuple_7_1_Sxa_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM120_FLATv9Xntup/FlatTuple_8_1_234_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM120_FLATv9Xntup/FlatTuple_9_1_su6_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM130_FLATv9Xntup/FlatTuple_10_1_Jzm_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM130_FLATv9Xntup/FlatTuple_11_1_7fh_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM130_FLATv9Xntup/FlatTuple_12_1_Myl_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM130_FLATv9Xntup/FlatTuple_13_1_8wb_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM130_FLATv9Xntup/FlatTuple_14_1_G01_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM130_FLATv9Xntup/FlatTuple_15_1_TAn_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM130_FLATv9Xntup/FlatTuple_16_1_qTj_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM130_FLATv9Xntup/FlatTuple_17_1_brX_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM130_FLATv9Xntup/FlatTuple_18_1_sqS_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM130_FLATv9Xntup/FlatTuple_19_1_p7c_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM130_FLATv9Xntup/FlatTuple_1_1_MhG_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM130_FLATv9Xntup/FlatTuple_20_1_uVx_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM130_FLATv9Xntup/FlatTuple_21_1_NtD_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM130_FLATv9Xntup/FlatTuple_22_1_MWx_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM130_FLATv9Xntup/FlatTuple_23_1_IKj_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM130_FLATv9Xntup/FlatTuple_24_1_f4a_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM130_FLATv9Xntup/FlatTuple_25_1_hbp_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM130_FLATv9Xntup/FlatTuple_26_1_ssr_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM130_FLATv9Xntup/FlatTuple_2_1_onT_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM130_FLATv9Xntup/FlatTuple_3_1_gFd_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM130_FLATv9Xntup/FlatTuple_4_1_BsQ_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM130_FLATv9Xntup/FlatTuple_5_1_1rI_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM130_FLATv9Xntup/FlatTuple_6_1_cTC_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM130_FLATv9Xntup/FlatTuple_7_1_fP4_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM130_FLATv9Xntup/FlatTuple_8_1_I7a_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM130_FLATv9Xntup/FlatTuple_9_1_ZDa_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM140_FLATv9Xntup/FlatTuple_10_1_iki_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM140_FLATv9Xntup/FlatTuple_11_1_z3C_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM140_FLATv9Xntup/FlatTuple_12_1_BnZ_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM140_FLATv9Xntup/FlatTuple_13_1_YQj_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM140_FLATv9Xntup/FlatTuple_14_1_cTp_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM140_FLATv9Xntup/FlatTuple_15_1_cas_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM140_FLATv9Xntup/FlatTuple_16_1_m2c_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM140_FLATv9Xntup/FlatTuple_17_1_Kc5_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM140_FLATv9Xntup/FlatTuple_18_1_EY0_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM140_FLATv9Xntup/FlatTuple_19_1_nHW_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM140_FLATv9Xntup/FlatTuple_1_1_9XA_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM140_FLATv9Xntup/FlatTuple_20_1_vxV_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM140_FLATv9Xntup/FlatTuple_21_1_yWr_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM140_FLATv9Xntup/FlatTuple_22_1_6vf_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM140_FLATv9Xntup/FlatTuple_23_1_W2i_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM140_FLATv9Xntup/FlatTuple_24_1_Cxu_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM140_FLATv9Xntup/FlatTuple_25_1_Vcn_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM140_FLATv9Xntup/FlatTuple_26_1_Ojg_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM140_FLATv9Xntup/FlatTuple_2_1_ZiG_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM140_FLATv9Xntup/FlatTuple_3_1_CWP_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM140_FLATv9Xntup/FlatTuple_4_1_x6l_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM140_FLATv9Xntup/FlatTuple_5_1_am3_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM140_FLATv9Xntup/FlatTuple_6_1_sWU_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM140_FLATv9Xntup/FlatTuple_7_1_5E5_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM140_FLATv9Xntup/FlatTuple_8_1_ecT_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM140_FLATv9Xntup/FlatTuple_9_1_pTA_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM160_FLATv9Xntup/FlatTuple_10_1_BaL_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM160_FLATv9Xntup/FlatTuple_11_1_5MV_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM160_FLATv9Xntup/FlatTuple_12_1_OHV_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM160_FLATv9Xntup/FlatTuple_13_1_Ctf_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM160_FLATv9Xntup/FlatTuple_14_1_e0j_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM160_FLATv9Xntup/FlatTuple_15_1_6Hx_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM160_FLATv9Xntup/FlatTuple_16_1_tOT_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM160_FLATv9Xntup/FlatTuple_17_1_1Ev_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM160_FLATv9Xntup/FlatTuple_18_1_b48_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM160_FLATv9Xntup/FlatTuple_19_1_fQa_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM160_FLATv9Xntup/FlatTuple_1_1_T25_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM160_FLATv9Xntup/FlatTuple_20_1_2nB_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM160_FLATv9Xntup/FlatTuple_21_1_P50_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM160_FLATv9Xntup/FlatTuple_22_1_mKu_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM160_FLATv9Xntup/FlatTuple_23_1_vWt_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM160_FLATv9Xntup/FlatTuple_24_1_pQh_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM160_FLATv9Xntup/FlatTuple_25_1_Zzr_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM160_FLATv9Xntup/FlatTuple_26_1_zHV_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM160_FLATv9Xntup/FlatTuple_2_1_icL_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM160_FLATv9Xntup/FlatTuple_3_1_3OE_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM160_FLATv9Xntup/FlatTuple_4_1_XBj_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM160_FLATv9Xntup/FlatTuple_5_1_Lo1_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM160_FLATv9Xntup/FlatTuple_6_1_hkX_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM160_FLATv9Xntup/FlatTuple_7_1_kXi_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM160_FLATv9Xntup/FlatTuple_8_1_1t8_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM160_FLATv9Xntup/FlatTuple_9_1_njP_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM180_FLATv9Xntup/FlatTuple_10_1_z0p_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM180_FLATv9Xntup/FlatTuple_11_1_Uw2_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM180_FLATv9Xntup/FlatTuple_12_1_4iR_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM180_FLATv9Xntup/FlatTuple_13_1_wEe_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM180_FLATv9Xntup/FlatTuple_14_1_Iso_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM180_FLATv9Xntup/FlatTuple_15_1_EKl_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM180_FLATv9Xntup/FlatTuple_16_1_8A0_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM180_FLATv9Xntup/FlatTuple_17_1_B5j_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM180_FLATv9Xntup/FlatTuple_18_1_uyn_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM180_FLATv9Xntup/FlatTuple_19_1_iC9_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM180_FLATv9Xntup/FlatTuple_1_1_65a_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM180_FLATv9Xntup/FlatTuple_20_1_Tn8_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM180_FLATv9Xntup/FlatTuple_21_1_y04_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM180_FLATv9Xntup/FlatTuple_22_1_Tln_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM180_FLATv9Xntup/FlatTuple_23_1_9iM_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM180_FLATv9Xntup/FlatTuple_24_1_Ryo_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM180_FLATv9Xntup/FlatTuple_25_1_RVv_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM180_FLATv9Xntup/FlatTuple_26_1_XP1_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM180_FLATv9Xntup/FlatTuple_2_1_N4w_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM180_FLATv9Xntup/FlatTuple_3_1_6rC_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM180_FLATv9Xntup/FlatTuple_4_1_ocE_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM180_FLATv9Xntup/FlatTuple_5_1_vLm_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM180_FLATv9Xntup/FlatTuple_6_1_o9l_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM180_FLATv9Xntup/FlatTuple_7_1_xQh_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM180_FLATv9Xntup/FlatTuple_8_1_w8B_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM180_FLATv9Xntup/FlatTuple_9_1_7kG_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM200_FLATv9Xntup/FlatTuple_10_1_r79_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM200_FLATv9Xntup/FlatTuple_11_1_oqO_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM200_FLATv9Xntup/FlatTuple_12_1_B17_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM200_FLATv9Xntup/FlatTuple_13_1_9Bu_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM200_FLATv9Xntup/FlatTuple_14_1_OBB_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM200_FLATv9Xntup/FlatTuple_15_1_zIR_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM200_FLATv9Xntup/FlatTuple_16_1_8up_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM200_FLATv9Xntup/FlatTuple_17_1_Toc_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM200_FLATv9Xntup/FlatTuple_18_1_NrJ_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM200_FLATv9Xntup/FlatTuple_19_1_O3C_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM200_FLATv9Xntup/FlatTuple_1_1_lVD_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM200_FLATv9Xntup/FlatTuple_20_1_Wrq_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM200_FLATv9Xntup/FlatTuple_21_1_TwA_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM200_FLATv9Xntup/FlatTuple_22_1_Yuj_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM200_FLATv9Xntup/FlatTuple_23_1_aO0_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM200_FLATv9Xntup/FlatTuple_24_1_63g_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM200_FLATv9Xntup/FlatTuple_25_1_kte_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM200_FLATv9Xntup/FlatTuple_2_1_khg_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM200_FLATv9Xntup/FlatTuple_3_1_tUC_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM200_FLATv9Xntup/FlatTuple_4_1_POu_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM200_FLATv9Xntup/FlatTuple_5_1_QiQ_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM200_FLATv9Xntup/FlatTuple_6_1_nD3_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM200_FLATv9Xntup/FlatTuple_7_1_8e3_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM200_FLATv9Xntup/FlatTuple_8_1_HI2_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM200_FLATv9Xntup/FlatTuple_9_1_wgR_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM250_FLATv9Xntup/FlatTuple_10_1_5sc_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM250_FLATv9Xntup/FlatTuple_11_1_9Qv_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM250_FLATv9Xntup/FlatTuple_12_1_T0r_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM250_FLATv9Xntup/FlatTuple_13_1_gjt_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM250_FLATv9Xntup/FlatTuple_14_1_2Vg_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM250_FLATv9Xntup/FlatTuple_15_1_6xc_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM250_FLATv9Xntup/FlatTuple_16_1_1lv_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM250_FLATv9Xntup/FlatTuple_17_1_Ogf_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM250_FLATv9Xntup/FlatTuple_18_1_jTe_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM250_FLATv9Xntup/FlatTuple_19_1_vYI_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM250_FLATv9Xntup/FlatTuple_1_1_q6c_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM250_FLATv9Xntup/FlatTuple_20_1_oOK_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM250_FLATv9Xntup/FlatTuple_21_1_LSk_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM250_FLATv9Xntup/FlatTuple_22_1_kBh_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM250_FLATv9Xntup/FlatTuple_23_1_Yic_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM250_FLATv9Xntup/FlatTuple_24_1_K0u_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM250_FLATv9Xntup/FlatTuple_25_1_apS_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM250_FLATv9Xntup/FlatTuple_26_1_bmz_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM250_FLATv9Xntup/FlatTuple_2_1_YkP_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM250_FLATv9Xntup/FlatTuple_3_1_Q33_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM250_FLATv9Xntup/FlatTuple_4_1_vr1_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM250_FLATv9Xntup/FlatTuple_5_1_SQx_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM250_FLATv9Xntup/FlatTuple_6_1_OpK_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM250_FLATv9Xntup/FlatTuple_7_1_b4x_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM250_FLATv9Xntup/FlatTuple_8_1_fvL_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM250_FLATv9Xntup/FlatTuple_9_1_7v7_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM300_FLATv9Xntup/FlatTuple_10_1_66N_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM300_FLATv9Xntup/FlatTuple_11_1_8Sz_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM300_FLATv9Xntup/FlatTuple_12_1_6Uq_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM300_FLATv9Xntup/FlatTuple_13_1_SdT_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM300_FLATv9Xntup/FlatTuple_14_1_vTS_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM300_FLATv9Xntup/FlatTuple_15_1_srd_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM300_FLATv9Xntup/FlatTuple_16_1_PfS_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM300_FLATv9Xntup/FlatTuple_17_1_oQi_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM300_FLATv9Xntup/FlatTuple_18_1_BEG_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM300_FLATv9Xntup/FlatTuple_19_1_FlZ_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM300_FLATv9Xntup/FlatTuple_1_1_WKc_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM300_FLATv9Xntup/FlatTuple_20_1_kLK_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM300_FLATv9Xntup/FlatTuple_21_1_A1P_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM300_FLATv9Xntup/FlatTuple_22_1_dO7_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM300_FLATv9Xntup/FlatTuple_23_1_n6U_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM300_FLATv9Xntup/FlatTuple_24_1_EbB_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM300_FLATv9Xntup/FlatTuple_25_1_VTz_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM300_FLATv9Xntup/FlatTuple_26_1_9wk_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM300_FLATv9Xntup/FlatTuple_2_1_PI5_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM300_FLATv9Xntup/FlatTuple_3_1_iWw_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM300_FLATv9Xntup/FlatTuple_4_1_0aE_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM300_FLATv9Xntup/FlatTuple_5_1_OJS_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM300_FLATv9Xntup/FlatTuple_6_1_aaL_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM300_FLATv9Xntup/FlatTuple_7_1_oe1_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM300_FLATv9Xntup/FlatTuple_8_1_uXJ_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM300_FLATv9Xntup/FlatTuple_9_1_inE_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM350_FLATv9Xntup/FlatTuple_10_1_s1i_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM350_FLATv9Xntup/FlatTuple_11_1_fFo_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM350_FLATv9Xntup/FlatTuple_12_1_DpT_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM350_FLATv9Xntup/FlatTuple_13_1_NRP_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM350_FLATv9Xntup/FlatTuple_14_1_tT8_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM350_FLATv9Xntup/FlatTuple_15_1_JaW_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM350_FLATv9Xntup/FlatTuple_16_1_8kR_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM350_FLATv9Xntup/FlatTuple_17_1_lS4_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM350_FLATv9Xntup/FlatTuple_18_1_Td9_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM350_FLATv9Xntup/FlatTuple_19_1_gtc_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM350_FLATv9Xntup/FlatTuple_1_1_woL_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM350_FLATv9Xntup/FlatTuple_20_1_vOR_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM350_FLATv9Xntup/FlatTuple_21_1_ESi_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM350_FLATv9Xntup/FlatTuple_22_1_L38_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM350_FLATv9Xntup/FlatTuple_23_1_Vtz_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM350_FLATv9Xntup/FlatTuple_24_1_R5r_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM350_FLATv9Xntup/FlatTuple_25_1_a82_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM350_FLATv9Xntup/FlatTuple_26_1_kMW_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM350_FLATv9Xntup/FlatTuple_2_1_3ZM_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM350_FLATv9Xntup/FlatTuple_3_1_iSC_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM350_FLATv9Xntup/FlatTuple_4_1_Vi7_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM350_FLATv9Xntup/FlatTuple_5_1_Fmi_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM350_FLATv9Xntup/FlatTuple_6_1_IW2_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM350_FLATv9Xntup/FlatTuple_7_1_oXL_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM350_FLATv9Xntup/FlatTuple_8_1_osd_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM350_FLATv9Xntup/FlatTuple_9_1_hI9_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM400_FLATv9Xntup/FlatTuple_10_1_SDB_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM400_FLATv9Xntup/FlatTuple_11_1_y29_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM400_FLATv9Xntup/FlatTuple_12_1_wM5_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM400_FLATv9Xntup/FlatTuple_13_1_U8G_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM400_FLATv9Xntup/FlatTuple_14_1_J5x_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM400_FLATv9Xntup/FlatTuple_15_1_yKU_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM400_FLATv9Xntup/FlatTuple_16_1_pyE_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM400_FLATv9Xntup/FlatTuple_17_1_jNo_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM400_FLATv9Xntup/FlatTuple_18_1_0P1_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM400_FLATv9Xntup/FlatTuple_19_1_yI8_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM400_FLATv9Xntup/FlatTuple_1_1_4Np_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM400_FLATv9Xntup/FlatTuple_20_1_qYR_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM400_FLATv9Xntup/FlatTuple_21_1_5VM_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM400_FLATv9Xntup/FlatTuple_22_1_lqs_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM400_FLATv9Xntup/FlatTuple_23_1_g4R_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM400_FLATv9Xntup/FlatTuple_24_1_vU5_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM400_FLATv9Xntup/FlatTuple_25_1_Vow_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM400_FLATv9Xntup/FlatTuple_26_1_TB8_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM400_FLATv9Xntup/FlatTuple_2_1_dJu_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM400_FLATv9Xntup/FlatTuple_3_1_4iT_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM400_FLATv9Xntup/FlatTuple_4_1_spx_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM400_FLATv9Xntup/FlatTuple_5_1_X1j_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM400_FLATv9Xntup/FlatTuple_6_1_Gpo_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM400_FLATv9Xntup/FlatTuple_7_1_Laq_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM400_FLATv9Xntup/FlatTuple_8_1_5xv_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM400_FLATv9Xntup/FlatTuple_9_1_VPV_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM450_FLATv9Xntup/FlatTuple_10_1_Dro_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM450_FLATv9Xntup/FlatTuple_11_1_znC_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM450_FLATv9Xntup/FlatTuple_12_1_XUZ_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM450_FLATv9Xntup/FlatTuple_13_1_HoQ_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM450_FLATv9Xntup/FlatTuple_14_1_NTZ_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM450_FLATv9Xntup/FlatTuple_15_1_HHI_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM450_FLATv9Xntup/FlatTuple_16_1_DcX_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM450_FLATv9Xntup/FlatTuple_17_1_FKM_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM450_FLATv9Xntup/FlatTuple_18_1_Bnt_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM450_FLATv9Xntup/FlatTuple_19_1_M2m_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM450_FLATv9Xntup/FlatTuple_1_1_JPS_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM450_FLATv9Xntup/FlatTuple_20_1_6lv_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM450_FLATv9Xntup/FlatTuple_21_1_CDL_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM450_FLATv9Xntup/FlatTuple_22_1_Gsq_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM450_FLATv9Xntup/FlatTuple_23_1_97V_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM450_FLATv9Xntup/FlatTuple_24_1_NAj_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM450_FLATv9Xntup/FlatTuple_25_1_TRg_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM450_FLATv9Xntup/FlatTuple_26_1_uQ6_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM450_FLATv9Xntup/FlatTuple_2_1_HQZ_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM450_FLATv9Xntup/FlatTuple_3_1_NGk_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM450_FLATv9Xntup/FlatTuple_4_1_12G_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM450_FLATv9Xntup/FlatTuple_5_1_8I8_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM450_FLATv9Xntup/FlatTuple_6_1_oYb_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM450_FLATv9Xntup/FlatTuple_7_1_Dj4_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM450_FLATv9Xntup/FlatTuple_8_1_T34_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM450_FLATv9Xntup/FlatTuple_9_1_Rcc_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM500_FLATv9Xntup/FlatTuple_10_1_Hxf_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM500_FLATv9Xntup/FlatTuple_11_1_qqw_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM500_FLATv9Xntup/FlatTuple_12_1_Khv_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM500_FLATv9Xntup/FlatTuple_13_1_Xrm_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM500_FLATv9Xntup/FlatTuple_14_1_2VB_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM500_FLATv9Xntup/FlatTuple_15_1_d4J_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM500_FLATv9Xntup/FlatTuple_16_1_jeD_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM500_FLATv9Xntup/FlatTuple_17_1_UU4_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM500_FLATv9Xntup/FlatTuple_18_1_cVC_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM500_FLATv9Xntup/FlatTuple_19_1_DIv_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM500_FLATv9Xntup/FlatTuple_1_1_23N_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM500_FLATv9Xntup/FlatTuple_20_1_8Wm_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM500_FLATv9Xntup/FlatTuple_21_1_gw8_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM500_FLATv9Xntup/FlatTuple_22_1_sx1_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM500_FLATv9Xntup/FlatTuple_23_1_lkU_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM500_FLATv9Xntup/FlatTuple_24_1_Ktf_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM500_FLATv9Xntup/FlatTuple_25_1_u94_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM500_FLATv9Xntup/FlatTuple_26_1_Klq_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM500_FLATv9Xntup/FlatTuple_2_1_RT6_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM500_FLATv9Xntup/FlatTuple_3_1_rhW_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM500_FLATv9Xntup/FlatTuple_4_1_ady_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM500_FLATv9Xntup/FlatTuple_5_1_Ng1_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM500_FLATv9Xntup/FlatTuple_6_1_qw3_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM500_FLATv9Xntup/FlatTuple_7_1_e3b_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM500_FLATv9Xntup/FlatTuple_8_1_w1o_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM500_FLATv9Xntup/FlatTuple_9_1_twG_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM600_FLATv9Xntup/FlatTuple_10_1_8hm_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM600_FLATv9Xntup/FlatTuple_11_1_7Zt_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM600_FLATv9Xntup/FlatTuple_12_1_qHX_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM600_FLATv9Xntup/FlatTuple_13_1_tbT_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM600_FLATv9Xntup/FlatTuple_14_1_gua_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM600_FLATv9Xntup/FlatTuple_15_1_XUr_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM600_FLATv9Xntup/FlatTuple_16_1_UbW_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM600_FLATv9Xntup/FlatTuple_17_1_8oa_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM600_FLATv9Xntup/FlatTuple_18_1_mqG_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM600_FLATv9Xntup/FlatTuple_19_1_qtN_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM600_FLATv9Xntup/FlatTuple_1_1_Erd_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM600_FLATv9Xntup/FlatTuple_20_1_Fwh_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM600_FLATv9Xntup/FlatTuple_21_1_4l2_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM600_FLATv9Xntup/FlatTuple_22_1_c5J_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM600_FLATv9Xntup/FlatTuple_23_1_P3w_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM600_FLATv9Xntup/FlatTuple_24_1_kyv_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM600_FLATv9Xntup/FlatTuple_25_1_VtF_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM600_FLATv9Xntup/FlatTuple_2_1_00L_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM600_FLATv9Xntup/FlatTuple_3_1_Nrw_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM600_FLATv9Xntup/FlatTuple_4_1_raB_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM600_FLATv9Xntup/FlatTuple_5_1_UCL_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM600_FLATv9Xntup/FlatTuple_6_1_8dY_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM600_FLATv9Xntup/FlatTuple_7_1_2jA_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM600_FLATv9Xntup/FlatTuple_8_1_CMv_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM600_FLATv9Xntup/FlatTuple_9_1_jo2_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM700_FLATv9Xntup/FlatTuple_10_1_ue2_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM700_FLATv9Xntup/FlatTuple_11_1_V9y_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM700_FLATv9Xntup/FlatTuple_12_1_pso_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM700_FLATv9Xntup/FlatTuple_13_1_WtA_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM700_FLATv9Xntup/FlatTuple_14_1_GmJ_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM700_FLATv9Xntup/FlatTuple_15_1_M1b_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM700_FLATv9Xntup/FlatTuple_16_1_s1a_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM700_FLATv9Xntup/FlatTuple_17_1_C14_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM700_FLATv9Xntup/FlatTuple_18_1_lK1_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM700_FLATv9Xntup/FlatTuple_19_1_WF2_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM700_FLATv9Xntup/FlatTuple_1_1_0Qt_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM700_FLATv9Xntup/FlatTuple_20_1_IF4_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM700_FLATv9Xntup/FlatTuple_21_1_9Oc_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM700_FLATv9Xntup/FlatTuple_22_1_4wW_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM700_FLATv9Xntup/FlatTuple_23_1_liL_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM700_FLATv9Xntup/FlatTuple_24_1_9uJ_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM700_FLATv9Xntup/FlatTuple_25_1_AoU_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM700_FLATv9Xntup/FlatTuple_26_1_H7q_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM700_FLATv9Xntup/FlatTuple_2_1_i8E_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM700_FLATv9Xntup/FlatTuple_3_1_66n_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM700_FLATv9Xntup/FlatTuple_4_1_lS8_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM700_FLATv9Xntup/FlatTuple_5_1_gyy_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM700_FLATv9Xntup/FlatTuple_6_1_zts_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM700_FLATv9Xntup/FlatTuple_7_1_Ivn_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM700_FLATv9Xntup/FlatTuple_8_1_PQi_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM700_FLATv9Xntup/FlatTuple_9_1_7gt_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM800_FLATv9Xntup/FlatTuple_10_1_ptj_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM800_FLATv9Xntup/FlatTuple_11_1_yQY_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM800_FLATv9Xntup/FlatTuple_12_1_zwT_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM800_FLATv9Xntup/FlatTuple_13_1_6Zj_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM800_FLATv9Xntup/FlatTuple_14_1_pt5_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM800_FLATv9Xntup/FlatTuple_15_1_fDJ_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM800_FLATv9Xntup/FlatTuple_16_1_uQe_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM800_FLATv9Xntup/FlatTuple_17_1_lu9_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM800_FLATv9Xntup/FlatTuple_18_1_2RD_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM800_FLATv9Xntup/FlatTuple_19_1_qCt_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM800_FLATv9Xntup/FlatTuple_1_1_zss_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM800_FLATv9Xntup/FlatTuple_20_1_FXR_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM800_FLATv9Xntup/FlatTuple_21_1_79H_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM800_FLATv9Xntup/FlatTuple_22_1_l8V_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM800_FLATv9Xntup/FlatTuple_23_1_rjX_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM800_FLATv9Xntup/FlatTuple_24_1_dc2_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM800_FLATv9Xntup/FlatTuple_25_1_8kU_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM800_FLATv9Xntup/FlatTuple_26_1_s61_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM800_FLATv9Xntup/FlatTuple_2_1_Bze_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM800_FLATv9Xntup/FlatTuple_3_1_H0U_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM800_FLATv9Xntup/FlatTuple_4_1_jZO_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM800_FLATv9Xntup/FlatTuple_5_1_NLm_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM800_FLATv9Xntup/FlatTuple_6_1_17A_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM800_FLATv9Xntup/FlatTuple_7_1_ifv_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM800_FLATv9Xntup/FlatTuple_8_1_YyV_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM800_FLATv9Xntup/FlatTuple_9_1_7sv_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM80_FLATv9Xntup/FlatTuple_10_1_fM3_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM80_FLATv9Xntup/FlatTuple_11_1_cjQ_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM80_FLATv9Xntup/FlatTuple_12_1_xr0_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM80_FLATv9Xntup/FlatTuple_13_1_SPw_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM80_FLATv9Xntup/FlatTuple_14_1_WSE_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM80_FLATv9Xntup/FlatTuple_15_1_1se_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM80_FLATv9Xntup/FlatTuple_16_1_4yI_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM80_FLATv9Xntup/FlatTuple_17_1_2OL_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM80_FLATv9Xntup/FlatTuple_18_1_rg2_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM80_FLATv9Xntup/FlatTuple_19_1_jkJ_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM80_FLATv9Xntup/FlatTuple_1_1_A34_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM80_FLATv9Xntup/FlatTuple_20_1_P7B_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM80_FLATv9Xntup/FlatTuple_21_1_apl_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM80_FLATv9Xntup/FlatTuple_22_1_R8O_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM80_FLATv9Xntup/FlatTuple_23_1_W8M_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM80_FLATv9Xntup/FlatTuple_24_1_L8h_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM80_FLATv9Xntup/FlatTuple_25_1_oZB_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM80_FLATv9Xntup/FlatTuple_26_1_jcP_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM80_FLATv9Xntup/FlatTuple_2_1_KQU_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM80_FLATv9Xntup/FlatTuple_3_1_y4w_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM80_FLATv9Xntup/FlatTuple_4_1_UlZ_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM80_FLATv9Xntup/FlatTuple_5_1_BEu_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM80_FLATv9Xntup/FlatTuple_6_1_IKo_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM80_FLATv9Xntup/FlatTuple_7_1_l56_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM80_FLATv9Xntup/FlatTuple_8_1_xXE_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM80_FLATv9Xntup/FlatTuple_9_1_MAS_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM900_FLATv9Xntup/FlatTuple_10_1_KWe_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM900_FLATv9Xntup/FlatTuple_11_1_pvk_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM900_FLATv9Xntup/FlatTuple_12_1_soH_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM900_FLATv9Xntup/FlatTuple_13_1_Sww_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM900_FLATv9Xntup/FlatTuple_14_1_gMM_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM900_FLATv9Xntup/FlatTuple_15_1_lzd_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM900_FLATv9Xntup/FlatTuple_16_1_SPe_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM900_FLATv9Xntup/FlatTuple_17_1_V2E_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM900_FLATv9Xntup/FlatTuple_18_1_JK7_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM900_FLATv9Xntup/FlatTuple_19_1_PNh_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM900_FLATv9Xntup/FlatTuple_1_1_QMx_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM900_FLATv9Xntup/FlatTuple_20_1_mjX_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM900_FLATv9Xntup/FlatTuple_21_1_GZk_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM900_FLATv9Xntup/FlatTuple_22_1_UIL_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM900_FLATv9Xntup/FlatTuple_23_1_QXF_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM900_FLATv9Xntup/FlatTuple_24_1_pgg_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM900_FLATv9Xntup/FlatTuple_25_1_4ro_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM900_FLATv9Xntup/FlatTuple_26_1_ASo_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM900_FLATv9Xntup/FlatTuple_2_1_SjR_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM900_FLATv9Xntup/FlatTuple_3_1_Lxu_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM900_FLATv9Xntup/FlatTuple_4_1_xMr_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM900_FLATv9Xntup/FlatTuple_5_1_ttP_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM900_FLATv9Xntup/FlatTuple_6_1_NFN_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM900_FLATv9Xntup/FlatTuple_7_1_sk8_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM900_FLATv9Xntup/FlatTuple_8_1_ply_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM900_FLATv9Xntup/FlatTuple_9_1_2IR_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM90_FLATv9Xntup/FlatTuple_10_1_gSa_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM90_FLATv9Xntup/FlatTuple_11_1_LVX_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM90_FLATv9Xntup/FlatTuple_12_1_JkE_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM90_FLATv9Xntup/FlatTuple_13_1_eP7_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM90_FLATv9Xntup/FlatTuple_14_1_o5X_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM90_FLATv9Xntup/FlatTuple_15_1_1ra_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM90_FLATv9Xntup/FlatTuple_16_1_v2X_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM90_FLATv9Xntup/FlatTuple_17_1_6hd_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM90_FLATv9Xntup/FlatTuple_18_1_Pzs_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM90_FLATv9Xntup/FlatTuple_19_1_2ev_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM90_FLATv9Xntup/FlatTuple_1_1_Vf3_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM90_FLATv9Xntup/FlatTuple_20_1_eVg_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM90_FLATv9Xntup/FlatTuple_21_1_iUu_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM90_FLATv9Xntup/FlatTuple_22_1_A9x_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM90_FLATv9Xntup/FlatTuple_23_1_fTa_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM90_FLATv9Xntup/FlatTuple_24_1_xVh_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM90_FLATv9Xntup/FlatTuple_25_1_L5G_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM90_FLATv9Xntup/FlatTuple_26_1_gNh_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM90_FLATv9Xntup/FlatTuple_2_1_fcQ_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM90_FLATv9Xntup/FlatTuple_3_1_cpB_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM90_FLATv9Xntup/FlatTuple_4_1_seg_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM90_FLATv9Xntup/FlatTuple_5_1_kM3_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM90_FLATv9Xntup/FlatTuple_6_1_IDg_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM90_FLATv9Xntup/FlatTuple_7_1_o6Q_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM90_FLATv9Xntup/FlatTuple_8_1_wst_skimmed.root')
listOfFiles.append('/uscms/home/shalhout/no_backup/NEWSKIMV9X/SUSYBBHToTauTauM90_FLATv9Xntup/FlatTuple_9_1_si2_skimmed.root')




for afile in listOfFiles:
	chain.AddFile(afile,0,'TauEsNominal/FlatTuple')
	chain.AddFile(afile,0,'TauEsUp/FlatTuple')
	chain.AddFile(afile,0,'TauEsDown/FlatTuple')




theselector = "./scripts/FlatTreeSel.C+"
selector = TSelector.GetSelector(theselector)

chain.SetNotify(selector)
selector.Init(chain)
selector.Begin(chain)

####################################################################
# read in electronID, muonID, tauID, trigger, and event selections

from Configurations.python.electronID import *
from Configurations.python.muonID import *
from Configurations.python.tauID import *
from Configurations.python.triggerRequirements import *
from Configurations.python.eventRequirements import *
from Configurations.python.eventClassification import *
from Plotting.python.EventVariables import *
from Plotting.python.DataCardHistograms import *
from EventWeights.python.eventWeightFunctions import *
from Plotting.python.ComparisonPlots import *
from Configurations.python.SampleSpecificSelections import *
from Plotting.python.FillHistogramsBySample import *


maxEntries = chain.GetEntries()


if SmallRun is True:
	maxEntries = 1000

for entry in range(0,maxEntries):
		entryNumber = chain.GetEntryNumber(entry);
		localEntry = chain.LoadTree(entryNumber);
		if (localEntry >= 0):
			#print "NAMEVAR = ", chain.NAMEVAR
			if(entryNumber%1000==0):
				print 'processing entry ',entryNumber, 'of', maxEntries
				sys.stdout.flush()
			selector.Process(localEntry)
			passingETauIndices = []
			passingMuTauIndices = []
			maxPairTypeAndIndex = []

			#########################################################
			# get event ID

			eventID = [str(chain.run), str(chain.luminosityBlock), str(chain.event)]
			eventString = str(chain.run)+"-"+str(chain.luminosityBlock)+"-"+str(chain.event)
			sampleName =  str(chain.SampleName)



#########################################################
# loop over eTau pairs and store all that pass in list

			for index in range(0, chain.eT_correctedSVFitMass.size()):
				passesCuts = True
				if passesDefaultSelectionETau(chain,index,UseNewTriggers,Verbose) is False:
					passesCuts = False
				if passesSUSYBBExtraSelectionETau(chain,index) is False:
					passesCuts = False
				if passesCuts is True:
					passingETauIndices.append(index)


#########################################################
# loop over muTau pairs and store all that pass in list

			for index in range(0, chain.muT_correctedSVFitMass.size()):
				passesCuts = True
				if passesDefaultSelectionMuTau(chain,index,UseNewTriggers,Verbose) is False:
					passesCuts = False
				if passesSUSYBBExtraSelectionMuTau(chain,index) is False:
					passesCuts = False
				if passesCuts is True:
					passingMuTauIndices.append(index)



#########################################################
# if have multiple passing H candidates in the same event
# find the highest sumPt pair


			if (len(passingETauIndices) + len(passingMuTauIndices)) == 1:
				if len(passingETauIndices) == 1 :
					maxPairTypeAndIndex.append(passingETauIndices[0])
					maxPairTypeAndIndex.append('eleTau')
				elif len(passingMuTauIndices) == 1:
					maxPairTypeAndIndex.append(passingMuTauIndices[0])
					maxPairTypeAndIndex.append('muTau')
			if (len(passingETauIndices) + len(passingMuTauIndices)) > 1:
					getMaxPtPairIndex(chain, maxPairTypeAndIndex, passingMuTauIndices, passingETauIndices)

#########################################################
# now classify the event based on tauPt and nbtags

			if len(maxPairTypeAndIndex)	> 0:
				if maxPairTypeAndIndex[1] == 'muTau':
					maxPairTypeAndIndex.append(muTauClassification(chain, maxPairTypeAndIndex[0]))
					maxPairTypeAndIndex.append(chain.NAMEVAR)
					maxPairTypeAndIndex.append(muTauClassificationJECDOWN(chain, maxPairTypeAndIndex[0]))
					maxPairTypeAndIndex.append(muTauClassificationJECUP(chain, maxPairTypeAndIndex[0]))
				if maxPairTypeAndIndex[1] == 'eleTau':
					maxPairTypeAndIndex.append(eTauClassification(chain, maxPairTypeAndIndex[0]))
					maxPairTypeAndIndex.append(chain.NAMEVAR)
					maxPairTypeAndIndex.append(eTauClassificationJECDOWN(chain, maxPairTypeAndIndex[0]))
					maxPairTypeAndIndex.append(eTauClassificationJECUP(chain, maxPairTypeAndIndex[0]))
				if PrintEvents:
					print maxPairTypeAndIndex[1], maxPairTypeAndIndex[2],eventID[0]+"-"+eventID[1]+"-"+eventID[2]

##################################################################################
# get weights and fill histograms


			if len(maxPairTypeAndIndex)	> 0:
				eventVariables = {}
				fillVariables(chain,eventVariables,maxPairTypeAndIndex,Verbose)
				finalWt = signalSUSYweightBB(chain, maxPairTypeAndIndex, Verbose)
				highPtTauWtSYS =  highPtTauSYS(chain, maxPairTypeAndIndex)
				SAMPLE_ADD = getSAMPLE_ADD(sampleName)
				assert(len(SAMPLE_ADD)>0), " Assert : unknown sample "
				#print maxPairTypeAndIndex
				FillSUSYBB(maxPairTypeAndIndex,SAMPLE_ADD,finalWt,highPtTauWtSYS,histogram_dict,eventVariables['SVFitMass'])


######################
# save filled histograms

WriteEverything()
writeCompFile()
