import time
import sys
import os
from ROOT import gROOT,TChain, TLorentzVector, TSelector, TTree, TF1, TH1F, TCanvas, gStyle, TFile
from ROOT import TDirectoryFile

###########################
# create the File dict

dataCardFiles = {}

##################
# master lists

eventType = []
dataCardCategories = []
sampleType = []
sampleTitle = []


##############################
# fill the lists

eventType.append("muonTau")
eventType.append("eleTau")

dataCardCategories.append("inclusive")
dataCardCategories.append("btag")
dataCardCategories.append("btag_high")
dataCardCategories.append("btag_low")
dataCardCategories.append("nobtag")
dataCardCategories.append("nobtag_high")
dataCardCategories.append("nobtag_medium")
dataCardCategories.append("nobtag_low")


############
# data
sampleType.append('data_obs')
sampleTitle.append('')

########
# QCD

sampleType.append('QCD')
sampleTitle.append('data anti-iso, norm QCD')
sampleType.append('QCD_CMS_htt_QCDShape_etau_btag_low_8TeVUp')
sampleTitle.append('data anti-iso, norm QCD')
sampleType.append('QCD_CMS_htt_QCDShape_etau_btag_low_8TeVDown')
sampleTitle.append('data anti-iso, norm QCD')
sampleType.append('QCD_fine_binning')
sampleTitle.append('QCD full vbf')
sampleType.append('QCD_CMS_htt_QCDShape_etau_btag_low_8TeVUp_fine_binning')
sampleTitle.append('QCD full vbf')
sampleType.append('QCD_CMS_htt_QCDShape_etau_btag_low_8TeVDown_fine_binning')
sampleTitle.append('QCD full vbf')
sampleType.append('QCD_CMS_scale_t_etau_8TeVUp')
sampleTitle.append('data anti-iso, norm QCD')
sampleType.append('QCD_CMS_scale_t_etau_8TeVUp_fine_binning')
sampleTitle.append('QCD full vbf')
sampleType.append('QCD_CMS_scale_t_etau_8TeVDown')
sampleTitle.append('data anti-iso, norm QCD')
sampleType.append('QCD_CMS_scale_t_etau_8TeVDown_fine_binning')
sampleTitle.append('QCD full vbf')
sampleType.append('QCD_CMS_scale_jUp')
sampleTitle.append('data anti-iso, norm QCD')
sampleType.append('QCD_CMS_scale_jUp_fine_binning')
sampleTitle.append('QCD full vbf')
sampleType.append('QCD_CMS_scale_jDown')
sampleTitle.append('data anti-iso, norm QCD')
sampleType.append('QCD_CMS_scale_jDown_fine_binning')
sampleTitle.append('QCD full vbf')

##########
# ttbar

sampleType.append('TT')
sampleTitle.append('ttbar')
sampleType.append('TT_CMS_htt_ttbarPtReweight_8TeVUp')
sampleTitle.append('ttbarUp')
sampleType.append('TT_CMS_htt_ttbarPtReweight_8TeVDown')
sampleTitle.append('ttbarDown')
sampleType.append('TT_fine_binning')
sampleTitle.append('ttbar')
sampleType.append('TT_CMS_scale_t_etau_8TeVUp')
sampleTitle.append('ttbar')
sampleType.append('TT_CMS_htt_ZLScale_mutau_8TeVUp;4	ttbarUp')
sampleTitle.append('')
sampleType.append('TT_CMS_htt_ZLScale_mutau_8TeVUp;3	ttbarUp')
sampleTitle.append('')
sampleType.append('TT_CMS_htt_ZLScale_mutau_8TeVUp;2	ttbarUp')
sampleTitle.append('')
sampleType.append('TT_CMS_htt_ZLScale_mutau_8TeVUp')
sampleTitle.append('ttbarUp')
sampleType.append('TT_CMS_htt_ZLScale_mutau_8TeVDown;4	ttbarDown')
sampleTitle.append('')
sampleType.append('TT_CMS_htt_ZLScale_mutau_8TeVDown;3	ttbarDown')
sampleTitle.append('')
sampleType.append('TT_CMS_htt_ZLScale_mutau_8TeVDown;2	ttbarDown')
sampleTitle.append('')
sampleType.append('TT_CMS_htt_ZLScale_mutau_8TeVDown')
sampleTitle.append('ttbarDown')
sampleType.append('TT_CMS_scale_t_etau_8TeVUp_fine_binning')
sampleTitle.append('ttbar')
sampleType.append('TT_CMS_scale_t_etau_8TeVDown')
sampleTitle.append('ttbar')
sampleType.append('TT_CMS_scale_t_etau_8TeVDown_fine_binning')
sampleTitle.append('ttbar')
sampleType.append('TT_CMS_scale_jUp')
sampleTitle.append('ttbar')
sampleType.append('TT_CMS_scale_jUp_fine_binning')
sampleTitle.append('ttbar')
sampleType.append('TT_CMS_scale_jDown')
sampleTitle.append('ttbar')
sampleType.append('TT_CMS_scale_jDown_fine_binning')
sampleTitle.append('ttbar')

############
# VH

sampleType.append('VH_SM125')
sampleTitle.append('VH125')

############
# VV

sampleType.append('VV')
sampleTitle.append('Diboson')
sampleType.append('VV_fine_binning')
sampleTitle.append('Diboson')
sampleType.append('VV_CMS_scale_t_etau_8TeVUp')
sampleTitle.append('Diboson')
sampleType.append('VV_CMS_scale_t_etau_8TeVUp_fine_binning')
sampleTitle.append('Diboson')
sampleType.append('VV_CMS_scale_t_etau_8TeVDown')
sampleTitle.append('Diboson')
sampleType.append('VV_CMS_scale_t_etau_8TeVDown_fine_binning')
sampleTitle.append('Diboson')
sampleType.append('VV_CMS_scale_jUp')
sampleTitle.append('Diboson')
sampleType.append('VV_CMS_scale_jUp_fine_binning')
sampleTitle.append('Diboson')
sampleType.append('VV_CMS_scale_jDown')
sampleTitle.append('Diboson')
sampleType.append('VV_CMS_scale_jDown_fine_binning')
sampleTitle.append('Diboson')

###############
# W

sampleType.append('W')
sampleTitle.append('W+jets (Loose b-Tag)')
sampleType.append('W_CMS_htt_WShape_etau_btag_low_8TeVUp')
sampleTitle.append('W+jets (Loose b-Tag)')
sampleType.append('W_CMS_htt_WShape_etau_btag_low_8TeVDown')
sampleTitle.append('W+jets (Loose b-Tag)')
sampleType.append('W_fine_binning')
sampleTitle.append('W+jets')
sampleType.append('W_CMS_htt_WShape_etau_btag_low_8TeVUp_fine_binning')
sampleTitle.append('W+jets')
sampleType.append('W_CMS_htt_WShape_etau_btag_low_8TeVDown_fine_binning')
sampleTitle.append('W+jets')
sampleType.append('W_CMS_scale_t_etau_8TeVUp')
sampleTitle.append('W+jets (Loose b-Tag)')
sampleType.append('W_CMS_scale_t_etau_8TeVUp_fine_binning')
sampleTitle.append('W+jets')
sampleType.append('W_CMS_scale_t_etau_8TeVDown')
sampleTitle.append('W+jets (Loose b-Tag)')
sampleType.append('W_CMS_scale_t_etau_8TeVDown_fine_binning')
sampleTitle.append('W+jets')
sampleType.append('W_CMS_scale_jUp')
sampleTitle.append('W+jets (Loose b-Tag)')
sampleType.append('W_CMS_scale_jUp_fine_binning')
sampleTitle.append('W+jets')
sampleType.append('W_CMS_scale_jDown')
sampleTitle.append('W+jets (Loose b-Tag)')
sampleType.append('W_CMS_scale_jDown_fine_binning')
sampleTitle.append('W+jets')

#################
# ZJ

sampleType.append('ZJ')
sampleTitle.append('Z+jets, jet to tau')
sampleType.append('ZJ_fine_binning')
sampleTitle.append('Z+jets, jet to tau')
sampleType.append('ZJ_CMS_scale_t_etau_8TeVUp')
sampleTitle.append('Z+jets, jet to tau')
sampleType.append('ZJ_CMS_scale_t_etau_8TeVUp_fine_binning')
sampleTitle.append('Z+jets, jet to tau')
sampleType.append('ZJ_CMS_scale_t_etau_8TeVDown')
sampleTitle.append('Z+jets, jet to tau')
sampleType.append('ZJ_CMS_scale_t_etau_8TeVDown_fine_binning')
sampleTitle.append('Z+jets, jet to tau')
sampleType.append('ZJ_CMS_scale_jUp')
sampleTitle.append('Z+jets, jet to tau')
sampleType.append('ZJ_CMS_scale_jUp_fine_binning')
sampleTitle.append('Z+jets, jet to tau')
sampleType.append('ZJ_CMS_scale_jDown')
sampleTitle.append('Z+jets, jet to tau')
sampleType.append('ZJ_CMS_scale_jDown_fine_binning')
sampleTitle.append('Z+jets, jet to tau')

###########
# ZL

sampleType.append('ZL')
sampleTitle.append('Z+jets, e->tau')
sampleType.append('ZL_CMS_htt_ZLScale_etau_8TeVUp')
sampleTitle.append('Z+jets, e->tau')
sampleType.append('ZL_CMS_htt_ZLScale_etau_8TeVDown')
sampleTitle.append('Z+jets, e->tau')
sampleType.append('ZL_fine_binning')
sampleTitle.append('Z+jets, mu->tau')
sampleType.append('ZL_CMS_scale_t_etau_8TeVUp')
sampleTitle.append('Z+jets, e->tau')
sampleType.append('ZL_CMS_scale_t_etau_8TeVUp_fine_binning')
sampleTitle.append('Z+jets, mu->tau')
sampleType.append('ZL_CMS_scale_t_etau_8TeVDown')
sampleTitle.append('Z+jets, e->tau')
sampleType.append('ZL_CMS_scale_t_etau_8TeVDown_fine_binning')
sampleTitle.append('Z+jets, mu->tau')
sampleType.append('ZL_CMS_scale_jUp')
sampleTitle.append('Z+jets, e->tau')
sampleType.append('ZL_CMS_scale_jUp_fine_binning')
sampleTitle.append('Z+jets, mu->tau')
sampleType.append('ZL_CMS_scale_jDown')
sampleTitle.append('Z+jets, e->tau')
sampleType.append('ZL_CMS_scale_jDown_fine_binning')
sampleTitle.append('Z+jets, mu->tau')

##############
# ZLL

sampleType.append('ZLL')
sampleTitle.append('Z+jets')
sampleType.append('ZLL_fine_binning')
sampleTitle.append('Z+jets, jet to tau')
sampleType.append('ZLL_CMS_scale_t_etau_8TeVUp')
sampleTitle.append('Z+jets')
sampleType.append('ZLL_CMS_scale_t_etau_8TeVUp_fine_binning')
sampleTitle.append('Z+jets, jet to tau')
sampleType.append('ZLL_CMS_scale_t_etau_8TeVDown')
sampleTitle.append('Z+jets')
sampleType.append('ZLL_CMS_scale_t_etau_8TeVDown_fine_binning')
sampleTitle.append('Z+jets, jet to tau')
sampleType.append('ZLL_CMS_scale_jUp')
sampleTitle.append('Z+jets')
sampleType.append('ZLL_CMS_scale_jUp_fine_binning')
sampleTitle.append('Z+jets, jet to tau')
sampleType.append('ZLL_CMS_scale_jDown')
sampleTitle.append('Z+jets')
sampleType.append('ZLL_CMS_scale_jDown_fine_binning')
sampleTitle.append('Z+jets, jet to tau')

################
# ZTT

sampleType.append('ZTT')
sampleTitle.append('Embedded')
sampleType.append('ZTT_fine_binning')
sampleTitle.append('Embedded')
sampleType.append('ZTT_CMS_scale_t_etau_8TeVUp')
sampleTitle.append('Embedded')
sampleType.append('ZTT_CMS_scale_t_etau_8TeVUp_fine_binning')
sampleTitle.append('Embedded')
sampleType.append('ZTT_CMS_scale_t_etau_8TeVDown')
sampleTitle.append('Embedded')
sampleType.append('ZTT_CMS_scale_t_etau_8TeVDown_fine_binning')
sampleTitle.append('Embedded')
sampleType.append('ZTT_CMS_scale_jUp')
sampleTitle.append('Embedded')
sampleType.append('ZTT_CMS_scale_jUp_fine_binning')
sampleTitle.append('Embedded')
sampleType.append('ZTT_CMS_scale_jDown')
sampleTitle.append('Embedded')
sampleType.append('ZTT_CMS_scale_jDown_fine_binning')
sampleTitle.append('Embedded')

#########
# bbH

sampleType.append('bbH80')
sampleTitle.append('BBH80')
sampleType.append('bbH80_CMS_eff_t_mssmHigh_etau_8TeVUp')
sampleTitle.append('BBH80')
sampleType.append('bbH80_CMS_eff_t_mssmHigh_etau_8TeVDown')
sampleTitle.append('BBH80')
sampleType.append('bbH80_CMS_htt_higgsPtReweight_8TeVUp')
sampleTitle.append('BBH80')
sampleType.append('bbH80_CMS_htt_higgsPtReweight_8TeVDown')
sampleTitle.append('BBH80')
sampleType.append('bbH80_CMS_scale_t_etau_8TeVUp')
sampleTitle.append('BBH80')
sampleType.append('bbH80_CMS_scale_t_etau_8TeVDown')
sampleTitle.append('BBH80')
sampleType.append('bbH80_CMS_scale_jUp')
sampleTitle.append('BBH80')
sampleType.append('bbH80_CMS_scale_jDown')
sampleTitle.append('BBH80')
sampleType.append('bbH90')
sampleTitle.append('BBH90')
sampleType.append('bbH90_CMS_eff_t_mssmHigh_etau_8TeVUp')
sampleTitle.append('BBH90')
sampleType.append('bbH90_CMS_eff_t_mssmHigh_etau_8TeVDown')
sampleTitle.append('BBH90')
sampleType.append('bbH90_CMS_htt_higgsPtReweight_8TeVUp')
sampleTitle.append('BBH90')
sampleType.append('bbH90_CMS_htt_higgsPtReweight_8TeVDown')
sampleTitle.append('BBH90')
sampleType.append('bbH90_CMS_scale_t_etau_8TeVUp')
sampleTitle.append('BBH90')
sampleType.append('bbH90_CMS_scale_t_etau_8TeVDown')
sampleTitle.append('BBH90')
sampleType.append('bbH90_CMS_scale_jUp')
sampleTitle.append('BBH90')
sampleType.append('bbH90_CMS_scale_jDown')
sampleTitle.append('BBH90')
sampleType.append('bbH100')
sampleTitle.append('BBH100')
sampleType.append('bbH100_CMS_eff_t_mssmHigh_etau_8TeVUp')
sampleTitle.append('BBH100')
sampleType.append('bbH100_CMS_eff_t_mssmHigh_etau_8TeVDown')
sampleTitle.append('BBH100')
sampleType.append('bbH100_CMS_htt_higgsPtReweight_8TeVUp')
sampleTitle.append('BBH100')
sampleType.append('bbH100_CMS_htt_higgsPtReweight_8TeVDown')
sampleTitle.append('BBH100')
sampleType.append('bbH100_CMS_scale_t_etau_8TeVUp')
sampleTitle.append('BBH100')
sampleType.append('bbH100_CMS_scale_t_etau_8TeVDown')
sampleTitle.append('BBH100')
sampleType.append('bbH100_CMS_scale_jUp')
sampleTitle.append('BBH100')
sampleType.append('bbH100_CMS_scale_jDown')
sampleTitle.append('BBH100')
sampleType.append('bbH110')
sampleTitle.append('BBH110')
sampleType.append('bbH110_CMS_eff_t_mssmHigh_etau_8TeVUp')
sampleTitle.append('BBH110')
sampleType.append('bbH110_CMS_eff_t_mssmHigh_etau_8TeVDown')
sampleTitle.append('BBH110')
sampleType.append('bbH110_CMS_htt_higgsPtReweight_8TeVUp')
sampleTitle.append('BBH110')
sampleType.append('bbH110_CMS_htt_higgsPtReweight_8TeVDown')
sampleTitle.append('BBH110')
sampleType.append('bbH110_CMS_scale_t_etau_8TeVUp')
sampleTitle.append('BBH110')
sampleType.append('bbH110_CMS_scale_t_etau_8TeVDown')
sampleTitle.append('BBH110')
sampleType.append('bbH110_CMS_scale_jUp')
sampleTitle.append('BBH110')
sampleType.append('bbH110_CMS_scale_jDown')
sampleTitle.append('BBH110')
sampleType.append('bbH120')
sampleTitle.append('BBH120')
sampleType.append('bbH120_CMS_eff_t_mssmHigh_etau_8TeVUp')
sampleTitle.append('BBH120')
sampleType.append('bbH120_CMS_eff_t_mssmHigh_etau_8TeVDown')
sampleTitle.append('BBH120')
sampleType.append('bbH120_CMS_htt_higgsPtReweight_8TeVUp')
sampleTitle.append('BBH120')
sampleType.append('bbH120_CMS_htt_higgsPtReweight_8TeVDown')
sampleTitle.append('BBH120')
sampleType.append('bbH120_CMS_scale_t_etau_8TeVUp')
sampleTitle.append('BBH120')
sampleType.append('bbH120_CMS_scale_t_etau_8TeVDown')
sampleTitle.append('BBH120')
sampleType.append('bbH120_CMS_scale_jUp')
sampleTitle.append('BBH120')
sampleType.append('bbH120_CMS_scale_jDown')
sampleTitle.append('BBH120')
sampleType.append('bbH130')
sampleTitle.append('BBH130')
sampleType.append('bbH130_CMS_eff_t_mssmHigh_etau_8TeVUp')
sampleTitle.append('BBH130')
sampleType.append('bbH130_CMS_eff_t_mssmHigh_etau_8TeVDown')
sampleTitle.append('BBH130')
sampleType.append('bbH130_CMS_htt_higgsPtReweight_8TeVUp')
sampleTitle.append('BBH130')
sampleType.append('bbH130_CMS_htt_higgsPtReweight_8TeVDown')
sampleTitle.append('BBH130')
sampleType.append('bbH130_CMS_scale_t_etau_8TeVUp')
sampleTitle.append('BBH130')
sampleType.append('bbH130_CMS_scale_t_etau_8TeVDown')
sampleTitle.append('BBH130')
sampleType.append('bbH130_CMS_scale_jUp')
sampleTitle.append('BBH130')
sampleType.append('bbH130_CMS_scale_jDown')
sampleTitle.append('BBH130')
sampleType.append('bbH140')
sampleTitle.append('BBH140')
sampleType.append('bbH140_CMS_eff_t_mssmHigh_etau_8TeVUp')
sampleTitle.append('BBH140')
sampleType.append('bbH140_CMS_eff_t_mssmHigh_etau_8TeVDown')
sampleTitle.append('BBH140')
sampleType.append('bbH140_CMS_htt_higgsPtReweight_8TeVUp')
sampleTitle.append('BBH140')
sampleType.append('bbH140_CMS_htt_higgsPtReweight_8TeVDown')
sampleTitle.append('BBH140')
sampleType.append('bbH140_CMS_scale_t_etau_8TeVUp')
sampleTitle.append('BBH140')
sampleType.append('bbH140_CMS_scale_t_etau_8TeVDown')
sampleTitle.append('BBH140')
sampleType.append('bbH140_CMS_scale_jUp')
sampleTitle.append('BBH140')
sampleType.append('bbH140_CMS_scale_jDown')
sampleTitle.append('BBH140')
sampleType.append('bbH160')
sampleTitle.append('BBH160')
sampleType.append('bbH160_CMS_eff_t_mssmHigh_etau_8TeVUp')
sampleTitle.append('BBH160')
sampleType.append('bbH160_CMS_eff_t_mssmHigh_etau_8TeVDown')
sampleTitle.append('BBH160')
sampleType.append('bbH160_CMS_htt_higgsPtReweight_8TeVUp')
sampleTitle.append('BBH160')
sampleType.append('bbH160_CMS_htt_higgsPtReweight_8TeVDown')
sampleTitle.append('BBH160')
sampleType.append('bbH160_CMS_scale_t_etau_8TeVUp')
sampleTitle.append('BBH160')
sampleType.append('bbH160_CMS_scale_t_etau_8TeVDown')
sampleTitle.append('BBH160')
sampleType.append('bbH160_CMS_scale_jUp')
sampleTitle.append('BBH160')
sampleType.append('bbH160_CMS_scale_jDown')
sampleTitle.append('BBH160')
sampleType.append('bbH180')
sampleTitle.append('BBH180')
sampleType.append('bbH180_CMS_eff_t_mssmHigh_etau_8TeVUp')
sampleTitle.append('BBH180')
sampleType.append('bbH180_CMS_eff_t_mssmHigh_etau_8TeVDown')
sampleTitle.append('BBH180')
sampleType.append('bbH180_CMS_htt_higgsPtReweight_8TeVUp')
sampleTitle.append('BBH180')
sampleType.append('bbH180_CMS_htt_higgsPtReweight_8TeVDown')
sampleTitle.append('BBH180')
sampleType.append('bbH180_CMS_scale_t_etau_8TeVUp')
sampleTitle.append('BBH180')
sampleType.append('bbH180_CMS_scale_t_etau_8TeVDown')
sampleTitle.append('BBH180')
sampleType.append('bbH180_CMS_scale_jUp')
sampleTitle.append('BBH180')
sampleType.append('bbH180_CMS_scale_jDown')
sampleTitle.append('BBH180')
sampleType.append('bbH200')
sampleTitle.append('BBH200')
sampleType.append('bbH200_CMS_eff_t_mssmHigh_etau_8TeVUp')
sampleTitle.append('BBH200')
sampleType.append('bbH200_CMS_eff_t_mssmHigh_etau_8TeVDown')
sampleTitle.append('BBH200')
sampleType.append('bbH200_CMS_htt_higgsPtReweight_8TeVUp')
sampleTitle.append('BBH200')
sampleType.append('bbH200_CMS_htt_higgsPtReweight_8TeVDown')
sampleTitle.append('BBH200')
sampleType.append('bbH200_CMS_scale_t_etau_8TeVUp')
sampleTitle.append('BBH200')
sampleType.append('bbH200_CMS_scale_t_etau_8TeVDown')
sampleTitle.append('BBH200')
sampleType.append('bbH200_CMS_scale_jUp')
sampleTitle.append('BBH200')
sampleType.append('bbH200_CMS_scale_jDown')
sampleTitle.append('BBH200')
sampleType.append('bbH250')
sampleTitle.append('BBH250')
sampleType.append('bbH250_CMS_eff_t_mssmHigh_etau_8TeVUp')
sampleTitle.append('BBH250')
sampleType.append('bbH250_CMS_eff_t_mssmHigh_etau_8TeVDown')
sampleTitle.append('BBH250')
sampleType.append('bbH250_CMS_htt_higgsPtReweight_8TeVUp')
sampleTitle.append('BBH250')
sampleType.append('bbH250_CMS_htt_higgsPtReweight_8TeVDown')
sampleTitle.append('BBH250')
sampleType.append('bbH250_CMS_scale_t_etau_8TeVUp')
sampleTitle.append('BBH250')
sampleType.append('bbH250_CMS_scale_t_etau_8TeVDown')
sampleTitle.append('BBH250')
sampleType.append('bbH250_CMS_scale_jUp')
sampleTitle.append('BBH250')
sampleType.append('bbH250_CMS_scale_jDown')
sampleTitle.append('BBH250')
sampleType.append('bbH300')
sampleTitle.append('BBH300')
sampleType.append('bbH300_CMS_eff_t_mssmHigh_etau_8TeVUp')
sampleTitle.append('BBH300')
sampleType.append('bbH300_CMS_eff_t_mssmHigh_etau_8TeVDown')
sampleTitle.append('BBH300')
sampleType.append('bbH300_CMS_htt_higgsPtReweight_8TeVUp')
sampleTitle.append('BBH300')
sampleType.append('bbH300_CMS_htt_higgsPtReweight_8TeVDown')
sampleTitle.append('BBH300')
sampleType.append('bbH300_CMS_scale_t_etau_8TeVUp')
sampleTitle.append('BBH300')
sampleType.append('bbH300_CMS_scale_t_etau_8TeVDown')
sampleTitle.append('BBH300')
sampleType.append('bbH300_CMS_scale_jUp')
sampleTitle.append('BBH300')
sampleType.append('bbH300_CMS_scale_jDown')
sampleTitle.append('BBH300')
sampleType.append('bbH350')
sampleTitle.append('BBH350')
sampleType.append('bbH350_CMS_eff_t_mssmHigh_etau_8TeVUp')
sampleTitle.append('BBH350')
sampleType.append('bbH350_CMS_eff_t_mssmHigh_etau_8TeVDown')
sampleTitle.append('BBH350')
sampleType.append('bbH350_CMS_htt_higgsPtReweight_8TeVUp')
sampleTitle.append('BBH350')
sampleType.append('bbH350_CMS_htt_higgsPtReweight_8TeVDown')
sampleTitle.append('BBH350')
sampleType.append('bbH350_CMS_scale_t_etau_8TeVUp')
sampleTitle.append('BBH350')
sampleType.append('bbH350_CMS_scale_t_etau_8TeVDown')
sampleTitle.append('BBH350')
sampleType.append('bbH350_CMS_scale_jUp')
sampleTitle.append('BBH350')
sampleType.append('bbH350_CMS_scale_jDown')
sampleTitle.append('BBH350')
sampleType.append('bbH400')
sampleTitle.append('BBH400')
sampleType.append('bbH400_CMS_eff_t_mssmHigh_etau_8TeVUp')
sampleTitle.append('BBH400')
sampleType.append('bbH400_CMS_eff_t_mssmHigh_etau_8TeVDown')
sampleTitle.append('BBH400')
sampleType.append('bbH400_CMS_htt_higgsPtReweight_8TeVUp')
sampleTitle.append('BBH400')
sampleType.append('bbH400_CMS_htt_higgsPtReweight_8TeVDown')
sampleTitle.append('BBH400')
sampleType.append('bbH400_CMS_scale_t_etau_8TeVUp')
sampleTitle.append('BBH400')
sampleType.append('bbH400_CMS_scale_t_etau_8TeVDown')
sampleTitle.append('BBH400')
sampleType.append('bbH400_CMS_scale_jUp')
sampleTitle.append('BBH400')
sampleType.append('bbH400_CMS_scale_jDown')
sampleTitle.append('BBH400')
sampleType.append('bbH450')
sampleTitle.append('BBH450')
sampleType.append('bbH450_CMS_eff_t_mssmHigh_etau_8TeVUp')
sampleTitle.append('BBH450')
sampleType.append('bbH450_CMS_eff_t_mssmHigh_etau_8TeVDown')
sampleTitle.append('BBH450')
sampleType.append('bbH450_CMS_htt_higgsPtReweight_8TeVUp')
sampleTitle.append('BBH450')
sampleType.append('bbH450_CMS_htt_higgsPtReweight_8TeVDown')
sampleTitle.append('BBH450')
sampleType.append('bbH450_CMS_scale_t_etau_8TeVUp')
sampleTitle.append('BBH450')
sampleType.append('bbH450_CMS_scale_t_etau_8TeVDown')
sampleTitle.append('BBH450')
sampleType.append('bbH450_CMS_scale_jUp')
sampleTitle.append('BBH450')
sampleType.append('bbH450_CMS_scale_jDown')
sampleTitle.append('BBH450')
sampleType.append('bbH500')
sampleTitle.append('BBH500')
sampleType.append('bbH500_CMS_eff_t_mssmHigh_etau_8TeVUp')
sampleTitle.append('BBH500')
sampleType.append('bbH500_CMS_eff_t_mssmHigh_etau_8TeVDown')
sampleTitle.append('BBH500')
sampleType.append('bbH500_CMS_htt_higgsPtReweight_8TeVUp')
sampleTitle.append('BBH500')
sampleType.append('bbH500_CMS_htt_higgsPtReweight_8TeVDown')
sampleTitle.append('BBH500')
sampleType.append('bbH500_CMS_scale_t_etau_8TeVUp')
sampleTitle.append('BBH500')
sampleType.append('bbH500_CMS_scale_t_etau_8TeVDown')
sampleTitle.append('BBH500')
sampleType.append('bbH500_CMS_scale_jUp')
sampleTitle.append('BBH500')
sampleType.append('bbH500_CMS_scale_jDown')
sampleTitle.append('BBH500')
sampleType.append('bbH600')
sampleTitle.append('BBH600')
sampleType.append('bbH600_CMS_eff_t_mssmHigh_etau_8TeVUp')
sampleTitle.append('BBH600')
sampleType.append('bbH600_CMS_eff_t_mssmHigh_etau_8TeVDown')
sampleTitle.append('BBH600')
sampleType.append('bbH600_CMS_htt_higgsPtReweight_8TeVUp')
sampleTitle.append('BBH600')
sampleType.append('bbH600_CMS_htt_higgsPtReweight_8TeVDown')
sampleTitle.append('BBH600')
sampleType.append('bbH600_CMS_scale_t_etau_8TeVUp')
sampleTitle.append('BBH600')
sampleType.append('bbH600_CMS_scale_t_etau_8TeVDown')
sampleTitle.append('BBH600')
sampleType.append('bbH600_CMS_scale_jUp')
sampleTitle.append('BBH600')
sampleType.append('bbH600_CMS_scale_jDown')
sampleTitle.append('BBH600')
sampleType.append('bbH700')
sampleTitle.append('BBH700')
sampleType.append('bbH700_CMS_eff_t_mssmHigh_etau_8TeVUp')
sampleTitle.append('BBH700')
sampleType.append('bbH700_CMS_eff_t_mssmHigh_etau_8TeVDown')
sampleTitle.append('BBH700')
sampleType.append('bbH700_CMS_htt_higgsPtReweight_8TeVUp')
sampleTitle.append('BBH700')
sampleType.append('bbH700_CMS_htt_higgsPtReweight_8TeVDown')
sampleTitle.append('BBH700')
sampleType.append('bbH700_CMS_scale_t_etau_8TeVUp')
sampleTitle.append('BBH700')
sampleType.append('bbH700_CMS_scale_t_etau_8TeVDown')
sampleTitle.append('BBH700')
sampleType.append('bbH700_CMS_scale_jUp')
sampleTitle.append('BBH700')
sampleType.append('bbH700_CMS_scale_jDown')
sampleTitle.append('BBH700')
sampleType.append('bbH800')
sampleTitle.append('BBH800')
sampleType.append('bbH800_CMS_eff_t_mssmHigh_etau_8TeVUp')
sampleTitle.append('BBH800')
sampleType.append('bbH800_CMS_eff_t_mssmHigh_etau_8TeVDown')
sampleTitle.append('BBH800')
sampleType.append('bbH800_CMS_htt_higgsPtReweight_8TeVUp')
sampleTitle.append('BBH800')
sampleType.append('bbH800_CMS_htt_higgsPtReweight_8TeVDown')
sampleTitle.append('BBH800')
sampleType.append('bbH800_CMS_scale_t_etau_8TeVUp')
sampleTitle.append('BBH800')
sampleType.append('bbH800_CMS_scale_t_etau_8TeVDown')
sampleTitle.append('BBH800')
sampleType.append('bbH800_CMS_scale_jUp')
sampleTitle.append('BBH800')
sampleType.append('bbH800_CMS_scale_jDown')
sampleTitle.append('BBH800')
sampleType.append('bbH900')
sampleTitle.append('BBH900')
sampleType.append('bbH900_CMS_eff_t_mssmHigh_etau_8TeVUp')
sampleTitle.append('BBH900')
sampleType.append('bbH900_CMS_eff_t_mssmHigh_etau_8TeVDown')
sampleTitle.append('BBH900')
sampleType.append('bbH900_CMS_htt_higgsPtReweight_8TeVUp')
sampleTitle.append('BBH900')
sampleType.append('bbH900_CMS_htt_higgsPtReweight_8TeVDown')
sampleTitle.append('BBH900')
sampleType.append('bbH900_CMS_scale_t_etau_8TeVUp')
sampleTitle.append('BBH900')
sampleType.append('bbH900_CMS_scale_t_etau_8TeVDown')
sampleTitle.append('BBH900')
sampleType.append('bbH900_CMS_scale_jUp')
sampleTitle.append('BBH900')
sampleType.append('bbH900_CMS_scale_jDown')
sampleTitle.append('BBH900')
sampleType.append('bbH1000')
sampleTitle.append('BBH1000')
sampleType.append('bbH1000_CMS_eff_t_mssmHigh_etau_8TeVUp')
sampleTitle.append('BBH1000')
sampleType.append('bbH1000_CMS_eff_t_mssmHigh_etau_8TeVDown')
sampleTitle.append('BBH1000')
sampleType.append('bbH1000_CMS_htt_higgsPtReweight_8TeVUp')
sampleTitle.append('BBH1000')
sampleType.append('bbH1000_CMS_htt_higgsPtReweight_8TeVDown')
sampleTitle.append('BBH1000')
sampleType.append('bbH1000_CMS_scale_t_etau_8TeVUp')
sampleTitle.append('BBH1000')
sampleType.append('bbH1000_CMS_scale_t_etau_8TeVDown')
sampleTitle.append('BBH1000')
sampleType.append('bbH1000_CMS_scale_jUp')
sampleTitle.append('BBH1000')
sampleType.append('bbH1000_CMS_scale_jDown')
sampleTitle.append('BBH1000')

############
# ggH

sampleType.append('ggH80')
sampleTitle.append('GGH80')
sampleType.append('ggH80_CMS_eff_t_mssmHigh_etau_8TeVUp')
sampleTitle.append('GGH80')
sampleType.append('ggH80_CMS_eff_t_mssmHigh_etau_8TeVDown')
sampleTitle.append('GGH80')
sampleType.append('ggH80_CMS_htt_higgsPtReweight_8TeVUp')
sampleTitle.append('SUSYGGH80Up')
sampleType.append('ggH80_CMS_htt_higgsPtReweight_8TeVDown')
sampleTitle.append('SUSYGGH80Down')
sampleType.append('ggH80_CMS_scale_t_etau_8TeVUp')
sampleTitle.append('GGH80')
sampleType.append('ggH80_CMS_scale_t_etau_8TeVDown')
sampleTitle.append('GGH80')
sampleType.append('ggH80_CMS_scale_jUp')
sampleTitle.append('GGH80')
sampleType.append('ggH80_CMS_scale_jDown')
sampleTitle.append('GGH80')
sampleType.append('ggH90')
sampleTitle.append('GGH90')
sampleType.append('ggH90_CMS_eff_t_mssmHigh_etau_8TeVUp')
sampleTitle.append('GGH90')
sampleType.append('ggH90_CMS_eff_t_mssmHigh_etau_8TeVDown')
sampleTitle.append('GGH90')
sampleType.append('ggH90_CMS_htt_higgsPtReweight_8TeVUp')
sampleTitle.append('SUSYGGH90Up')
sampleType.append('ggH90_CMS_htt_higgsPtReweight_8TeVDown')
sampleTitle.append('SUSYGGH90Down')
sampleType.append('ggH90_CMS_scale_t_etau_8TeVUp')
sampleTitle.append('GGH90')
sampleType.append('ggH90_CMS_scale_t_etau_8TeVDown')
sampleTitle.append('GGH90')
sampleType.append('ggH90_CMS_scale_jUp')
sampleTitle.append('GGH90')
sampleType.append('ggH90_CMS_scale_jDown')
sampleTitle.append('GGH90')
sampleType.append('ggH100')
sampleTitle.append('GGH100')
sampleType.append('ggH100_CMS_eff_t_mssmHigh_etau_8TeVUp')
sampleTitle.append('GGH100')
sampleType.append('ggH100_CMS_eff_t_mssmHigh_etau_8TeVDown')
sampleTitle.append('GGH100')
sampleType.append('ggH100_CMS_htt_higgsPtReweight_8TeVUp')
sampleTitle.append('SUSYGGH100Up')
sampleType.append('ggH100_CMS_htt_higgsPtReweight_8TeVDown')
sampleTitle.append('SUSYGGH100Down')
sampleType.append('ggH100_CMS_scale_t_etau_8TeVUp')
sampleTitle.append('GGH100')
sampleType.append('ggH100_CMS_scale_t_etau_8TeVDown')
sampleTitle.append('GGH100')
sampleType.append('ggH100_CMS_scale_jUp')
sampleTitle.append('GGH100')
sampleType.append('ggH100_CMS_scale_jDown')
sampleTitle.append('GGH100')
sampleType.append('ggH110')
sampleTitle.append('GGH110')
sampleType.append('ggH110_CMS_eff_t_mssmHigh_etau_8TeVUp')
sampleTitle.append('GGH110')
sampleType.append('ggH110_CMS_eff_t_mssmHigh_etau_8TeVDown')
sampleTitle.append('GGH110')
sampleType.append('ggH110_CMS_htt_higgsPtReweight_8TeVUp')
sampleTitle.append('SUSYGGH110Up')
sampleType.append('ggH110_CMS_htt_higgsPtReweight_8TeVDown')
sampleTitle.append('SUSYGGH110Down')
sampleType.append('ggH110_CMS_scale_t_etau_8TeVUp')
sampleTitle.append('GGH110')
sampleType.append('ggH110_CMS_scale_t_etau_8TeVDown')
sampleTitle.append('GGH110')
sampleType.append('ggH110_CMS_scale_jUp')
sampleTitle.append('GGH110')
sampleType.append('ggH110_CMS_scale_jDown')
sampleTitle.append('GGH110')
sampleType.append('ggH120')
sampleTitle.append('GGH120')
sampleType.append('ggH120_CMS_eff_t_mssmHigh_etau_8TeVUp')
sampleTitle.append('GGH120')
sampleType.append('ggH120_CMS_eff_t_mssmHigh_etau_8TeVDown')
sampleTitle.append('GGH120')
sampleType.append('ggH120_CMS_htt_higgsPtReweight_8TeVUp')
sampleTitle.append('SUSYGGH120Up')
sampleType.append('ggH120_CMS_htt_higgsPtReweight_8TeVDown')
sampleTitle.append('SUSYGGH120Down')
sampleType.append('ggH120_CMS_scale_t_etau_8TeVUp')
sampleTitle.append('GGH120')
sampleType.append('ggH120_CMS_scale_t_etau_8TeVDown')
sampleTitle.append('GGH120')
sampleType.append('ggH120_CMS_scale_jUp')
sampleTitle.append('GGH120')
sampleType.append('ggH120_CMS_scale_jDown')
sampleTitle.append('GGH120')
sampleType.append('ggH130')
sampleTitle.append('GGH130')
sampleType.append('ggH130_CMS_eff_t_mssmHigh_etau_8TeVUp')
sampleTitle.append('GGH130')
sampleType.append('ggH130_CMS_eff_t_mssmHigh_etau_8TeVDown')
sampleTitle.append('GGH130')
sampleType.append('ggH130_CMS_htt_higgsPtReweight_8TeVUp')
sampleTitle.append('SUSYGGH130Up')
sampleType.append('ggH130_CMS_htt_higgsPtReweight_8TeVDown')
sampleTitle.append('SUSYGGH130Down')
sampleType.append('ggH130_CMS_scale_t_etau_8TeVUp')
sampleTitle.append('GGH130')
sampleType.append('ggH130_CMS_scale_t_etau_8TeVDown')
sampleTitle.append('GGH130')
sampleType.append('ggH130_CMS_scale_jUp')
sampleTitle.append('GGH130')
sampleType.append('ggH130_CMS_scale_jDown')
sampleTitle.append('GGH130')
sampleType.append('ggH140')
sampleTitle.append('GGH140')
sampleType.append('ggH140_CMS_eff_t_mssmHigh_etau_8TeVUp')
sampleTitle.append('GGH140')
sampleType.append('ggH140_CMS_eff_t_mssmHigh_etau_8TeVDown')
sampleTitle.append('GGH140')
sampleType.append('ggH140_CMS_htt_higgsPtReweight_8TeVUp')
sampleTitle.append('SUSYGGH140Up')
sampleType.append('ggH140_CMS_htt_higgsPtReweight_8TeVDown')
sampleTitle.append('SUSYGGH140Down')
sampleType.append('ggH140_CMS_scale_t_etau_8TeVUp')
sampleTitle.append('GGH140')
sampleType.append('ggH140_CMS_scale_t_etau_8TeVDown')
sampleTitle.append('GGH140')
sampleType.append('ggH140_CMS_scale_jUp')
sampleTitle.append('GGH140')
sampleType.append('ggH140_CMS_scale_jDown')
sampleTitle.append('GGH140')
sampleType.append('ggH160')
sampleTitle.append('GGH160')
sampleType.append('ggH160_CMS_eff_t_mssmHigh_etau_8TeVUp')
sampleTitle.append('GGH160')
sampleType.append('ggH160_CMS_eff_t_mssmHigh_etau_8TeVDown')
sampleTitle.append('GGH160')
sampleType.append('ggH160_CMS_htt_higgsPtReweight_8TeVUp')
sampleTitle.append('SUSYGGH160Up')
sampleType.append('ggH160_CMS_htt_higgsPtReweight_8TeVDown')
sampleTitle.append('SUSYGGH160Down')
sampleType.append('ggH160_CMS_scale_t_etau_8TeVUp')
sampleTitle.append('GGH160')
sampleType.append('ggH160_CMS_scale_t_etau_8TeVDown')
sampleTitle.append('GGH160')
sampleType.append('ggH160_CMS_scale_jUp')
sampleTitle.append('GGH160')
sampleType.append('ggH160_CMS_scale_jDown')
sampleTitle.append('GGH160')
sampleType.append('ggH180')
sampleTitle.append('GGH180')
sampleType.append('ggH180_CMS_eff_t_mssmHigh_etau_8TeVUp')
sampleTitle.append('GGH180')
sampleType.append('ggH180_CMS_eff_t_mssmHigh_etau_8TeVDown')
sampleTitle.append('GGH180')
sampleType.append('ggH180_CMS_htt_higgsPtReweight_8TeVUp')
sampleTitle.append('SUSYGGH180Up')
sampleType.append('ggH180_CMS_htt_higgsPtReweight_8TeVDown')
sampleTitle.append('SUSYGGH180Down')
sampleType.append('ggH180_CMS_scale_t_etau_8TeVUp')
sampleTitle.append('GGH180')
sampleType.append('ggH180_CMS_scale_t_etau_8TeVDown')
sampleTitle.append('GGH180')
sampleType.append('ggH180_CMS_scale_jUp')
sampleTitle.append('GGH180')
sampleType.append('ggH180_CMS_scale_jDown')
sampleTitle.append('GGH180')
sampleType.append('ggH200')
sampleTitle.append('GGH200')
sampleType.append('ggH200_CMS_eff_t_mssmHigh_etau_8TeVUp')
sampleTitle.append('GGH200')
sampleType.append('ggH200_CMS_eff_t_mssmHigh_etau_8TeVDown')
sampleTitle.append('GGH200')
sampleType.append('ggH200_CMS_htt_higgsPtReweight_8TeVUp')
sampleTitle.append('SUSYGGH200Up')
sampleType.append('ggH200_CMS_htt_higgsPtReweight_8TeVDown')
sampleTitle.append('SUSYGGH200Down')
sampleType.append('ggH200_CMS_scale_t_etau_8TeVUp')
sampleTitle.append('GGH200')
sampleType.append('ggH200_CMS_scale_t_etau_8TeVDown')
sampleTitle.append('GGH200')
sampleType.append('ggH200_CMS_scale_jUp')
sampleTitle.append('GGH200')
sampleType.append('ggH200_CMS_scale_jDown')
sampleTitle.append('GGH200')
sampleType.append('ggH250')
sampleTitle.append('GGH250')
sampleType.append('ggH250_CMS_eff_t_mssmHigh_etau_8TeVUp')
sampleTitle.append('GGH250')
sampleType.append('ggH250_CMS_eff_t_mssmHigh_etau_8TeVDown')
sampleTitle.append('GGH250')
sampleType.append('ggH250_CMS_htt_higgsPtReweight_8TeVUp')
sampleTitle.append('SUSYGGH250Up')
sampleType.append('ggH250_CMS_htt_higgsPtReweight_8TeVDown')
sampleTitle.append('SUSYGGH250Down')
sampleType.append('ggH250_CMS_scale_t_etau_8TeVUp')
sampleTitle.append('GGH250')
sampleType.append('ggH250_CMS_scale_t_etau_8TeVDown')
sampleTitle.append('GGH250')
sampleType.append('ggH250_CMS_scale_jUp')
sampleTitle.append('GGH250')
sampleType.append('ggH250_CMS_scale_jDown')
sampleTitle.append('GGH250')
sampleType.append('ggH300')
sampleTitle.append('GGH300')
sampleType.append('ggH300_CMS_eff_t_mssmHigh_etau_8TeVUp')
sampleTitle.append('GGH300')
sampleType.append('ggH300_CMS_eff_t_mssmHigh_etau_8TeVDown')
sampleTitle.append('GGH300')
sampleType.append('ggH300_CMS_htt_higgsPtReweight_8TeVUp')
sampleTitle.append('SUSYGGH300Up')
sampleType.append('ggH300_CMS_htt_higgsPtReweight_8TeVDown')
sampleTitle.append('SUSYGGH300Down')
sampleType.append('ggH300_CMS_scale_t_etau_8TeVUp')
sampleTitle.append('GGH300')
sampleType.append('ggH300_CMS_scale_t_etau_8TeVDown')
sampleTitle.append('GGH300')
sampleType.append('ggH300_CMS_scale_jUp')
sampleTitle.append('GGH300')
sampleType.append('ggH300_CMS_scale_jDown')
sampleTitle.append('GGH300')
sampleType.append('ggH350')
sampleTitle.append('GGH350')
sampleType.append('ggH350_CMS_eff_t_mssmHigh_etau_8TeVUp')
sampleTitle.append('GGH350')
sampleType.append('ggH350_CMS_eff_t_mssmHigh_etau_8TeVDown')
sampleTitle.append('GGH350')
sampleType.append('ggH350_CMS_htt_higgsPtReweight_8TeVUp')
sampleTitle.append('SUSYGGH350Up')
sampleType.append('ggH350_CMS_htt_higgsPtReweight_8TeVDown')
sampleTitle.append('SUSYGGH350Down')
sampleType.append('ggH350_CMS_scale_t_etau_8TeVUp')
sampleTitle.append('GGH350')
sampleType.append('ggH350_CMS_scale_t_etau_8TeVDown')
sampleTitle.append('GGH350')
sampleType.append('ggH350_CMS_scale_jUp')
sampleTitle.append('GGH350')
sampleType.append('ggH350_CMS_scale_jDown')
sampleTitle.append('GGH350')
sampleType.append('ggH400')
sampleTitle.append('GGH400')
sampleType.append('ggH400_CMS_eff_t_mssmHigh_etau_8TeVUp')
sampleTitle.append('GGH400')
sampleType.append('ggH400_CMS_eff_t_mssmHigh_etau_8TeVDown')
sampleTitle.append('GGH400')
sampleType.append('ggH400_CMS_htt_higgsPtReweight_8TeVUp')
sampleTitle.append('SUSYGGH400Up')
sampleType.append('ggH400_CMS_htt_higgsPtReweight_8TeVDown')
sampleTitle.append('SUSYGGH400Down')
sampleType.append('ggH400_CMS_scale_t_etau_8TeVUp')
sampleTitle.append('GGH400')
sampleType.append('ggH400_CMS_scale_t_etau_8TeVDown')
sampleTitle.append('GGH400')
sampleType.append('ggH400_CMS_scale_jUp')
sampleTitle.append('GGH400')
sampleType.append('ggH400_CMS_scale_jDown')
sampleTitle.append('GGH400')
sampleType.append('ggH450')
sampleTitle.append('GGH450')
sampleType.append('ggH450_CMS_eff_t_mssmHigh_etau_8TeVUp')
sampleTitle.append('GGH450')
sampleType.append('ggH450_CMS_eff_t_mssmHigh_etau_8TeVDown')
sampleTitle.append('GGH450')
sampleType.append('ggH450_CMS_htt_higgsPtReweight_8TeVUp')
sampleTitle.append('SUSYGGH450Up')
sampleType.append('ggH450_CMS_htt_higgsPtReweight_8TeVDown')
sampleTitle.append('SUSYGGH450Down')
sampleType.append('ggH450_CMS_scale_t_etau_8TeVUp')
sampleTitle.append('GGH450')
sampleType.append('ggH450_CMS_scale_t_etau_8TeVDown')
sampleTitle.append('GGH450')
sampleType.append('ggH450_CMS_scale_jUp')
sampleTitle.append('GGH450')
sampleType.append('ggH450_CMS_scale_jDown')
sampleTitle.append('GGH450')
sampleType.append('ggH500')
sampleTitle.append('GGH500')
sampleType.append('ggH500_CMS_eff_t_mssmHigh_etau_8TeVUp')
sampleTitle.append('GGH500')
sampleType.append('ggH500_CMS_eff_t_mssmHigh_etau_8TeVDown')
sampleTitle.append('GGH500')
sampleType.append('ggH500_CMS_htt_higgsPtReweight_8TeVUp')
sampleTitle.append('SUSYGGH500Up')
sampleType.append('ggH500_CMS_htt_higgsPtReweight_8TeVDown')
sampleTitle.append('SUSYGGH500Down')
sampleType.append('ggH500_CMS_scale_t_etau_8TeVUp')
sampleTitle.append('GGH500')
sampleType.append('ggH500_CMS_scale_t_etau_8TeVDown')
sampleTitle.append('GGH500')
sampleType.append('ggH500_CMS_scale_jUp')
sampleTitle.append('GGH500')
sampleType.append('ggH500_CMS_scale_jDown')
sampleTitle.append('GGH500')
sampleType.append('ggH600')
sampleTitle.append('GGH600')
sampleType.append('ggH600_CMS_eff_t_mssmHigh_etau_8TeVUp')
sampleTitle.append('GGH600')
sampleType.append('ggH600_CMS_eff_t_mssmHigh_etau_8TeVDown')
sampleTitle.append('GGH600')
sampleType.append('ggH600_CMS_htt_higgsPtReweight_8TeVUp')
sampleTitle.append('SUSYGGH600Up')
sampleType.append('ggH600_CMS_htt_higgsPtReweight_8TeVDown')
sampleTitle.append('SUSYGGH600Down')
sampleType.append('ggH600_CMS_scale_t_etau_8TeVUp')
sampleTitle.append('GGH600')
sampleType.append('ggH600_CMS_scale_t_etau_8TeVDown')
sampleTitle.append('GGH600')
sampleType.append('ggH600_CMS_scale_jUp')
sampleTitle.append('GGH600')
sampleType.append('ggH600_CMS_scale_jDown')
sampleTitle.append('GGH600')
sampleType.append('ggH700')
sampleTitle.append('GGH700')
sampleType.append('ggH700_CMS_eff_t_mssmHigh_etau_8TeVUp')
sampleTitle.append('GGH700')
sampleType.append('ggH700_CMS_eff_t_mssmHigh_etau_8TeVDown')
sampleTitle.append('GGH700')
sampleType.append('ggH700_CMS_htt_higgsPtReweight_8TeVUp')
sampleTitle.append('SUSYGGH700Up')
sampleType.append('ggH700_CMS_htt_higgsPtReweight_8TeVDown')
sampleTitle.append('SUSYGGH700Down')
sampleType.append('ggH700_CMS_scale_t_etau_8TeVUp')
sampleTitle.append('GGH700')
sampleType.append('ggH700_CMS_scale_t_etau_8TeVDown')
sampleTitle.append('GGH700')
sampleType.append('ggH700_CMS_scale_jUp')
sampleTitle.append('GGH700')
sampleType.append('ggH700_CMS_scale_jDown')
sampleTitle.append('GGH700')
sampleType.append('ggH800')
sampleTitle.append('GGH800')
sampleType.append('ggH800_CMS_eff_t_mssmHigh_etau_8TeVUp')
sampleTitle.append('GGH800')
sampleType.append('ggH800_CMS_eff_t_mssmHigh_etau_8TeVDown')
sampleTitle.append('GGH800')
sampleType.append('ggH800_CMS_htt_higgsPtReweight_8TeVUp')
sampleTitle.append('SUSYGGH800Up')
sampleType.append('ggH800_CMS_htt_higgsPtReweight_8TeVDown')
sampleTitle.append('SUSYGGH800Down')
sampleType.append('ggH800_CMS_scale_t_etau_8TeVUp')
sampleTitle.append('GGH800')
sampleType.append('ggH800_CMS_scale_t_etau_8TeVDown')
sampleTitle.append('GGH800')
sampleType.append('ggH800_CMS_scale_jUp')
sampleTitle.append('GGH800')
sampleType.append('ggH800_CMS_scale_jDown')
sampleTitle.append('GGH800')
sampleType.append('ggH900')
sampleTitle.append('GGH900')
sampleType.append('ggH900_CMS_eff_t_mssmHigh_etau_8TeVUp')
sampleTitle.append('GGH900')
sampleType.append('ggH900_CMS_eff_t_mssmHigh_etau_8TeVDown')
sampleTitle.append('GGH900')
sampleType.append('ggH900_CMS_htt_higgsPtReweight_8TeVUp')
sampleTitle.append('SUSYGGH900Up')
sampleType.append('ggH900_CMS_htt_higgsPtReweight_8TeVDown')
sampleTitle.append('SUSYGGH900Down')
sampleType.append('ggH900_CMS_scale_t_etau_8TeVUp')
sampleTitle.append('GGH900')
sampleType.append('ggH900_CMS_scale_t_etau_8TeVDown')
sampleTitle.append('GGH900')
sampleType.append('ggH900_CMS_scale_jUp')
sampleTitle.append('GGH900')
sampleType.append('ggH900_CMS_scale_jDown')
sampleTitle.append('GGH900')
sampleType.append('ggH1000')
sampleTitle.append('GGH1000')
sampleType.append('ggH1000_CMS_eff_t_mssmHigh_etau_8TeVUp')
sampleTitle.append('GGH1000')
sampleType.append('ggH1000_CMS_eff_t_mssmHigh_etau_8TeVDown')
sampleTitle.append('GGH1000')
sampleType.append('ggH1000_CMS_htt_higgsPtReweight_8TeVUp')
sampleTitle.append('SUSYGGH1000Up')
sampleType.append('ggH1000_CMS_htt_higgsPtReweight_8TeVDown')
sampleTitle.append('SUSYGGH1000Down')
sampleType.append('ggH1000_CMS_scale_t_etau_8TeVUp')
sampleTitle.append('GGH1000')
sampleType.append('ggH1000_CMS_scale_t_etau_8TeVDown')
sampleTitle.append('GGH1000')
sampleType.append('ggH1000_CMS_scale_jUp')
sampleTitle.append('GGH1000')
sampleType.append('ggH1000_CMS_scale_jDown')
sampleTitle.append('GGH1000')

############
# ggH (SM)

sampleType.append('ggH_SM125')
sampleTitle.append('GGFH125')

############
# qqH

sampleType.append('qqH_SM125')
sampleTitle.append('VBFH125')






#############################
# declare histogram dictionaries, and a list containing them
# follow same order as dataCardCategories

inclusive_Hists = {}
btag_Hists = {}
btag_high_Hists = {}
btag_low_Hists = {}
nobtag_Hists = {}
nobtag_high_Hists = {}
nobtag_medium_Hists = {}
nobtag_low_Hists = {}

histogram_dict_list = []
histogram_dict_list.append(inclusive_Hists)
histogram_dict_list.append(btag_Hists)
histogram_dict_list.append(btag_high_Hists)
histogram_dict_list.append(btag_low_Hists)
histogram_dict_list.append(nobtag_Hists)
histogram_dict_list.append(nobtag_high_Hists)
histogram_dict_list.append(nobtag_medium_Hists)
histogram_dict_list.append(nobtag_low_Hists)



#######################
# declare files

for evT in range(0, len(eventType)):
  fileName = "davis_htt_mssm_"+eventType[evT]+".root"
  dataCardFiles[fileName] = TFile( fileName, 'RECREATE', 'test' )

################################
# add directories to files

for evT in range(0, len(eventType)):
  fileName = "davis_htt_mssm_"+eventType[evT]+".root"
  dataCardFiles[fileName].cd()
  for index in range(0, len(dataCardCategories)):
    directoryName = eventType[evT]+"_"+dataCardCategories[index]
    TDirectoryFile(directoryName,directoryName)

#############################
# add histograms to dictionaries

for dictIndx in range(0, len(histogram_dict_list)):
  for sampleIndx in range(0, len(sampleType)):
    histName = sampleType[sampleIndx]+"_"+dataCardCategories[dictIndx]
    histogram_dict_list[dictIndx][sampleIndx] = TH1F(histName,sampleTitle[sampleIndx],100,0,1400)
    histogram_dict_list[dictIndx][sampleIndx].Sumw2()
    #histogram_dict_list[dictIndx][sampleIndx].SetDirectory(0)


def WriteEverything():
  for evT in range(0, len(eventType)):
    fileName = "davis_htt_mssm_"+eventType[evT]+".root"
    dataCardFiles[fileName].cd()
    for index in range(0, len(dataCardCategories)):
      directoryName = eventType[evT]+"_"+dataCardCategories[index]
      dataCardFiles[fileName].cd(directoryName)
      for sampleIndx in range(0, len(sampleType)):
        histName = sampleType[sampleIndx]+"_"+dataCardCategories[index]
        suffix = "_"+dataCardCategories[index]
        writeAs = histName[:-len(suffix)]
        histogram_dict_list[index][sampleIndx].Write(writeAs)
    dataCardFiles[fileName].Close()
  return


##########
# for testing

# def WriteEverything():
#   for evT in range(0, len(eventType)):
#     fileName = "davis_htt_mssm_"+eventType[evT]+".root"
#     dataCardFiles[fileName].cd()
#     for index in range(0, len(dataCardCategories)):
#       directoryName = eventType[evT]+"_"+dataCardCategories[index]
#       dataCardFiles[fileName].cd(directoryName)
#       for sampleIndx in range(0, len(sampleType)):
#         histName = sampleType[sampleIndx]+"_"+dataCardCategories[index]
#         suffix = "_"+dataCardCategories[index]
#         writeAs = histName[:-len(suffix)]
#         histogram_dict_list[index][sampleIndx].Write(writeAs)
#     dataCardFiles[fileName].Close()
#   return
