import time
import sys
import os
from ROOT import gROOT,TChain, TLorentzVector, TSelector, TTree, TF1, TH1F, TCanvas, gStyle, TFile
from ROOT import TDirectoryFile
from array import array

from Plotting.python.FileName import FileNamePrefix



###########################
# create the File dict

dataCardFiles = {}

##################
# master lists

eventType = []
dataCardCategories = []
sampleType = []
sampleTitle = []


##############################
# fill the lists

eventType.append("muTau")
eventType.append("eleTau")

dataCardCategories.append("inclusive")
dataCardCategories.append("btag")
dataCardCategories.append("btag_high")
dataCardCategories.append("btag_low")
dataCardCategories.append("nobtag")
dataCardCategories.append("nobtag_high")
dataCardCategories.append("nobtag_medium")
dataCardCategories.append("nobtag_low")

#########################
# create the histogram names and titles

sampleType.append('QCD')
sampleType.append('QCD_CMS_htt_QCDShape_etau_btag_8TeVDown')
sampleType.append('QCD_CMS_htt_QCDShape_etau_btag_8TeVDown_fine_binning')
sampleType.append('QCD_CMS_htt_QCDShape_etau_btag_8TeVUp')
sampleType.append('QCD_CMS_htt_QCDShape_etau_btag_8TeVUp_fine_binning')
sampleType.append('QCD_CMS_htt_QCDShape_etau_btag_high_8TeVDown')
sampleType.append('QCD_CMS_htt_QCDShape_etau_btag_high_8TeVDown_fine_binning')
sampleType.append('QCD_CMS_htt_QCDShape_etau_btag_high_8TeVUp')
sampleType.append('QCD_CMS_htt_QCDShape_etau_btag_high_8TeVUp_fine_binning')
sampleType.append('QCD_CMS_htt_QCDShape_etau_btag_low_8TeVDown')
sampleType.append('QCD_CMS_htt_QCDShape_etau_btag_low_8TeVDown_fine_binning')
sampleType.append('QCD_CMS_htt_QCDShape_etau_btag_low_8TeVUp')
sampleType.append('QCD_CMS_htt_QCDShape_etau_btag_low_8TeVUp_fine_binning')
sampleType.append('QCD_CMS_htt_QCDShape_etau_nobtag_8TeVDown')
sampleType.append('QCD_CMS_htt_QCDShape_etau_nobtag_8TeVDown_fine_binning')
sampleType.append('QCD_CMS_htt_QCDShape_etau_nobtag_8TeVUp')
sampleType.append('QCD_CMS_htt_QCDShape_etau_nobtag_8TeVUp_fine_binning')
sampleType.append('QCD_CMS_htt_QCDShape_etau_nobtag_high_8TeVDown')
sampleType.append('QCD_CMS_htt_QCDShape_etau_nobtag_high_8TeVDown_fine_binning')
sampleType.append('QCD_CMS_htt_QCDShape_etau_nobtag_high_8TeVUp')
sampleType.append('QCD_CMS_htt_QCDShape_etau_nobtag_high_8TeVUp_fine_binning')
sampleType.append('QCD_CMS_htt_QCDShape_etau_nobtag_low_8TeVDown')
sampleType.append('QCD_CMS_htt_QCDShape_etau_nobtag_low_8TeVDown_fine_binning')
sampleType.append('QCD_CMS_htt_QCDShape_etau_nobtag_low_8TeVUp')
sampleType.append('QCD_CMS_htt_QCDShape_etau_nobtag_low_8TeVUp_fine_binning')
sampleType.append('QCD_CMS_htt_QCDShape_etau_nobtag_medium_8TeVDown')
sampleType.append('QCD_CMS_htt_QCDShape_etau_nobtag_medium_8TeVDown_fine_binning')
sampleType.append('QCD_CMS_htt_QCDShape_etau_nobtag_medium_8TeVUp')
sampleType.append('QCD_CMS_htt_QCDShape_etau_nobtag_medium_8TeVUp_fine_binning')
sampleType.append('QCD_CMS_htt_QCDShape_mutau_btag_8TeVDown')
sampleType.append('QCD_CMS_htt_QCDShape_mutau_btag_8TeVDown_fine_binning')
sampleType.append('QCD_CMS_htt_QCDShape_mutau_btag_8TeVUp')
sampleType.append('QCD_CMS_htt_QCDShape_mutau_btag_8TeVUp_fine_binning')
sampleType.append('QCD_CMS_htt_QCDShape_mutau_btag_high_8TeVDown')
sampleType.append('QCD_CMS_htt_QCDShape_mutau_btag_high_8TeVDown_fine_binning')
sampleType.append('QCD_CMS_htt_QCDShape_mutau_btag_high_8TeVUp')
sampleType.append('QCD_CMS_htt_QCDShape_mutau_btag_high_8TeVUp_fine_binning')
sampleType.append('QCD_CMS_htt_QCDShape_mutau_btag_low_8TeVDown')
sampleType.append('QCD_CMS_htt_QCDShape_mutau_btag_low_8TeVDown_fine_binning')
sampleType.append('QCD_CMS_htt_QCDShape_mutau_btag_low_8TeVUp')
sampleType.append('QCD_CMS_htt_QCDShape_mutau_btag_low_8TeVUp_fine_binning')
sampleType.append('QCD_CMS_htt_QCDShape_mutau_nobtag_8TeVDown')
sampleType.append('QCD_CMS_htt_QCDShape_mutau_nobtag_8TeVDown_fine_binning')
sampleType.append('QCD_CMS_htt_QCDShape_mutau_nobtag_8TeVUp')
sampleType.append('QCD_CMS_htt_QCDShape_mutau_nobtag_8TeVUp_fine_binning')
sampleType.append('QCD_CMS_htt_QCDShape_mutau_nobtag_high_8TeVDown')
sampleType.append('QCD_CMS_htt_QCDShape_mutau_nobtag_high_8TeVDown_fine_binning')
sampleType.append('QCD_CMS_htt_QCDShape_mutau_nobtag_high_8TeVUp')
sampleType.append('QCD_CMS_htt_QCDShape_mutau_nobtag_high_8TeVUp_fine_binning')
sampleType.append('QCD_CMS_htt_QCDShape_mutau_nobtag_low_8TeVDown')
sampleType.append('QCD_CMS_htt_QCDShape_mutau_nobtag_low_8TeVDown_fine_binning')
sampleType.append('QCD_CMS_htt_QCDShape_mutau_nobtag_low_8TeVUp')
sampleType.append('QCD_CMS_htt_QCDShape_mutau_nobtag_low_8TeVUp_fine_binning')
sampleType.append('QCD_CMS_htt_QCDShape_mutau_nobtag_medium_8TeVDown')
sampleType.append('QCD_CMS_htt_QCDShape_mutau_nobtag_medium_8TeVDown_fine_binning')
sampleType.append('QCD_CMS_htt_QCDShape_mutau_nobtag_medium_8TeVUp')
sampleType.append('QCD_CMS_htt_QCDShape_mutau_nobtag_medium_8TeVUp_fine_binning')
sampleType.append('QCD_CMS_htt_QCDfrShape_etau_8TeVDown')
sampleType.append('QCD_CMS_htt_QCDfrShape_etau_8TeVDown_fine_binning')
sampleType.append('QCD_CMS_htt_QCDfrShape_etau_8TeVUp')
sampleType.append('QCD_CMS_htt_QCDfrShape_etau_8TeVUp_fine_binning')
sampleType.append('QCD_CMS_htt_QCDfrShape_mutau_8TeVDown')
sampleType.append('QCD_CMS_htt_QCDfrShape_mutau_8TeVDown_fine_binning')
sampleType.append('QCD_CMS_htt_QCDfrShape_mutau_8TeVUp')
sampleType.append('QCD_CMS_htt_QCDfrShape_mutau_8TeVUp_fine_binning')
sampleType.append('QCD_CMS_scale_jDown')
sampleType.append('QCD_CMS_scale_jDown_fine_binning')
sampleType.append('QCD_CMS_scale_jUp')
sampleType.append('QCD_CMS_scale_jUp_fine_binning')
sampleType.append('QCD_CMS_scale_t_etau_8TeVDown')
sampleType.append('QCD_CMS_scale_t_etau_8TeVDown_fine_binning')
sampleType.append('QCD_CMS_scale_t_etau_8TeVUp')
sampleType.append('QCD_CMS_scale_t_etau_8TeVUp_fine_binning')
sampleType.append('QCD_CMS_scale_t_mutau_8TeVDown')
sampleType.append('QCD_CMS_scale_t_mutau_8TeVDown_fine_binning')
sampleType.append('QCD_CMS_scale_t_mutau_8TeVUp')
sampleType.append('QCD_CMS_scale_t_mutau_8TeVUp_fine_binning')
sampleType.append('QCD_fine_binning')
sampleType.append('TT')
sampleType.append('TT_CMS_htt_ZLScale_etau_8TeVDown')
sampleType.append('TT_CMS_htt_ZLScale_etau_8TeVUp')
sampleType.append('TT_CMS_htt_ZLScale_mutau_8TeVDown')
sampleType.append('TT_CMS_htt_ZLScale_mutau_8TeVUp')
sampleType.append('TT_CMS_htt_ttbarPtReweight_8TeVDown')
sampleType.append('TT_CMS_htt_ttbarPtReweight_8TeVUp')
sampleType.append('TT_CMS_scale_jDown')
sampleType.append('TT_CMS_scale_jDown_fine_binning')
sampleType.append('TT_CMS_scale_jUp')
sampleType.append('TT_CMS_scale_jUp_fine_binning')
sampleType.append('TT_CMS_scale_t_etau_8TeVDown')
sampleType.append('TT_CMS_scale_t_etau_8TeVDown_fine_binning')
sampleType.append('TT_CMS_scale_t_etau_8TeVUp')
sampleType.append('TT_CMS_scale_t_etau_8TeVUp_fine_binning')
sampleType.append('TT_CMS_scale_t_mutau_8TeVDown')
sampleType.append('TT_CMS_scale_t_mutau_8TeVDown_fine_binning')
sampleType.append('TT_CMS_scale_t_mutau_8TeVUp')
sampleType.append('TT_CMS_scale_t_mutau_8TeVUp_fine_binning')
sampleType.append('TT_fine_binning')
sampleType.append('VH_SM125')
sampleType.append('VH_SM125_CMS_eff_t_mssmHigh_etau_8TeVDown')
sampleType.append('VH_SM125_CMS_eff_t_mssmHigh_etau_8TeVUp')
sampleType.append('VH_SM125_CMS_eff_t_mssmHigh_mutau_8TeVDown')
sampleType.append('VH_SM125_CMS_eff_t_mssmHigh_mutau_8TeVUp')
sampleType.append('VH_SM125_CMS_scale_jDown')
sampleType.append('VH_SM125_CMS_scale_jUp')
sampleType.append('VH_SM125_CMS_scale_t_etau_8TeVDown')
sampleType.append('VH_SM125_CMS_scale_t_etau_8TeVUp')
sampleType.append('VH_SM125_CMS_scale_t_mutau_8TeVDown')
sampleType.append('VH_SM125_CMS_scale_t_mutau_8TeVUp')
sampleType.append('VV')
sampleType.append('VV_CMS_scale_jDown')
sampleType.append('VV_CMS_scale_jDown_fine_binning')
sampleType.append('VV_CMS_scale_jUp')
sampleType.append('VV_CMS_scale_jUp_fine_binning')
sampleType.append('VV_CMS_scale_t_etau_8TeVDown')
sampleType.append('VV_CMS_scale_t_etau_8TeVDown_fine_binning')
sampleType.append('VV_CMS_scale_t_etau_8TeVUp')
sampleType.append('VV_CMS_scale_t_etau_8TeVUp_fine_binning')
sampleType.append('VV_CMS_scale_t_mutau_8TeVDown')
sampleType.append('VV_CMS_scale_t_mutau_8TeVDown_fine_binning')
sampleType.append('VV_CMS_scale_t_mutau_8TeVUp')
sampleType.append('VV_CMS_scale_t_mutau_8TeVUp_fine_binning')
sampleType.append('VV_fine_binning')
sampleType.append('W')
sampleType.append('W_CMS_htt_WShape_etau_btag_8TeVDown')
sampleType.append('W_CMS_htt_WShape_etau_btag_8TeVDown_fine_binning')
sampleType.append('W_CMS_htt_WShape_etau_btag_8TeVUp')
sampleType.append('W_CMS_htt_WShape_etau_btag_8TeVUp_fine_binning')
sampleType.append('W_CMS_htt_WShape_etau_btag_high_8TeVDown')
sampleType.append('W_CMS_htt_WShape_etau_btag_high_8TeVDown_fine_binning')
sampleType.append('W_CMS_htt_WShape_etau_btag_high_8TeVUp')
sampleType.append('W_CMS_htt_WShape_etau_btag_high_8TeVUp_fine_binning')
sampleType.append('W_CMS_htt_WShape_etau_btag_low_8TeVDown')
sampleType.append('W_CMS_htt_WShape_etau_btag_low_8TeVDown_fine_binning')
sampleType.append('W_CMS_htt_WShape_etau_btag_low_8TeVUp')
sampleType.append('W_CMS_htt_WShape_etau_btag_low_8TeVUp_fine_binning')
sampleType.append('W_CMS_htt_WShape_etau_nobtag_8TeVDown')
sampleType.append('W_CMS_htt_WShape_etau_nobtag_8TeVDown_fine_binning')
sampleType.append('W_CMS_htt_WShape_etau_nobtag_8TeVUp')
sampleType.append('W_CMS_htt_WShape_etau_nobtag_8TeVUp_fine_binning')
sampleType.append('W_CMS_htt_WShape_etau_nobtag_high_8TeVDown')
sampleType.append('W_CMS_htt_WShape_etau_nobtag_high_8TeVDown_fine_binning')
sampleType.append('W_CMS_htt_WShape_etau_nobtag_high_8TeVUp')
sampleType.append('W_CMS_htt_WShape_etau_nobtag_high_8TeVUp_fine_binning')
sampleType.append('W_CMS_htt_WShape_etau_nobtag_low_8TeVDown')
sampleType.append('W_CMS_htt_WShape_etau_nobtag_low_8TeVDown_fine_binning')
sampleType.append('W_CMS_htt_WShape_etau_nobtag_low_8TeVUp')
sampleType.append('W_CMS_htt_WShape_etau_nobtag_low_8TeVUp_fine_binning')
sampleType.append('W_CMS_htt_WShape_etau_nobtag_medium_8TeVDown')
sampleType.append('W_CMS_htt_WShape_etau_nobtag_medium_8TeVDown_fine_binning')
sampleType.append('W_CMS_htt_WShape_etau_nobtag_medium_8TeVUp')
sampleType.append('W_CMS_htt_WShape_etau_nobtag_medium_8TeVUp_fine_binning')
sampleType.append('W_CMS_htt_WShape_mutau_btag_8TeVDown')
sampleType.append('W_CMS_htt_WShape_mutau_btag_8TeVDown_fine_binning')
sampleType.append('W_CMS_htt_WShape_mutau_btag_8TeVUp')
sampleType.append('W_CMS_htt_WShape_mutau_btag_8TeVUp_fine_binning')
sampleType.append('W_CMS_htt_WShape_mutau_btag_high_8TeVDown')
sampleType.append('W_CMS_htt_WShape_mutau_btag_high_8TeVDown_fine_binning')
sampleType.append('W_CMS_htt_WShape_mutau_btag_high_8TeVUp')
sampleType.append('W_CMS_htt_WShape_mutau_btag_high_8TeVUp_fine_binning')
sampleType.append('W_CMS_htt_WShape_mutau_btag_low_8TeVDown')
sampleType.append('W_CMS_htt_WShape_mutau_btag_low_8TeVDown_fine_binning')
sampleType.append('W_CMS_htt_WShape_mutau_btag_low_8TeVUp')
sampleType.append('W_CMS_htt_WShape_mutau_btag_low_8TeVUp_fine_binning')
sampleType.append('W_CMS_htt_WShape_mutau_nobtag_8TeVDown')
sampleType.append('W_CMS_htt_WShape_mutau_nobtag_8TeVDown_fine_binning')
sampleType.append('W_CMS_htt_WShape_mutau_nobtag_8TeVUp')
sampleType.append('W_CMS_htt_WShape_mutau_nobtag_8TeVUp_fine_binning')
sampleType.append('W_CMS_htt_WShape_mutau_nobtag_high_8TeVDown')
sampleType.append('W_CMS_htt_WShape_mutau_nobtag_high_8TeVDown_fine_binning')
sampleType.append('W_CMS_htt_WShape_mutau_nobtag_high_8TeVUp')
sampleType.append('W_CMS_htt_WShape_mutau_nobtag_high_8TeVUp_fine_binning')
sampleType.append('W_CMS_htt_WShape_mutau_nobtag_low_8TeVDown')
sampleType.append('W_CMS_htt_WShape_mutau_nobtag_low_8TeVDown_fine_binning')
sampleType.append('W_CMS_htt_WShape_mutau_nobtag_low_8TeVUp')
sampleType.append('W_CMS_htt_WShape_mutau_nobtag_low_8TeVUp_fine_binning')
sampleType.append('W_CMS_htt_WShape_mutau_nobtag_medium_8TeVDown')
sampleType.append('W_CMS_htt_WShape_mutau_nobtag_medium_8TeVDown_fine_binning')
sampleType.append('W_CMS_htt_WShape_mutau_nobtag_medium_8TeVUp')
sampleType.append('W_CMS_htt_WShape_mutau_nobtag_medium_8TeVUp_fine_binning')
sampleType.append('W_CMS_scale_jDown')
sampleType.append('W_CMS_scale_jDown_fine_binning')
sampleType.append('W_CMS_scale_jUp')
sampleType.append('W_CMS_scale_jUp_fine_binning')
sampleType.append('W_CMS_scale_t_etau_8TeVDown')
sampleType.append('W_CMS_scale_t_etau_8TeVDown_fine_binning')
sampleType.append('W_CMS_scale_t_etau_8TeVUp')
sampleType.append('W_CMS_scale_t_etau_8TeVUp_fine_binning')
sampleType.append('W_CMS_scale_t_mutau_8TeVDown')
sampleType.append('W_CMS_scale_t_mutau_8TeVDown_fine_binning')
sampleType.append('W_CMS_scale_t_mutau_8TeVUp')
sampleType.append('W_CMS_scale_t_mutau_8TeVUp_fine_binning')
sampleType.append('W_fine_binning')
sampleType.append('ZJ')
sampleType.append('ZJ_CMS_scale_jDown')
sampleType.append('ZJ_CMS_scale_jDown_fine_binning')
sampleType.append('ZJ_CMS_scale_jUp')
sampleType.append('ZJ_CMS_scale_jUp_fine_binning')
sampleType.append('ZJ_CMS_scale_t_etau_8TeVDown')
sampleType.append('ZJ_CMS_scale_t_etau_8TeVDown_fine_binning')
sampleType.append('ZJ_CMS_scale_t_etau_8TeVUp')
sampleType.append('ZJ_CMS_scale_t_etau_8TeVUp_fine_binning')
sampleType.append('ZJ_CMS_scale_t_mutau_8TeVDown')
sampleType.append('ZJ_CMS_scale_t_mutau_8TeVDown_fine_binning')
sampleType.append('ZJ_CMS_scale_t_mutau_8TeVUp')
sampleType.append('ZJ_CMS_scale_t_mutau_8TeVUp_fine_binning')
sampleType.append('ZJ_fine_binning')
sampleType.append('ZL')
sampleType.append('ZLL')
sampleType.append('ZLL_CMS_scale_jDown')
sampleType.append('ZLL_CMS_scale_jDown_fine_binning')
sampleType.append('ZLL_CMS_scale_jUp')
sampleType.append('ZLL_CMS_scale_jUp_fine_binning')
sampleType.append('ZLL_CMS_scale_t_etau_8TeVDown')
sampleType.append('ZLL_CMS_scale_t_etau_8TeVDown_fine_binning')
sampleType.append('ZLL_CMS_scale_t_etau_8TeVUp')
sampleType.append('ZLL_CMS_scale_t_etau_8TeVUp_fine_binning')
sampleType.append('ZLL_CMS_scale_t_mutau_8TeVDown')
sampleType.append('ZLL_CMS_scale_t_mutau_8TeVDown_fine_binning')
sampleType.append('ZLL_CMS_scale_t_mutau_8TeVUp')
sampleType.append('ZLL_CMS_scale_t_mutau_8TeVUp_fine_binning')
sampleType.append('ZLL_fine_binning')
sampleType.append('ZL_CMS_htt_ZLScale_etau_8TeVDown')
sampleType.append('ZL_CMS_htt_ZLScale_etau_8TeVUp')
sampleType.append('ZL_CMS_htt_ZLScale_mutau_8TeVDown')
sampleType.append('ZL_CMS_htt_ZLScale_mutau_8TeVUp')
sampleType.append('ZL_CMS_scale_jDown')
sampleType.append('ZL_CMS_scale_jDown_fine_binning')
sampleType.append('ZL_CMS_scale_jUp')
sampleType.append('ZL_CMS_scale_jUp_fine_binning')
sampleType.append('ZL_CMS_scale_t_etau_8TeVDown')
sampleType.append('ZL_CMS_scale_t_etau_8TeVDown_fine_binning')
sampleType.append('ZL_CMS_scale_t_etau_8TeVUp')
sampleType.append('ZL_CMS_scale_t_etau_8TeVUp_fine_binning')
sampleType.append('ZL_CMS_scale_t_mutau_8TeVDown')
sampleType.append('ZL_CMS_scale_t_mutau_8TeVDown_fine_binning')
sampleType.append('ZL_CMS_scale_t_mutau_8TeVUp')
sampleType.append('ZL_CMS_scale_t_mutau_8TeVUp_fine_binning')
sampleType.append('ZL_fine_binning')
sampleType.append('ZTT')
sampleType.append('ZTT_CMS_scale_jDown')
sampleType.append('ZTT_CMS_scale_jDown_fine_binning')
sampleType.append('ZTT_CMS_scale_jUp')
sampleType.append('ZTT_CMS_scale_jUp_fine_binning')
sampleType.append('ZTT_CMS_scale_t_etau_8TeVDown')
sampleType.append('ZTT_CMS_scale_t_etau_8TeVDown_fine_binning')
sampleType.append('ZTT_CMS_scale_t_etau_8TeVUp')
sampleType.append('ZTT_CMS_scale_t_etau_8TeVUp_fine_binning')
sampleType.append('ZTT_CMS_scale_t_mutau_8TeVDown')
sampleType.append('ZTT_CMS_scale_t_mutau_8TeVDown_fine_binning')
sampleType.append('ZTT_CMS_scale_t_mutau_8TeVUp')
sampleType.append('ZTT_CMS_scale_t_mutau_8TeVUp_fine_binning')
sampleType.append('ZTT_fine_binning')
sampleType.append('bbH100')
sampleType.append('bbH1000')
sampleType.append('bbH1000_CMS_eff_t_mssmHigh_etau_8TeVDown')
sampleType.append('bbH1000_CMS_eff_t_mssmHigh_etau_8TeVUp')
sampleType.append('bbH1000_CMS_eff_t_mssmHigh_mutau_8TeVDown')
sampleType.append('bbH1000_CMS_eff_t_mssmHigh_mutau_8TeVUp')
sampleType.append('bbH1000_CMS_scale_jDown')
sampleType.append('bbH1000_CMS_scale_jUp')
sampleType.append('bbH1000_CMS_scale_t_etau_8TeVDown')
sampleType.append('bbH1000_CMS_scale_t_etau_8TeVUp')
sampleType.append('bbH1000_CMS_scale_t_mutau_8TeVDown')
sampleType.append('bbH1000_CMS_scale_t_mutau_8TeVUp')
sampleType.append('bbH100_CMS_eff_t_mssmHigh_etau_8TeVDown')
sampleType.append('bbH100_CMS_eff_t_mssmHigh_etau_8TeVUp')
sampleType.append('bbH100_CMS_eff_t_mssmHigh_mutau_8TeVDown')
sampleType.append('bbH100_CMS_eff_t_mssmHigh_mutau_8TeVUp')
sampleType.append('bbH100_CMS_scale_jDown')
sampleType.append('bbH100_CMS_scale_jUp')
sampleType.append('bbH100_CMS_scale_t_etau_8TeVDown')
sampleType.append('bbH100_CMS_scale_t_etau_8TeVUp')
sampleType.append('bbH100_CMS_scale_t_mutau_8TeVDown')
sampleType.append('bbH100_CMS_scale_t_mutau_8TeVUp')
sampleType.append('bbH110')
sampleType.append('bbH110_CMS_eff_t_mssmHigh_etau_8TeVDown')
sampleType.append('bbH110_CMS_eff_t_mssmHigh_etau_8TeVUp')
sampleType.append('bbH110_CMS_eff_t_mssmHigh_mutau_8TeVDown')
sampleType.append('bbH110_CMS_eff_t_mssmHigh_mutau_8TeVUp')
sampleType.append('bbH110_CMS_scale_jDown')
sampleType.append('bbH110_CMS_scale_jUp')
sampleType.append('bbH110_CMS_scale_t_etau_8TeVDown')
sampleType.append('bbH110_CMS_scale_t_etau_8TeVUp')
sampleType.append('bbH110_CMS_scale_t_mutau_8TeVDown')
sampleType.append('bbH110_CMS_scale_t_mutau_8TeVUp')
sampleType.append('bbH120')
sampleType.append('bbH120_CMS_eff_t_mssmHigh_etau_8TeVDown')
sampleType.append('bbH120_CMS_eff_t_mssmHigh_etau_8TeVUp')
sampleType.append('bbH120_CMS_eff_t_mssmHigh_mutau_8TeVDown')
sampleType.append('bbH120_CMS_eff_t_mssmHigh_mutau_8TeVUp')
sampleType.append('bbH120_CMS_scale_jDown')
sampleType.append('bbH120_CMS_scale_jUp')
sampleType.append('bbH120_CMS_scale_t_etau_8TeVDown')
sampleType.append('bbH120_CMS_scale_t_etau_8TeVUp')
sampleType.append('bbH120_CMS_scale_t_mutau_8TeVDown')
sampleType.append('bbH120_CMS_scale_t_mutau_8TeVUp')
sampleType.append('bbH130')
sampleType.append('bbH130_CMS_eff_t_mssmHigh_etau_8TeVDown')
sampleType.append('bbH130_CMS_eff_t_mssmHigh_etau_8TeVUp')
sampleType.append('bbH130_CMS_eff_t_mssmHigh_mutau_8TeVDown')
sampleType.append('bbH130_CMS_eff_t_mssmHigh_mutau_8TeVUp')
sampleType.append('bbH130_CMS_scale_jDown')
sampleType.append('bbH130_CMS_scale_jUp')
sampleType.append('bbH130_CMS_scale_t_etau_8TeVDown')
sampleType.append('bbH130_CMS_scale_t_etau_8TeVUp')
sampleType.append('bbH130_CMS_scale_t_mutau_8TeVDown')
sampleType.append('bbH130_CMS_scale_t_mutau_8TeVUp')
sampleType.append('bbH140')
sampleType.append('bbH140_CMS_eff_t_mssmHigh_etau_8TeVDown')
sampleType.append('bbH140_CMS_eff_t_mssmHigh_etau_8TeVUp')
sampleType.append('bbH140_CMS_eff_t_mssmHigh_mutau_8TeVDown')
sampleType.append('bbH140_CMS_eff_t_mssmHigh_mutau_8TeVUp')
sampleType.append('bbH140_CMS_scale_jDown')
sampleType.append('bbH140_CMS_scale_jUp')
sampleType.append('bbH140_CMS_scale_t_etau_8TeVDown')
sampleType.append('bbH140_CMS_scale_t_etau_8TeVUp')
sampleType.append('bbH140_CMS_scale_t_mutau_8TeVDown')
sampleType.append('bbH140_CMS_scale_t_mutau_8TeVUp')
sampleType.append('bbH160')
sampleType.append('bbH160_CMS_eff_t_mssmHigh_etau_8TeVDown')
sampleType.append('bbH160_CMS_eff_t_mssmHigh_etau_8TeVUp')
sampleType.append('bbH160_CMS_eff_t_mssmHigh_mutau_8TeVDown')
sampleType.append('bbH160_CMS_eff_t_mssmHigh_mutau_8TeVUp')
sampleType.append('bbH160_CMS_scale_jDown')
sampleType.append('bbH160_CMS_scale_jUp')
sampleType.append('bbH160_CMS_scale_t_etau_8TeVDown')
sampleType.append('bbH160_CMS_scale_t_etau_8TeVUp')
sampleType.append('bbH160_CMS_scale_t_mutau_8TeVDown')
sampleType.append('bbH160_CMS_scale_t_mutau_8TeVUp')
sampleType.append('bbH180')
sampleType.append('bbH180_CMS_eff_t_mssmHigh_etau_8TeVDown')
sampleType.append('bbH180_CMS_eff_t_mssmHigh_etau_8TeVUp')
sampleType.append('bbH180_CMS_eff_t_mssmHigh_mutau_8TeVDown')
sampleType.append('bbH180_CMS_eff_t_mssmHigh_mutau_8TeVUp')
sampleType.append('bbH180_CMS_scale_jDown')
sampleType.append('bbH180_CMS_scale_jUp')
sampleType.append('bbH180_CMS_scale_t_etau_8TeVDown')
sampleType.append('bbH180_CMS_scale_t_etau_8TeVUp')
sampleType.append('bbH180_CMS_scale_t_mutau_8TeVDown')
sampleType.append('bbH180_CMS_scale_t_mutau_8TeVUp')
sampleType.append('bbH200')
sampleType.append('bbH200_CMS_eff_t_mssmHigh_etau_8TeVDown')
sampleType.append('bbH200_CMS_eff_t_mssmHigh_etau_8TeVUp')
sampleType.append('bbH200_CMS_eff_t_mssmHigh_mutau_8TeVDown')
sampleType.append('bbH200_CMS_eff_t_mssmHigh_mutau_8TeVUp')
sampleType.append('bbH200_CMS_scale_jDown')
sampleType.append('bbH200_CMS_scale_jUp')
sampleType.append('bbH200_CMS_scale_t_etau_8TeVDown')
sampleType.append('bbH200_CMS_scale_t_etau_8TeVUp')
sampleType.append('bbH200_CMS_scale_t_mutau_8TeVDown')
sampleType.append('bbH200_CMS_scale_t_mutau_8TeVUp')
sampleType.append('bbH250')
sampleType.append('bbH250_CMS_eff_t_mssmHigh_etau_8TeVDown')
sampleType.append('bbH250_CMS_eff_t_mssmHigh_etau_8TeVUp')
sampleType.append('bbH250_CMS_eff_t_mssmHigh_mutau_8TeVDown')
sampleType.append('bbH250_CMS_eff_t_mssmHigh_mutau_8TeVUp')
sampleType.append('bbH250_CMS_scale_jDown')
sampleType.append('bbH250_CMS_scale_jUp')
sampleType.append('bbH250_CMS_scale_t_etau_8TeVDown')
sampleType.append('bbH250_CMS_scale_t_etau_8TeVUp')
sampleType.append('bbH250_CMS_scale_t_mutau_8TeVDown')
sampleType.append('bbH250_CMS_scale_t_mutau_8TeVUp')
sampleType.append('bbH300')
sampleType.append('bbH300_CMS_eff_t_mssmHigh_etau_8TeVDown')
sampleType.append('bbH300_CMS_eff_t_mssmHigh_etau_8TeVUp')
sampleType.append('bbH300_CMS_eff_t_mssmHigh_mutau_8TeVDown')
sampleType.append('bbH300_CMS_eff_t_mssmHigh_mutau_8TeVUp')
sampleType.append('bbH300_CMS_scale_jDown')
sampleType.append('bbH300_CMS_scale_jUp')
sampleType.append('bbH300_CMS_scale_t_etau_8TeVDown')
sampleType.append('bbH300_CMS_scale_t_etau_8TeVUp')
sampleType.append('bbH300_CMS_scale_t_mutau_8TeVDown')
sampleType.append('bbH300_CMS_scale_t_mutau_8TeVUp')
sampleType.append('bbH350')
sampleType.append('bbH350_CMS_eff_t_mssmHigh_etau_8TeVDown')
sampleType.append('bbH350_CMS_eff_t_mssmHigh_etau_8TeVUp')
sampleType.append('bbH350_CMS_eff_t_mssmHigh_mutau_8TeVDown')
sampleType.append('bbH350_CMS_eff_t_mssmHigh_mutau_8TeVUp')
sampleType.append('bbH350_CMS_scale_jDown')
sampleType.append('bbH350_CMS_scale_jUp')
sampleType.append('bbH350_CMS_scale_t_etau_8TeVDown')
sampleType.append('bbH350_CMS_scale_t_etau_8TeVUp')
sampleType.append('bbH350_CMS_scale_t_mutau_8TeVDown')
sampleType.append('bbH350_CMS_scale_t_mutau_8TeVUp')
sampleType.append('bbH400')
sampleType.append('bbH400_CMS_eff_t_mssmHigh_etau_8TeVDown')
sampleType.append('bbH400_CMS_eff_t_mssmHigh_etau_8TeVUp')
sampleType.append('bbH400_CMS_eff_t_mssmHigh_mutau_8TeVDown')
sampleType.append('bbH400_CMS_eff_t_mssmHigh_mutau_8TeVUp')
sampleType.append('bbH400_CMS_scale_jDown')
sampleType.append('bbH400_CMS_scale_jUp')
sampleType.append('bbH400_CMS_scale_t_etau_8TeVDown')
sampleType.append('bbH400_CMS_scale_t_etau_8TeVUp')
sampleType.append('bbH400_CMS_scale_t_mutau_8TeVDown')
sampleType.append('bbH400_CMS_scale_t_mutau_8TeVUp')
sampleType.append('bbH450')
sampleType.append('bbH450_CMS_eff_t_mssmHigh_etau_8TeVDown')
sampleType.append('bbH450_CMS_eff_t_mssmHigh_etau_8TeVUp')
sampleType.append('bbH450_CMS_eff_t_mssmHigh_mutau_8TeVDown')
sampleType.append('bbH450_CMS_eff_t_mssmHigh_mutau_8TeVUp')
sampleType.append('bbH450_CMS_scale_jDown')
sampleType.append('bbH450_CMS_scale_jUp')
sampleType.append('bbH450_CMS_scale_t_etau_8TeVDown')
sampleType.append('bbH450_CMS_scale_t_etau_8TeVUp')
sampleType.append('bbH450_CMS_scale_t_mutau_8TeVDown')
sampleType.append('bbH450_CMS_scale_t_mutau_8TeVUp')
sampleType.append('bbH500')
sampleType.append('bbH500_CMS_eff_t_mssmHigh_etau_8TeVDown')
sampleType.append('bbH500_CMS_eff_t_mssmHigh_etau_8TeVUp')
sampleType.append('bbH500_CMS_eff_t_mssmHigh_mutau_8TeVDown')
sampleType.append('bbH500_CMS_eff_t_mssmHigh_mutau_8TeVUp')
sampleType.append('bbH500_CMS_scale_jDown')
sampleType.append('bbH500_CMS_scale_jUp')
sampleType.append('bbH500_CMS_scale_t_etau_8TeVDown')
sampleType.append('bbH500_CMS_scale_t_etau_8TeVUp')
sampleType.append('bbH500_CMS_scale_t_mutau_8TeVDown')
sampleType.append('bbH500_CMS_scale_t_mutau_8TeVUp')
sampleType.append('bbH600')
sampleType.append('bbH600_CMS_eff_t_mssmHigh_etau_8TeVDown')
sampleType.append('bbH600_CMS_eff_t_mssmHigh_etau_8TeVUp')
sampleType.append('bbH600_CMS_eff_t_mssmHigh_mutau_8TeVDown')
sampleType.append('bbH600_CMS_eff_t_mssmHigh_mutau_8TeVUp')
sampleType.append('bbH600_CMS_scale_jDown')
sampleType.append('bbH600_CMS_scale_jUp')
sampleType.append('bbH600_CMS_scale_t_etau_8TeVDown')
sampleType.append('bbH600_CMS_scale_t_etau_8TeVUp')
sampleType.append('bbH600_CMS_scale_t_mutau_8TeVDown')
sampleType.append('bbH600_CMS_scale_t_mutau_8TeVUp')
sampleType.append('bbH700')
sampleType.append('bbH700_CMS_eff_t_mssmHigh_etau_8TeVDown')
sampleType.append('bbH700_CMS_eff_t_mssmHigh_etau_8TeVUp')
sampleType.append('bbH700_CMS_eff_t_mssmHigh_mutau_8TeVDown')
sampleType.append('bbH700_CMS_eff_t_mssmHigh_mutau_8TeVUp')
sampleType.append('bbH700_CMS_scale_jDown')
sampleType.append('bbH700_CMS_scale_jUp')
sampleType.append('bbH700_CMS_scale_t_etau_8TeVDown')
sampleType.append('bbH700_CMS_scale_t_etau_8TeVUp')
sampleType.append('bbH700_CMS_scale_t_mutau_8TeVDown')
sampleType.append('bbH700_CMS_scale_t_mutau_8TeVUp')
sampleType.append('bbH80')
sampleType.append('bbH800')
sampleType.append('bbH800_CMS_eff_t_mssmHigh_etau_8TeVDown')
sampleType.append('bbH800_CMS_eff_t_mssmHigh_etau_8TeVUp')
sampleType.append('bbH800_CMS_eff_t_mssmHigh_mutau_8TeVDown')
sampleType.append('bbH800_CMS_eff_t_mssmHigh_mutau_8TeVUp')
sampleType.append('bbH800_CMS_scale_jDown')
sampleType.append('bbH800_CMS_scale_jUp')
sampleType.append('bbH800_CMS_scale_t_etau_8TeVDown')
sampleType.append('bbH800_CMS_scale_t_etau_8TeVUp')
sampleType.append('bbH800_CMS_scale_t_mutau_8TeVDown')
sampleType.append('bbH800_CMS_scale_t_mutau_8TeVUp')
sampleType.append('bbH80_CMS_eff_t_mssmHigh_etau_8TeVDown')
sampleType.append('bbH80_CMS_eff_t_mssmHigh_etau_8TeVUp')
sampleType.append('bbH80_CMS_eff_t_mssmHigh_mutau_8TeVDown')
sampleType.append('bbH80_CMS_eff_t_mssmHigh_mutau_8TeVUp')
sampleType.append('bbH80_CMS_htt_higgsPtReweight_8TeVDown')
sampleType.append('bbH80_CMS_htt_higgsPtReweight_8TeVUp')
sampleType.append('bbH80_CMS_scale_jDown')
sampleType.append('bbH80_CMS_scale_jUp')
sampleType.append('bbH80_CMS_scale_t_etau_8TeVDown')
sampleType.append('bbH80_CMS_scale_t_etau_8TeVUp')
sampleType.append('bbH80_CMS_scale_t_mutau_8TeVDown')
sampleType.append('bbH80_CMS_scale_t_mutau_8TeVUp')
sampleType.append('bbH90')
sampleType.append('bbH900')
sampleType.append('bbH900_CMS_eff_t_mssmHigh_etau_8TeVDown')
sampleType.append('bbH900_CMS_eff_t_mssmHigh_etau_8TeVUp')
sampleType.append('bbH900_CMS_eff_t_mssmHigh_mutau_8TeVDown')
sampleType.append('bbH900_CMS_eff_t_mssmHigh_mutau_8TeVUp')
sampleType.append('bbH900_CMS_scale_jDown')
sampleType.append('bbH900_CMS_scale_jUp')
sampleType.append('bbH900_CMS_scale_t_etau_8TeVDown')
sampleType.append('bbH900_CMS_scale_t_etau_8TeVUp')
sampleType.append('bbH900_CMS_scale_t_mutau_8TeVDown')
sampleType.append('bbH900_CMS_scale_t_mutau_8TeVUp')
sampleType.append('bbH90_CMS_eff_t_mssmHigh_etau_8TeVDown')
sampleType.append('bbH90_CMS_eff_t_mssmHigh_etau_8TeVUp')
sampleType.append('bbH90_CMS_eff_t_mssmHigh_mutau_8TeVDown')
sampleType.append('bbH90_CMS_eff_t_mssmHigh_mutau_8TeVUp')
sampleType.append('bbH90_CMS_scale_jDown')
sampleType.append('bbH90_CMS_scale_jUp')
sampleType.append('bbH90_CMS_scale_t_etau_8TeVDown')
sampleType.append('bbH90_CMS_scale_t_etau_8TeVUp')
sampleType.append('bbH90_CMS_scale_t_mutau_8TeVDown')
sampleType.append('bbH90_CMS_scale_t_mutau_8TeVUp')
sampleType.append('data_obs')
sampleType.append('ggH100')
sampleType.append('ggH1000')
sampleType.append('ggH1000_CMS_eff_t_mssmHigh_etau_8TeVDown')
sampleType.append('ggH1000_CMS_eff_t_mssmHigh_etau_8TeVUp')
sampleType.append('ggH1000_CMS_eff_t_mssmHigh_mutau_8TeVDown')
sampleType.append('ggH1000_CMS_eff_t_mssmHigh_mutau_8TeVUp')
sampleType.append('ggH1000_CMS_htt_higgsPtReweight_8TeVDown')
sampleType.append('ggH1000_CMS_htt_higgsPtReweight_8TeVUp')
sampleType.append('ggH1000_CMS_htt_higgsPtReweight_scale_8TeVDown')
sampleType.append('ggH1000_CMS_htt_higgsPtReweight_scale_8TeVUp')
sampleType.append('ggH1000_CMS_scale_jDown')
sampleType.append('ggH1000_CMS_scale_jUp')
sampleType.append('ggH1000_CMS_scale_t_etau_8TeVDown')
sampleType.append('ggH1000_CMS_scale_t_etau_8TeVUp')
sampleType.append('ggH1000_CMS_scale_t_mutau_8TeVDown')
sampleType.append('ggH1000_CMS_scale_t_mutau_8TeVUp')
sampleType.append('ggH100_CMS_eff_t_mssmHigh_etau_8TeVDown')
sampleType.append('ggH100_CMS_eff_t_mssmHigh_etau_8TeVUp')
sampleType.append('ggH100_CMS_eff_t_mssmHigh_mutau_8TeVDown')
sampleType.append('ggH100_CMS_eff_t_mssmHigh_mutau_8TeVUp')
sampleType.append('ggH100_CMS_htt_higgsPtReweight_8TeVDown')
sampleType.append('ggH100_CMS_htt_higgsPtReweight_8TeVUp')
sampleType.append('ggH100_CMS_htt_higgsPtReweight_scale_8TeVDown')
sampleType.append('ggH100_CMS_htt_higgsPtReweight_scale_8TeVUp')
sampleType.append('ggH100_CMS_scale_jDown')
sampleType.append('ggH100_CMS_scale_jUp')
sampleType.append('ggH100_CMS_scale_t_etau_8TeVDown')
sampleType.append('ggH100_CMS_scale_t_etau_8TeVUp')
sampleType.append('ggH100_CMS_scale_t_mutau_8TeVDown')
sampleType.append('ggH100_CMS_scale_t_mutau_8TeVUp')
sampleType.append('ggH110')
sampleType.append('ggH110_CMS_eff_t_mssmHigh_etau_8TeVDown')
sampleType.append('ggH110_CMS_eff_t_mssmHigh_etau_8TeVUp')
sampleType.append('ggH110_CMS_eff_t_mssmHigh_mutau_8TeVDown')
sampleType.append('ggH110_CMS_eff_t_mssmHigh_mutau_8TeVUp')
sampleType.append('ggH110_CMS_htt_higgsPtReweight_8TeVDown')
sampleType.append('ggH110_CMS_htt_higgsPtReweight_8TeVUp')
sampleType.append('ggH110_CMS_htt_higgsPtReweight_scale_8TeVDown')
sampleType.append('ggH110_CMS_htt_higgsPtReweight_scale_8TeVUp')
sampleType.append('ggH110_CMS_scale_jDown')
sampleType.append('ggH110_CMS_scale_jUp')
sampleType.append('ggH110_CMS_scale_t_etau_8TeVDown')
sampleType.append('ggH110_CMS_scale_t_etau_8TeVUp')
sampleType.append('ggH110_CMS_scale_t_mutau_8TeVDown')
sampleType.append('ggH110_CMS_scale_t_mutau_8TeVUp')
sampleType.append('ggH120')
sampleType.append('ggH120_CMS_eff_t_mssmHigh_etau_8TeVDown')
sampleType.append('ggH120_CMS_eff_t_mssmHigh_etau_8TeVUp')
sampleType.append('ggH120_CMS_eff_t_mssmHigh_mutau_8TeVDown')
sampleType.append('ggH120_CMS_eff_t_mssmHigh_mutau_8TeVUp')
sampleType.append('ggH120_CMS_htt_higgsPtReweight_8TeVDown')
sampleType.append('ggH120_CMS_htt_higgsPtReweight_8TeVUp')
sampleType.append('ggH120_CMS_htt_higgsPtReweight_scale_8TeVDown')
sampleType.append('ggH120_CMS_htt_higgsPtReweight_scale_8TeVUp')
sampleType.append('ggH120_CMS_scale_jDown')
sampleType.append('ggH120_CMS_scale_jUp')
sampleType.append('ggH120_CMS_scale_t_etau_8TeVDown')
sampleType.append('ggH120_CMS_scale_t_etau_8TeVUp')
sampleType.append('ggH120_CMS_scale_t_mutau_8TeVDown')
sampleType.append('ggH120_CMS_scale_t_mutau_8TeVUp')
sampleType.append('ggH130')
sampleType.append('ggH130_CMS_eff_t_mssmHigh_etau_8TeVDown')
sampleType.append('ggH130_CMS_eff_t_mssmHigh_etau_8TeVUp')
sampleType.append('ggH130_CMS_eff_t_mssmHigh_mutau_8TeVDown')
sampleType.append('ggH130_CMS_eff_t_mssmHigh_mutau_8TeVUp')
sampleType.append('ggH130_CMS_htt_higgsPtReweight_8TeVDown')
sampleType.append('ggH130_CMS_htt_higgsPtReweight_8TeVUp')
sampleType.append('ggH130_CMS_htt_higgsPtReweight_scale_8TeVDown')
sampleType.append('ggH130_CMS_htt_higgsPtReweight_scale_8TeVUp')
sampleType.append('ggH130_CMS_scale_jDown')
sampleType.append('ggH130_CMS_scale_jUp')
sampleType.append('ggH130_CMS_scale_t_etau_8TeVDown')
sampleType.append('ggH130_CMS_scale_t_etau_8TeVUp')
sampleType.append('ggH130_CMS_scale_t_mutau_8TeVDown')
sampleType.append('ggH130_CMS_scale_t_mutau_8TeVUp')
sampleType.append('ggH140')
sampleType.append('ggH140_CMS_eff_t_mssmHigh_etau_8TeVDown')
sampleType.append('ggH140_CMS_eff_t_mssmHigh_etau_8TeVUp')
sampleType.append('ggH140_CMS_eff_t_mssmHigh_mutau_8TeVDown')
sampleType.append('ggH140_CMS_eff_t_mssmHigh_mutau_8TeVUp')
sampleType.append('ggH140_CMS_htt_higgsPtReweight_8TeVDown')
sampleType.append('ggH140_CMS_htt_higgsPtReweight_8TeVUp')
sampleType.append('ggH140_CMS_htt_higgsPtReweight_scale_8TeVDown')
sampleType.append('ggH140_CMS_htt_higgsPtReweight_scale_8TeVUp')
sampleType.append('ggH140_CMS_scale_jDown')
sampleType.append('ggH140_CMS_scale_jUp')
sampleType.append('ggH140_CMS_scale_t_etau_8TeVDown')
sampleType.append('ggH140_CMS_scale_t_etau_8TeVUp')
sampleType.append('ggH140_CMS_scale_t_mutau_8TeVDown')
sampleType.append('ggH140_CMS_scale_t_mutau_8TeVUp')
sampleType.append('ggH160')
sampleType.append('ggH160_CMS_eff_t_mssmHigh_etau_8TeVDown')
sampleType.append('ggH160_CMS_eff_t_mssmHigh_etau_8TeVUp')
sampleType.append('ggH160_CMS_eff_t_mssmHigh_mutau_8TeVDown')
sampleType.append('ggH160_CMS_eff_t_mssmHigh_mutau_8TeVUp')
sampleType.append('ggH160_CMS_htt_higgsPtReweight_8TeVDown')
sampleType.append('ggH160_CMS_htt_higgsPtReweight_8TeVUp')
sampleType.append('ggH160_CMS_htt_higgsPtReweight_scale_8TeVDown')
sampleType.append('ggH160_CMS_htt_higgsPtReweight_scale_8TeVUp')
sampleType.append('ggH160_CMS_scale_jDown')
sampleType.append('ggH160_CMS_scale_jUp')
sampleType.append('ggH160_CMS_scale_t_etau_8TeVDown')
sampleType.append('ggH160_CMS_scale_t_etau_8TeVUp')
sampleType.append('ggH160_CMS_scale_t_mutau_8TeVDown')
sampleType.append('ggH160_CMS_scale_t_mutau_8TeVUp')
sampleType.append('ggH180')
sampleType.append('ggH180_CMS_eff_t_mssmHigh_etau_8TeVDown')
sampleType.append('ggH180_CMS_eff_t_mssmHigh_etau_8TeVUp')
sampleType.append('ggH180_CMS_eff_t_mssmHigh_mutau_8TeVDown')
sampleType.append('ggH180_CMS_eff_t_mssmHigh_mutau_8TeVUp')
sampleType.append('ggH180_CMS_htt_higgsPtReweight_8TeVDown')
sampleType.append('ggH180_CMS_htt_higgsPtReweight_8TeVUp')
sampleType.append('ggH180_CMS_htt_higgsPtReweight_scale_8TeVDown')
sampleType.append('ggH180_CMS_htt_higgsPtReweight_scale_8TeVUp')
sampleType.append('ggH180_CMS_scale_jDown')
sampleType.append('ggH180_CMS_scale_jUp')
sampleType.append('ggH180_CMS_scale_t_etau_8TeVDown')
sampleType.append('ggH180_CMS_scale_t_etau_8TeVUp')
sampleType.append('ggH180_CMS_scale_t_mutau_8TeVDown')
sampleType.append('ggH180_CMS_scale_t_mutau_8TeVUp')
sampleType.append('ggH200')
sampleType.append('ggH200_CMS_eff_t_mssmHigh_etau_8TeVDown')
sampleType.append('ggH200_CMS_eff_t_mssmHigh_etau_8TeVUp')
sampleType.append('ggH200_CMS_eff_t_mssmHigh_mutau_8TeVDown')
sampleType.append('ggH200_CMS_eff_t_mssmHigh_mutau_8TeVUp')
sampleType.append('ggH200_CMS_htt_higgsPtReweight_8TeVDown')
sampleType.append('ggH200_CMS_htt_higgsPtReweight_8TeVUp')
sampleType.append('ggH200_CMS_htt_higgsPtReweight_scale_8TeVDown')
sampleType.append('ggH200_CMS_htt_higgsPtReweight_scale_8TeVUp')
sampleType.append('ggH200_CMS_scale_jDown')
sampleType.append('ggH200_CMS_scale_jUp')
sampleType.append('ggH200_CMS_scale_t_etau_8TeVDown')
sampleType.append('ggH200_CMS_scale_t_etau_8TeVUp')
sampleType.append('ggH200_CMS_scale_t_mutau_8TeVDown')
sampleType.append('ggH200_CMS_scale_t_mutau_8TeVUp')
sampleType.append('ggH250')
sampleType.append('ggH250_CMS_eff_t_mssmHigh_etau_8TeVDown')
sampleType.append('ggH250_CMS_eff_t_mssmHigh_etau_8TeVUp')
sampleType.append('ggH250_CMS_eff_t_mssmHigh_mutau_8TeVDown')
sampleType.append('ggH250_CMS_eff_t_mssmHigh_mutau_8TeVUp')
sampleType.append('ggH250_CMS_htt_higgsPtReweight_8TeVDown')
sampleType.append('ggH250_CMS_htt_higgsPtReweight_8TeVUp')
sampleType.append('ggH250_CMS_htt_higgsPtReweight_scale_8TeVDown')
sampleType.append('ggH250_CMS_htt_higgsPtReweight_scale_8TeVUp')
sampleType.append('ggH250_CMS_scale_jDown')
sampleType.append('ggH250_CMS_scale_jUp')
sampleType.append('ggH250_CMS_scale_t_etau_8TeVDown')
sampleType.append('ggH250_CMS_scale_t_etau_8TeVUp')
sampleType.append('ggH250_CMS_scale_t_mutau_8TeVDown')
sampleType.append('ggH250_CMS_scale_t_mutau_8TeVUp')
sampleType.append('ggH300')
sampleType.append('ggH300_CMS_eff_t_mssmHigh_etau_8TeVDown')
sampleType.append('ggH300_CMS_eff_t_mssmHigh_etau_8TeVUp')
sampleType.append('ggH300_CMS_eff_t_mssmHigh_mutau_8TeVDown')
sampleType.append('ggH300_CMS_eff_t_mssmHigh_mutau_8TeVUp')
sampleType.append('ggH300_CMS_htt_higgsPtReweight_8TeVDown')
sampleType.append('ggH300_CMS_htt_higgsPtReweight_8TeVUp')
sampleType.append('ggH300_CMS_htt_higgsPtReweight_scale_8TeVDown')
sampleType.append('ggH300_CMS_htt_higgsPtReweight_scale_8TeVUp')
sampleType.append('ggH300_CMS_scale_jDown')
sampleType.append('ggH300_CMS_scale_jUp')
sampleType.append('ggH300_CMS_scale_t_etau_8TeVDown')
sampleType.append('ggH300_CMS_scale_t_etau_8TeVUp')
sampleType.append('ggH300_CMS_scale_t_mutau_8TeVDown')
sampleType.append('ggH300_CMS_scale_t_mutau_8TeVUp')
sampleType.append('ggH350')
sampleType.append('ggH350_CMS_eff_t_mssmHigh_etau_8TeVDown')
sampleType.append('ggH350_CMS_eff_t_mssmHigh_etau_8TeVUp')
sampleType.append('ggH350_CMS_eff_t_mssmHigh_mutau_8TeVDown')
sampleType.append('ggH350_CMS_eff_t_mssmHigh_mutau_8TeVUp')
sampleType.append('ggH350_CMS_htt_higgsPtReweight_8TeVDown')
sampleType.append('ggH350_CMS_htt_higgsPtReweight_8TeVUp')
sampleType.append('ggH350_CMS_htt_higgsPtReweight_scale_8TeVDown')
sampleType.append('ggH350_CMS_htt_higgsPtReweight_scale_8TeVUp')
sampleType.append('ggH350_CMS_scale_jDown')
sampleType.append('ggH350_CMS_scale_jUp')
sampleType.append('ggH350_CMS_scale_t_etau_8TeVDown')
sampleType.append('ggH350_CMS_scale_t_etau_8TeVUp')
sampleType.append('ggH350_CMS_scale_t_mutau_8TeVDown')
sampleType.append('ggH350_CMS_scale_t_mutau_8TeVUp')
sampleType.append('ggH400')
sampleType.append('ggH400_CMS_eff_t_mssmHigh_etau_8TeVDown')
sampleType.append('ggH400_CMS_eff_t_mssmHigh_etau_8TeVUp')
sampleType.append('ggH400_CMS_eff_t_mssmHigh_mutau_8TeVDown')
sampleType.append('ggH400_CMS_eff_t_mssmHigh_mutau_8TeVUp')
sampleType.append('ggH400_CMS_htt_higgsPtReweight_8TeVDown')
sampleType.append('ggH400_CMS_htt_higgsPtReweight_8TeVUp')
sampleType.append('ggH400_CMS_htt_higgsPtReweight_scale_8TeVDown')
sampleType.append('ggH400_CMS_htt_higgsPtReweight_scale_8TeVUp')
sampleType.append('ggH400_CMS_scale_jDown')
sampleType.append('ggH400_CMS_scale_jUp')
sampleType.append('ggH400_CMS_scale_t_etau_8TeVDown')
sampleType.append('ggH400_CMS_scale_t_etau_8TeVUp')
sampleType.append('ggH400_CMS_scale_t_mutau_8TeVDown')
sampleType.append('ggH400_CMS_scale_t_mutau_8TeVUp')
sampleType.append('ggH450')
sampleType.append('ggH450_CMS_eff_t_mssmHigh_etau_8TeVDown')
sampleType.append('ggH450_CMS_eff_t_mssmHigh_etau_8TeVUp')
sampleType.append('ggH450_CMS_eff_t_mssmHigh_mutau_8TeVDown')
sampleType.append('ggH450_CMS_eff_t_mssmHigh_mutau_8TeVUp')
sampleType.append('ggH450_CMS_htt_higgsPtReweight_8TeVDown')
sampleType.append('ggH450_CMS_htt_higgsPtReweight_8TeVUp')
sampleType.append('ggH450_CMS_htt_higgsPtReweight_scale_8TeVDown')
sampleType.append('ggH450_CMS_htt_higgsPtReweight_scale_8TeVUp')
sampleType.append('ggH450_CMS_scale_jDown')
sampleType.append('ggH450_CMS_scale_jUp')
sampleType.append('ggH450_CMS_scale_t_etau_8TeVDown')
sampleType.append('ggH450_CMS_scale_t_etau_8TeVUp')
sampleType.append('ggH450_CMS_scale_t_mutau_8TeVDown')
sampleType.append('ggH450_CMS_scale_t_mutau_8TeVUp')
sampleType.append('ggH500')
sampleType.append('ggH500_CMS_eff_t_mssmHigh_etau_8TeVDown')
sampleType.append('ggH500_CMS_eff_t_mssmHigh_etau_8TeVUp')
sampleType.append('ggH500_CMS_eff_t_mssmHigh_mutau_8TeVDown')
sampleType.append('ggH500_CMS_eff_t_mssmHigh_mutau_8TeVUp')
sampleType.append('ggH500_CMS_htt_higgsPtReweight_8TeVDown')
sampleType.append('ggH500_CMS_htt_higgsPtReweight_8TeVUp')
sampleType.append('ggH500_CMS_htt_higgsPtReweight_scale_8TeVDown')
sampleType.append('ggH500_CMS_htt_higgsPtReweight_scale_8TeVUp')
sampleType.append('ggH500_CMS_scale_jDown')
sampleType.append('ggH500_CMS_scale_jUp')
sampleType.append('ggH500_CMS_scale_t_etau_8TeVDown')
sampleType.append('ggH500_CMS_scale_t_etau_8TeVUp')
sampleType.append('ggH500_CMS_scale_t_mutau_8TeVDown')
sampleType.append('ggH500_CMS_scale_t_mutau_8TeVUp')
sampleType.append('ggH600')
sampleType.append('ggH600_CMS_eff_t_mssmHigh_etau_8TeVDown')
sampleType.append('ggH600_CMS_eff_t_mssmHigh_etau_8TeVUp')
sampleType.append('ggH600_CMS_eff_t_mssmHigh_mutau_8TeVDown')
sampleType.append('ggH600_CMS_eff_t_mssmHigh_mutau_8TeVUp')
sampleType.append('ggH600_CMS_htt_higgsPtReweight_8TeVDown')
sampleType.append('ggH600_CMS_htt_higgsPtReweight_8TeVUp')
sampleType.append('ggH600_CMS_htt_higgsPtReweight_scale_8TeVDown')
sampleType.append('ggH600_CMS_htt_higgsPtReweight_scale_8TeVUp')
sampleType.append('ggH600_CMS_scale_jDown')
sampleType.append('ggH600_CMS_scale_jUp')
sampleType.append('ggH600_CMS_scale_t_etau_8TeVDown')
sampleType.append('ggH600_CMS_scale_t_etau_8TeVUp')
sampleType.append('ggH600_CMS_scale_t_mutau_8TeVDown')
sampleType.append('ggH600_CMS_scale_t_mutau_8TeVUp')
sampleType.append('ggH700')
sampleType.append('ggH700_CMS_eff_t_mssmHigh_etau_8TeVDown')
sampleType.append('ggH700_CMS_eff_t_mssmHigh_etau_8TeVUp')
sampleType.append('ggH700_CMS_eff_t_mssmHigh_mutau_8TeVDown')
sampleType.append('ggH700_CMS_eff_t_mssmHigh_mutau_8TeVUp')
sampleType.append('ggH700_CMS_htt_higgsPtReweight_8TeVDown')
sampleType.append('ggH700_CMS_htt_higgsPtReweight_8TeVUp')
sampleType.append('ggH700_CMS_htt_higgsPtReweight_scale_8TeVDown')
sampleType.append('ggH700_CMS_htt_higgsPtReweight_scale_8TeVUp')
sampleType.append('ggH700_CMS_scale_jDown')
sampleType.append('ggH700_CMS_scale_jUp')
sampleType.append('ggH700_CMS_scale_t_etau_8TeVDown')
sampleType.append('ggH700_CMS_scale_t_etau_8TeVUp')
sampleType.append('ggH700_CMS_scale_t_mutau_8TeVDown')
sampleType.append('ggH700_CMS_scale_t_mutau_8TeVUp')
sampleType.append('ggH80')
sampleType.append('ggH800')
sampleType.append('ggH800_CMS_eff_t_mssmHigh_etau_8TeVDown')
sampleType.append('ggH800_CMS_eff_t_mssmHigh_etau_8TeVUp')
sampleType.append('ggH800_CMS_eff_t_mssmHigh_mutau_8TeVDown')
sampleType.append('ggH800_CMS_eff_t_mssmHigh_mutau_8TeVUp')
sampleType.append('ggH800_CMS_htt_higgsPtReweight_8TeVDown')
sampleType.append('ggH800_CMS_htt_higgsPtReweight_8TeVUp')
sampleType.append('ggH800_CMS_htt_higgsPtReweight_scale_8TeVDown')
sampleType.append('ggH800_CMS_htt_higgsPtReweight_scale_8TeVUp')
sampleType.append('ggH800_CMS_scale_jDown')
sampleType.append('ggH800_CMS_scale_jUp')
sampleType.append('ggH800_CMS_scale_t_etau_8TeVDown')
sampleType.append('ggH800_CMS_scale_t_etau_8TeVUp')
sampleType.append('ggH800_CMS_scale_t_mutau_8TeVDown')
sampleType.append('ggH800_CMS_scale_t_mutau_8TeVUp')
sampleType.append('ggH80_CMS_eff_t_mssmHigh_etau_8TeVDown')
sampleType.append('ggH80_CMS_eff_t_mssmHigh_etau_8TeVUp')
sampleType.append('ggH80_CMS_eff_t_mssmHigh_mutau_8TeVDown')
sampleType.append('ggH80_CMS_eff_t_mssmHigh_mutau_8TeVUp')
sampleType.append('ggH80_CMS_htt_higgsPtReweight_8TeVDown')
sampleType.append('ggH80_CMS_htt_higgsPtReweight_8TeVUp')
sampleType.append('ggH80_CMS_htt_higgsPtReweight_scale_8TeVDown')
sampleType.append('ggH80_CMS_htt_higgsPtReweight_scale_8TeVUp')
sampleType.append('ggH80_CMS_scale_jDown')
sampleType.append('ggH80_CMS_scale_jUp')
sampleType.append('ggH80_CMS_scale_t_etau_8TeVDown')
sampleType.append('ggH80_CMS_scale_t_etau_8TeVUp')
sampleType.append('ggH80_CMS_scale_t_mutau_8TeVDown')
sampleType.append('ggH80_CMS_scale_t_mutau_8TeVUp')
sampleType.append('ggH90')
sampleType.append('ggH900')
sampleType.append('ggH900_CMS_eff_t_mssmHigh_etau_8TeVDown')
sampleType.append('ggH900_CMS_eff_t_mssmHigh_etau_8TeVUp')
sampleType.append('ggH900_CMS_eff_t_mssmHigh_mutau_8TeVDown')
sampleType.append('ggH900_CMS_eff_t_mssmHigh_mutau_8TeVUp')
sampleType.append('ggH900_CMS_htt_higgsPtReweight_8TeVDown')
sampleType.append('ggH900_CMS_htt_higgsPtReweight_8TeVUp')
sampleType.append('ggH900_CMS_htt_higgsPtReweight_scale_8TeVDown')
sampleType.append('ggH900_CMS_htt_higgsPtReweight_scale_8TeVUp')
sampleType.append('ggH900_CMS_scale_jDown')
sampleType.append('ggH900_CMS_scale_jUp')
sampleType.append('ggH900_CMS_scale_t_etau_8TeVDown')
sampleType.append('ggH900_CMS_scale_t_etau_8TeVUp')
sampleType.append('ggH900_CMS_scale_t_mutau_8TeVDown')
sampleType.append('ggH900_CMS_scale_t_mutau_8TeVUp')
sampleType.append('ggH90_CMS_eff_t_mssmHigh_etau_8TeVDown')
sampleType.append('ggH90_CMS_eff_t_mssmHigh_etau_8TeVUp')
sampleType.append('ggH90_CMS_eff_t_mssmHigh_mutau_8TeVDown')
sampleType.append('ggH90_CMS_eff_t_mssmHigh_mutau_8TeVUp')
sampleType.append('ggH90_CMS_htt_higgsPtReweight_8TeVDown')
sampleType.append('ggH90_CMS_htt_higgsPtReweight_8TeVUp')
sampleType.append('ggH90_CMS_htt_higgsPtReweight_scale_8TeVDown')
sampleType.append('ggH90_CMS_htt_higgsPtReweight_scale_8TeVUp')
sampleType.append('ggH90_CMS_scale_jDown')
sampleType.append('ggH90_CMS_scale_jUp')
sampleType.append('ggH90_CMS_scale_t_etau_8TeVDown')
sampleType.append('ggH90_CMS_scale_t_etau_8TeVUp')
sampleType.append('ggH90_CMS_scale_t_mutau_8TeVDown')
sampleType.append('ggH90_CMS_scale_t_mutau_8TeVUp')
sampleType.append('ggH_SM125')
sampleType.append('ggH_SM125_CMS_eff_t_mssmHigh_etau_8TeVDown')
sampleType.append('ggH_SM125_CMS_eff_t_mssmHigh_etau_8TeVUp')
sampleType.append('ggH_SM125_CMS_eff_t_mssmHigh_mutau_8TeVDown')
sampleType.append('ggH_SM125_CMS_eff_t_mssmHigh_mutau_8TeVUp')
sampleType.append('ggH_SM125_CMS_htt_higgsPtReweightSM_8TeVDown')
sampleType.append('ggH_SM125_CMS_htt_higgsPtReweightSM_8TeVUp')
sampleType.append('ggH_SM125_CMS_scale_jDown')
sampleType.append('ggH_SM125_CMS_scale_jUp')
sampleType.append('ggH_SM125_CMS_scale_t_etau_8TeVDown')
sampleType.append('ggH_SM125_CMS_scale_t_etau_8TeVUp')
sampleType.append('ggH_SM125_CMS_scale_t_mutau_8TeVDown')
sampleType.append('ggH_SM125_CMS_scale_t_mutau_8TeVUp')
sampleType.append('qqH_SM125')
sampleType.append('qqH_SM125_CMS_eff_t_mssmHigh_etau_8TeVDown')
sampleType.append('qqH_SM125_CMS_eff_t_mssmHigh_etau_8TeVUp')
sampleType.append('qqH_SM125_CMS_eff_t_mssmHigh_mutau_8TeVDown')
sampleType.append('qqH_SM125_CMS_eff_t_mssmHigh_mutau_8TeVUp')
sampleType.append('qqH_SM125_CMS_scale_jDown')
sampleType.append('qqH_SM125_CMS_scale_jUp')
sampleType.append('qqH_SM125_CMS_scale_t_etau_8TeVDown')
sampleType.append('qqH_SM125_CMS_scale_t_etau_8TeVUp')
sampleType.append('qqH_SM125_CMS_scale_t_mutau_8TeVDown')
sampleType.append('qqH_SM125_CMS_scale_t_mutau_8TeVUp')

sampleTitle.append('QCD')
sampleTitle.append('QCD_CMS_htt_QCDShape_etau_btag_8TeVDown')
sampleTitle.append('QCD_CMS_htt_QCDShape_etau_btag_8TeVDown_fine_binning')
sampleTitle.append('QCD_CMS_htt_QCDShape_etau_btag_8TeVUp')
sampleTitle.append('QCD_CMS_htt_QCDShape_etau_btag_8TeVUp_fine_binning')
sampleTitle.append('QCD_CMS_htt_QCDShape_etau_btag_high_8TeVDown')
sampleTitle.append('QCD_CMS_htt_QCDShape_etau_btag_high_8TeVDown_fine_binning')
sampleTitle.append('QCD_CMS_htt_QCDShape_etau_btag_high_8TeVUp')
sampleTitle.append('QCD_CMS_htt_QCDShape_etau_btag_high_8TeVUp_fine_binning')
sampleTitle.append('QCD_CMS_htt_QCDShape_etau_btag_low_8TeVDown')
sampleTitle.append('QCD_CMS_htt_QCDShape_etau_btag_low_8TeVDown_fine_binning')
sampleTitle.append('QCD_CMS_htt_QCDShape_etau_btag_low_8TeVUp')
sampleTitle.append('QCD_CMS_htt_QCDShape_etau_btag_low_8TeVUp_fine_binning')
sampleTitle.append('QCD_CMS_htt_QCDShape_etau_nobtag_8TeVDown')
sampleTitle.append('QCD_CMS_htt_QCDShape_etau_nobtag_8TeVDown_fine_binning')
sampleTitle.append('QCD_CMS_htt_QCDShape_etau_nobtag_8TeVUp')
sampleTitle.append('QCD_CMS_htt_QCDShape_etau_nobtag_8TeVUp_fine_binning')
sampleTitle.append('QCD_CMS_htt_QCDShape_etau_nobtag_high_8TeVDown')
sampleTitle.append('QCD_CMS_htt_QCDShape_etau_nobtag_high_8TeVDown_fine_binning')
sampleTitle.append('QCD_CMS_htt_QCDShape_etau_nobtag_high_8TeVUp')
sampleTitle.append('QCD_CMS_htt_QCDShape_etau_nobtag_high_8TeVUp_fine_binning')
sampleTitle.append('QCD_CMS_htt_QCDShape_etau_nobtag_low_8TeVDown')
sampleTitle.append('QCD_CMS_htt_QCDShape_etau_nobtag_low_8TeVDown_fine_binning')
sampleTitle.append('QCD_CMS_htt_QCDShape_etau_nobtag_low_8TeVUp')
sampleTitle.append('QCD_CMS_htt_QCDShape_etau_nobtag_low_8TeVUp_fine_binning')
sampleTitle.append('QCD_CMS_htt_QCDShape_etau_nobtag_medium_8TeVDown')
sampleTitle.append('QCD_CMS_htt_QCDShape_etau_nobtag_medium_8TeVDown_fine_binning')
sampleTitle.append('QCD_CMS_htt_QCDShape_etau_nobtag_medium_8TeVUp')
sampleTitle.append('QCD_CMS_htt_QCDShape_etau_nobtag_medium_8TeVUp_fine_binning')
sampleTitle.append('QCD_CMS_htt_QCDShape_mutau_btag_8TeVDown')
sampleTitle.append('QCD_CMS_htt_QCDShape_mutau_btag_8TeVDown_fine_binning')
sampleTitle.append('QCD_CMS_htt_QCDShape_mutau_btag_8TeVUp')
sampleTitle.append('QCD_CMS_htt_QCDShape_mutau_btag_8TeVUp_fine_binning')
sampleTitle.append('QCD_CMS_htt_QCDShape_mutau_btag_high_8TeVDown')
sampleTitle.append('QCD_CMS_htt_QCDShape_mutau_btag_high_8TeVDown_fine_binning')
sampleTitle.append('QCD_CMS_htt_QCDShape_mutau_btag_high_8TeVUp')
sampleTitle.append('QCD_CMS_htt_QCDShape_mutau_btag_high_8TeVUp_fine_binning')
sampleTitle.append('QCD_CMS_htt_QCDShape_mutau_btag_low_8TeVDown')
sampleTitle.append('QCD_CMS_htt_QCDShape_mutau_btag_low_8TeVDown_fine_binning')
sampleTitle.append('QCD_CMS_htt_QCDShape_mutau_btag_low_8TeVUp')
sampleTitle.append('QCD_CMS_htt_QCDShape_mutau_btag_low_8TeVUp_fine_binning')
sampleTitle.append('QCD_CMS_htt_QCDShape_mutau_nobtag_8TeVDown')
sampleTitle.append('QCD_CMS_htt_QCDShape_mutau_nobtag_8TeVDown_fine_binning')
sampleTitle.append('QCD_CMS_htt_QCDShape_mutau_nobtag_8TeVUp')
sampleTitle.append('QCD_CMS_htt_QCDShape_mutau_nobtag_8TeVUp_fine_binning')
sampleTitle.append('QCD_CMS_htt_QCDShape_mutau_nobtag_high_8TeVDown')
sampleTitle.append('QCD_CMS_htt_QCDShape_mutau_nobtag_high_8TeVDown_fine_binning')
sampleTitle.append('QCD_CMS_htt_QCDShape_mutau_nobtag_high_8TeVUp')
sampleTitle.append('QCD_CMS_htt_QCDShape_mutau_nobtag_high_8TeVUp_fine_binning')
sampleTitle.append('QCD_CMS_htt_QCDShape_mutau_nobtag_low_8TeVDown')
sampleTitle.append('QCD_CMS_htt_QCDShape_mutau_nobtag_low_8TeVDown_fine_binning')
sampleTitle.append('QCD_CMS_htt_QCDShape_mutau_nobtag_low_8TeVUp')
sampleTitle.append('QCD_CMS_htt_QCDShape_mutau_nobtag_low_8TeVUp_fine_binning')
sampleTitle.append('QCD_CMS_htt_QCDShape_mutau_nobtag_medium_8TeVDown')
sampleTitle.append('QCD_CMS_htt_QCDShape_mutau_nobtag_medium_8TeVDown_fine_binning')
sampleTitle.append('QCD_CMS_htt_QCDShape_mutau_nobtag_medium_8TeVUp')
sampleTitle.append('QCD_CMS_htt_QCDShape_mutau_nobtag_medium_8TeVUp_fine_binning')
sampleTitle.append('QCD_CMS_htt_QCDfrShape_etau_8TeVDown')
sampleTitle.append('QCD_CMS_htt_QCDfrShape_etau_8TeVDown_fine_binning')
sampleTitle.append('QCD_CMS_htt_QCDfrShape_etau_8TeVUp')
sampleTitle.append('QCD_CMS_htt_QCDfrShape_etau_8TeVUp_fine_binning')
sampleTitle.append('QCD_CMS_htt_QCDfrShape_mutau_8TeVDown')
sampleTitle.append('QCD_CMS_htt_QCDfrShape_mutau_8TeVDown_fine_binning')
sampleTitle.append('QCD_CMS_htt_QCDfrShape_mutau_8TeVUp')
sampleTitle.append('QCD_CMS_htt_QCDfrShape_mutau_8TeVUp_fine_binning')
sampleTitle.append('QCD_CMS_scale_jDown')
sampleTitle.append('QCD_CMS_scale_jDown_fine_binning')
sampleTitle.append('QCD_CMS_scale_jUp')
sampleTitle.append('QCD_CMS_scale_jUp_fine_binning')
sampleTitle.append('QCD_CMS_scale_t_etau_8TeVDown')
sampleTitle.append('QCD_CMS_scale_t_etau_8TeVDown_fine_binning')
sampleTitle.append('QCD_CMS_scale_t_etau_8TeVUp')
sampleTitle.append('QCD_CMS_scale_t_etau_8TeVUp_fine_binning')
sampleTitle.append('QCD_CMS_scale_t_mutau_8TeVDown')
sampleTitle.append('QCD_CMS_scale_t_mutau_8TeVDown_fine_binning')
sampleTitle.append('QCD_CMS_scale_t_mutau_8TeVUp')
sampleTitle.append('QCD_CMS_scale_t_mutau_8TeVUp_fine_binning')
sampleTitle.append('QCD_fine_binning')
sampleTitle.append('TT')
sampleTitle.append('TT_CMS_htt_ZLScale_etau_8TeVDown')
sampleTitle.append('TT_CMS_htt_ZLScale_etau_8TeVUp')
sampleTitle.append('TT_CMS_htt_ZLScale_mutau_8TeVDown')
sampleTitle.append('TT_CMS_htt_ZLScale_mutau_8TeVUp')
sampleTitle.append('TT_CMS_htt_ttbarPtReweight_8TeVDown')
sampleTitle.append('TT_CMS_htt_ttbarPtReweight_8TeVUp')
sampleTitle.append('TT_CMS_scale_jDown')
sampleTitle.append('TT_CMS_scale_jDown_fine_binning')
sampleTitle.append('TT_CMS_scale_jUp')
sampleTitle.append('TT_CMS_scale_jUp_fine_binning')
sampleTitle.append('TT_CMS_scale_t_etau_8TeVDown')
sampleTitle.append('TT_CMS_scale_t_etau_8TeVDown_fine_binning')
sampleTitle.append('TT_CMS_scale_t_etau_8TeVUp')
sampleTitle.append('TT_CMS_scale_t_etau_8TeVUp_fine_binning')
sampleTitle.append('TT_CMS_scale_t_mutau_8TeVDown')
sampleTitle.append('TT_CMS_scale_t_mutau_8TeVDown_fine_binning')
sampleTitle.append('TT_CMS_scale_t_mutau_8TeVUp')
sampleTitle.append('TT_CMS_scale_t_mutau_8TeVUp_fine_binning')
sampleTitle.append('TT_fine_binning')
sampleTitle.append('VH_SM125')
sampleTitle.append('VH_SM125_CMS_eff_t_mssmHigh_etau_8TeVDown')
sampleTitle.append('VH_SM125_CMS_eff_t_mssmHigh_etau_8TeVUp')
sampleTitle.append('VH_SM125_CMS_eff_t_mssmHigh_mutau_8TeVDown')
sampleTitle.append('VH_SM125_CMS_eff_t_mssmHigh_mutau_8TeVUp')
sampleTitle.append('VH_SM125_CMS_scale_jDown')
sampleTitle.append('VH_SM125_CMS_scale_jUp')
sampleTitle.append('VH_SM125_CMS_scale_t_etau_8TeVDown')
sampleTitle.append('VH_SM125_CMS_scale_t_etau_8TeVUp')
sampleTitle.append('VH_SM125_CMS_scale_t_mutau_8TeVDown')
sampleTitle.append('VH_SM125_CMS_scale_t_mutau_8TeVUp')
sampleTitle.append('VV')
sampleTitle.append('VV_CMS_scale_jDown')
sampleTitle.append('VV_CMS_scale_jDown_fine_binning')
sampleTitle.append('VV_CMS_scale_jUp')
sampleTitle.append('VV_CMS_scale_jUp_fine_binning')
sampleTitle.append('VV_CMS_scale_t_etau_8TeVDown')
sampleTitle.append('VV_CMS_scale_t_etau_8TeVDown_fine_binning')
sampleTitle.append('VV_CMS_scale_t_etau_8TeVUp')
sampleTitle.append('VV_CMS_scale_t_etau_8TeVUp_fine_binning')
sampleTitle.append('VV_CMS_scale_t_mutau_8TeVDown')
sampleTitle.append('VV_CMS_scale_t_mutau_8TeVDown_fine_binning')
sampleTitle.append('VV_CMS_scale_t_mutau_8TeVUp')
sampleTitle.append('VV_CMS_scale_t_mutau_8TeVUp_fine_binning')
sampleTitle.append('VV_fine_binning')
sampleTitle.append('W')
sampleTitle.append('W_CMS_htt_WShape_etau_btag_8TeVDown')
sampleTitle.append('W_CMS_htt_WShape_etau_btag_8TeVDown_fine_binning')
sampleTitle.append('W_CMS_htt_WShape_etau_btag_8TeVUp')
sampleTitle.append('W_CMS_htt_WShape_etau_btag_8TeVUp_fine_binning')
sampleTitle.append('W_CMS_htt_WShape_etau_btag_high_8TeVDown')
sampleTitle.append('W_CMS_htt_WShape_etau_btag_high_8TeVDown_fine_binning')
sampleTitle.append('W_CMS_htt_WShape_etau_btag_high_8TeVUp')
sampleTitle.append('W_CMS_htt_WShape_etau_btag_high_8TeVUp_fine_binning')
sampleTitle.append('W_CMS_htt_WShape_etau_btag_low_8TeVDown')
sampleTitle.append('W_CMS_htt_WShape_etau_btag_low_8TeVDown_fine_binning')
sampleTitle.append('W_CMS_htt_WShape_etau_btag_low_8TeVUp')
sampleTitle.append('W_CMS_htt_WShape_etau_btag_low_8TeVUp_fine_binning')
sampleTitle.append('W_CMS_htt_WShape_etau_nobtag_8TeVDown')
sampleTitle.append('W_CMS_htt_WShape_etau_nobtag_8TeVDown_fine_binning')
sampleTitle.append('W_CMS_htt_WShape_etau_nobtag_8TeVUp')
sampleTitle.append('W_CMS_htt_WShape_etau_nobtag_8TeVUp_fine_binning')
sampleTitle.append('W_CMS_htt_WShape_etau_nobtag_high_8TeVDown')
sampleTitle.append('W_CMS_htt_WShape_etau_nobtag_high_8TeVDown_fine_binning')
sampleTitle.append('W_CMS_htt_WShape_etau_nobtag_high_8TeVUp')
sampleTitle.append('W_CMS_htt_WShape_etau_nobtag_high_8TeVUp_fine_binning')
sampleTitle.append('W_CMS_htt_WShape_etau_nobtag_low_8TeVDown')
sampleTitle.append('W_CMS_htt_WShape_etau_nobtag_low_8TeVDown_fine_binning')
sampleTitle.append('W_CMS_htt_WShape_etau_nobtag_low_8TeVUp')
sampleTitle.append('W_CMS_htt_WShape_etau_nobtag_low_8TeVUp_fine_binning')
sampleTitle.append('W_CMS_htt_WShape_etau_nobtag_medium_8TeVDown')
sampleTitle.append('W_CMS_htt_WShape_etau_nobtag_medium_8TeVDown_fine_binning')
sampleTitle.append('W_CMS_htt_WShape_etau_nobtag_medium_8TeVUp')
sampleTitle.append('W_CMS_htt_WShape_etau_nobtag_medium_8TeVUp_fine_binning')
sampleTitle.append('W_CMS_htt_WShape_mutau_btag_8TeVDown')
sampleTitle.append('W_CMS_htt_WShape_mutau_btag_8TeVDown_fine_binning')
sampleTitle.append('W_CMS_htt_WShape_mutau_btag_8TeVUp')
sampleTitle.append('W_CMS_htt_WShape_mutau_btag_8TeVUp_fine_binning')
sampleTitle.append('W_CMS_htt_WShape_mutau_btag_high_8TeVDown')
sampleTitle.append('W_CMS_htt_WShape_mutau_btag_high_8TeVDown_fine_binning')
sampleTitle.append('W_CMS_htt_WShape_mutau_btag_high_8TeVUp')
sampleTitle.append('W_CMS_htt_WShape_mutau_btag_high_8TeVUp_fine_binning')
sampleTitle.append('W_CMS_htt_WShape_mutau_btag_low_8TeVDown')
sampleTitle.append('W_CMS_htt_WShape_mutau_btag_low_8TeVDown_fine_binning')
sampleTitle.append('W_CMS_htt_WShape_mutau_btag_low_8TeVUp')
sampleTitle.append('W_CMS_htt_WShape_mutau_btag_low_8TeVUp_fine_binning')
sampleTitle.append('W_CMS_htt_WShape_mutau_nobtag_8TeVDown')
sampleTitle.append('W_CMS_htt_WShape_mutau_nobtag_8TeVDown_fine_binning')
sampleTitle.append('W_CMS_htt_WShape_mutau_nobtag_8TeVUp')
sampleTitle.append('W_CMS_htt_WShape_mutau_nobtag_8TeVUp_fine_binning')
sampleTitle.append('W_CMS_htt_WShape_mutau_nobtag_high_8TeVDown')
sampleTitle.append('W_CMS_htt_WShape_mutau_nobtag_high_8TeVDown_fine_binning')
sampleTitle.append('W_CMS_htt_WShape_mutau_nobtag_high_8TeVUp')
sampleTitle.append('W_CMS_htt_WShape_mutau_nobtag_high_8TeVUp_fine_binning')
sampleTitle.append('W_CMS_htt_WShape_mutau_nobtag_low_8TeVDown')
sampleTitle.append('W_CMS_htt_WShape_mutau_nobtag_low_8TeVDown_fine_binning')
sampleTitle.append('W_CMS_htt_WShape_mutau_nobtag_low_8TeVUp')
sampleTitle.append('W_CMS_htt_WShape_mutau_nobtag_low_8TeVUp_fine_binning')
sampleTitle.append('W_CMS_htt_WShape_mutau_nobtag_medium_8TeVDown')
sampleTitle.append('W_CMS_htt_WShape_mutau_nobtag_medium_8TeVDown_fine_binning')
sampleTitle.append('W_CMS_htt_WShape_mutau_nobtag_medium_8TeVUp')
sampleTitle.append('W_CMS_htt_WShape_mutau_nobtag_medium_8TeVUp_fine_binning')
sampleTitle.append('W_CMS_scale_jDown')
sampleTitle.append('W_CMS_scale_jDown_fine_binning')
sampleTitle.append('W_CMS_scale_jUp')
sampleTitle.append('W_CMS_scale_jUp_fine_binning')
sampleTitle.append('W_CMS_scale_t_etau_8TeVDown')
sampleTitle.append('W_CMS_scale_t_etau_8TeVDown_fine_binning')
sampleTitle.append('W_CMS_scale_t_etau_8TeVUp')
sampleTitle.append('W_CMS_scale_t_etau_8TeVUp_fine_binning')
sampleTitle.append('W_CMS_scale_t_mutau_8TeVDown')
sampleTitle.append('W_CMS_scale_t_mutau_8TeVDown_fine_binning')
sampleTitle.append('W_CMS_scale_t_mutau_8TeVUp')
sampleTitle.append('W_CMS_scale_t_mutau_8TeVUp_fine_binning')
sampleTitle.append('W_fine_binning')
sampleTitle.append('ZJ')
sampleTitle.append('ZJ_CMS_scale_jDown')
sampleTitle.append('ZJ_CMS_scale_jDown_fine_binning')
sampleTitle.append('ZJ_CMS_scale_jUp')
sampleTitle.append('ZJ_CMS_scale_jUp_fine_binning')
sampleTitle.append('ZJ_CMS_scale_t_etau_8TeVDown')
sampleTitle.append('ZJ_CMS_scale_t_etau_8TeVDown_fine_binning')
sampleTitle.append('ZJ_CMS_scale_t_etau_8TeVUp')
sampleTitle.append('ZJ_CMS_scale_t_etau_8TeVUp_fine_binning')
sampleTitle.append('ZJ_CMS_scale_t_mutau_8TeVDown')
sampleTitle.append('ZJ_CMS_scale_t_mutau_8TeVDown_fine_binning')
sampleTitle.append('ZJ_CMS_scale_t_mutau_8TeVUp')
sampleTitle.append('ZJ_CMS_scale_t_mutau_8TeVUp_fine_binning')
sampleTitle.append('ZJ_fine_binning')
sampleTitle.append('ZL')
sampleTitle.append('ZLL')
sampleTitle.append('ZLL_CMS_scale_jDown')
sampleTitle.append('ZLL_CMS_scale_jDown_fine_binning')
sampleTitle.append('ZLL_CMS_scale_jUp')
sampleTitle.append('ZLL_CMS_scale_jUp_fine_binning')
sampleTitle.append('ZLL_CMS_scale_t_etau_8TeVDown')
sampleTitle.append('ZLL_CMS_scale_t_etau_8TeVDown_fine_binning')
sampleTitle.append('ZLL_CMS_scale_t_etau_8TeVUp')
sampleTitle.append('ZLL_CMS_scale_t_etau_8TeVUp_fine_binning')
sampleTitle.append('ZLL_CMS_scale_t_mutau_8TeVDown')
sampleTitle.append('ZLL_CMS_scale_t_mutau_8TeVDown_fine_binning')
sampleTitle.append('ZLL_CMS_scale_t_mutau_8TeVUp')
sampleTitle.append('ZLL_CMS_scale_t_mutau_8TeVUp_fine_binning')
sampleTitle.append('ZLL_fine_binning')
sampleTitle.append('ZL_CMS_htt_ZLScale_etau_8TeVDown')
sampleTitle.append('ZL_CMS_htt_ZLScale_etau_8TeVUp')
sampleTitle.append('ZL_CMS_htt_ZLScale_mutau_8TeVDown')
sampleTitle.append('ZL_CMS_htt_ZLScale_mutau_8TeVUp')
sampleTitle.append('ZL_CMS_scale_jDown')
sampleTitle.append('ZL_CMS_scale_jDown_fine_binning')
sampleTitle.append('ZL_CMS_scale_jUp')
sampleTitle.append('ZL_CMS_scale_jUp_fine_binning')
sampleTitle.append('ZL_CMS_scale_t_etau_8TeVDown')
sampleTitle.append('ZL_CMS_scale_t_etau_8TeVDown_fine_binning')
sampleTitle.append('ZL_CMS_scale_t_etau_8TeVUp')
sampleTitle.append('ZL_CMS_scale_t_etau_8TeVUp_fine_binning')
sampleTitle.append('ZL_CMS_scale_t_mutau_8TeVDown')
sampleTitle.append('ZL_CMS_scale_t_mutau_8TeVDown_fine_binning')
sampleTitle.append('ZL_CMS_scale_t_mutau_8TeVUp')
sampleTitle.append('ZL_CMS_scale_t_mutau_8TeVUp_fine_binning')
sampleTitle.append('ZL_fine_binning')
sampleTitle.append('ZTT')
sampleTitle.append('ZTT_CMS_scale_jDown')
sampleTitle.append('ZTT_CMS_scale_jDown_fine_binning')
sampleTitle.append('ZTT_CMS_scale_jUp')
sampleTitle.append('ZTT_CMS_scale_jUp_fine_binning')
sampleTitle.append('ZTT_CMS_scale_t_etau_8TeVDown')
sampleTitle.append('ZTT_CMS_scale_t_etau_8TeVDown_fine_binning')
sampleTitle.append('ZTT_CMS_scale_t_etau_8TeVUp')
sampleTitle.append('ZTT_CMS_scale_t_etau_8TeVUp_fine_binning')
sampleTitle.append('ZTT_CMS_scale_t_mutau_8TeVDown')
sampleTitle.append('ZTT_CMS_scale_t_mutau_8TeVDown_fine_binning')
sampleTitle.append('ZTT_CMS_scale_t_mutau_8TeVUp')
sampleTitle.append('ZTT_CMS_scale_t_mutau_8TeVUp_fine_binning')
sampleTitle.append('ZTT_fine_binning')
sampleTitle.append('bbH100')
sampleTitle.append('bbH1000')
sampleTitle.append('bbH1000_CMS_eff_t_mssmHigh_etau_8TeVDown')
sampleTitle.append('bbH1000_CMS_eff_t_mssmHigh_etau_8TeVUp')
sampleTitle.append('bbH1000_CMS_eff_t_mssmHigh_mutau_8TeVDown')
sampleTitle.append('bbH1000_CMS_eff_t_mssmHigh_mutau_8TeVUp')
sampleTitle.append('bbH1000_CMS_scale_jDown')
sampleTitle.append('bbH1000_CMS_scale_jUp')
sampleTitle.append('bbH1000_CMS_scale_t_etau_8TeVDown')
sampleTitle.append('bbH1000_CMS_scale_t_etau_8TeVUp')
sampleTitle.append('bbH1000_CMS_scale_t_mutau_8TeVDown')
sampleTitle.append('bbH1000_CMS_scale_t_mutau_8TeVUp')
sampleTitle.append('bbH100_CMS_eff_t_mssmHigh_etau_8TeVDown')
sampleTitle.append('bbH100_CMS_eff_t_mssmHigh_etau_8TeVUp')
sampleTitle.append('bbH100_CMS_eff_t_mssmHigh_mutau_8TeVDown')
sampleTitle.append('bbH100_CMS_eff_t_mssmHigh_mutau_8TeVUp')
sampleTitle.append('bbH100_CMS_scale_jDown')
sampleTitle.append('bbH100_CMS_scale_jUp')
sampleTitle.append('bbH100_CMS_scale_t_etau_8TeVDown')
sampleTitle.append('bbH100_CMS_scale_t_etau_8TeVUp')
sampleTitle.append('bbH100_CMS_scale_t_mutau_8TeVDown')
sampleTitle.append('bbH100_CMS_scale_t_mutau_8TeVUp')
sampleTitle.append('bbH110')
sampleTitle.append('bbH110_CMS_eff_t_mssmHigh_etau_8TeVDown')
sampleTitle.append('bbH110_CMS_eff_t_mssmHigh_etau_8TeVUp')
sampleTitle.append('bbH110_CMS_eff_t_mssmHigh_mutau_8TeVDown')
sampleTitle.append('bbH110_CMS_eff_t_mssmHigh_mutau_8TeVUp')
sampleTitle.append('bbH110_CMS_scale_jDown')
sampleTitle.append('bbH110_CMS_scale_jUp')
sampleTitle.append('bbH110_CMS_scale_t_etau_8TeVDown')
sampleTitle.append('bbH110_CMS_scale_t_etau_8TeVUp')
sampleTitle.append('bbH110_CMS_scale_t_mutau_8TeVDown')
sampleTitle.append('bbH110_CMS_scale_t_mutau_8TeVUp')
sampleTitle.append('bbH120')
sampleTitle.append('bbH120_CMS_eff_t_mssmHigh_etau_8TeVDown')
sampleTitle.append('bbH120_CMS_eff_t_mssmHigh_etau_8TeVUp')
sampleTitle.append('bbH120_CMS_eff_t_mssmHigh_mutau_8TeVDown')
sampleTitle.append('bbH120_CMS_eff_t_mssmHigh_mutau_8TeVUp')
sampleTitle.append('bbH120_CMS_scale_jDown')
sampleTitle.append('bbH120_CMS_scale_jUp')
sampleTitle.append('bbH120_CMS_scale_t_etau_8TeVDown')
sampleTitle.append('bbH120_CMS_scale_t_etau_8TeVUp')
sampleTitle.append('bbH120_CMS_scale_t_mutau_8TeVDown')
sampleTitle.append('bbH120_CMS_scale_t_mutau_8TeVUp')
sampleTitle.append('bbH130')
sampleTitle.append('bbH130_CMS_eff_t_mssmHigh_etau_8TeVDown')
sampleTitle.append('bbH130_CMS_eff_t_mssmHigh_etau_8TeVUp')
sampleTitle.append('bbH130_CMS_eff_t_mssmHigh_mutau_8TeVDown')
sampleTitle.append('bbH130_CMS_eff_t_mssmHigh_mutau_8TeVUp')
sampleTitle.append('bbH130_CMS_scale_jDown')
sampleTitle.append('bbH130_CMS_scale_jUp')
sampleTitle.append('bbH130_CMS_scale_t_etau_8TeVDown')
sampleTitle.append('bbH130_CMS_scale_t_etau_8TeVUp')
sampleTitle.append('bbH130_CMS_scale_t_mutau_8TeVDown')
sampleTitle.append('bbH130_CMS_scale_t_mutau_8TeVUp')
sampleTitle.append('bbH140')
sampleTitle.append('bbH140_CMS_eff_t_mssmHigh_etau_8TeVDown')
sampleTitle.append('bbH140_CMS_eff_t_mssmHigh_etau_8TeVUp')
sampleTitle.append('bbH140_CMS_eff_t_mssmHigh_mutau_8TeVDown')
sampleTitle.append('bbH140_CMS_eff_t_mssmHigh_mutau_8TeVUp')
sampleTitle.append('bbH140_CMS_scale_jDown')
sampleTitle.append('bbH140_CMS_scale_jUp')
sampleTitle.append('bbH140_CMS_scale_t_etau_8TeVDown')
sampleTitle.append('bbH140_CMS_scale_t_etau_8TeVUp')
sampleTitle.append('bbH140_CMS_scale_t_mutau_8TeVDown')
sampleTitle.append('bbH140_CMS_scale_t_mutau_8TeVUp')
sampleTitle.append('bbH160')
sampleTitle.append('bbH160_CMS_eff_t_mssmHigh_etau_8TeVDown')
sampleTitle.append('bbH160_CMS_eff_t_mssmHigh_etau_8TeVUp')
sampleTitle.append('bbH160_CMS_eff_t_mssmHigh_mutau_8TeVDown')
sampleTitle.append('bbH160_CMS_eff_t_mssmHigh_mutau_8TeVUp')
sampleTitle.append('bbH160_CMS_scale_jDown')
sampleTitle.append('bbH160_CMS_scale_jUp')
sampleTitle.append('bbH160_CMS_scale_t_etau_8TeVDown')
sampleTitle.append('bbH160_CMS_scale_t_etau_8TeVUp')
sampleTitle.append('bbH160_CMS_scale_t_mutau_8TeVDown')
sampleTitle.append('bbH160_CMS_scale_t_mutau_8TeVUp')
sampleTitle.append('bbH180')
sampleTitle.append('bbH180_CMS_eff_t_mssmHigh_etau_8TeVDown')
sampleTitle.append('bbH180_CMS_eff_t_mssmHigh_etau_8TeVUp')
sampleTitle.append('bbH180_CMS_eff_t_mssmHigh_mutau_8TeVDown')
sampleTitle.append('bbH180_CMS_eff_t_mssmHigh_mutau_8TeVUp')
sampleTitle.append('bbH180_CMS_scale_jDown')
sampleTitle.append('bbH180_CMS_scale_jUp')
sampleTitle.append('bbH180_CMS_scale_t_etau_8TeVDown')
sampleTitle.append('bbH180_CMS_scale_t_etau_8TeVUp')
sampleTitle.append('bbH180_CMS_scale_t_mutau_8TeVDown')
sampleTitle.append('bbH180_CMS_scale_t_mutau_8TeVUp')
sampleTitle.append('bbH200')
sampleTitle.append('bbH200_CMS_eff_t_mssmHigh_etau_8TeVDown')
sampleTitle.append('bbH200_CMS_eff_t_mssmHigh_etau_8TeVUp')
sampleTitle.append('bbH200_CMS_eff_t_mssmHigh_mutau_8TeVDown')
sampleTitle.append('bbH200_CMS_eff_t_mssmHigh_mutau_8TeVUp')
sampleTitle.append('bbH200_CMS_scale_jDown')
sampleTitle.append('bbH200_CMS_scale_jUp')
sampleTitle.append('bbH200_CMS_scale_t_etau_8TeVDown')
sampleTitle.append('bbH200_CMS_scale_t_etau_8TeVUp')
sampleTitle.append('bbH200_CMS_scale_t_mutau_8TeVDown')
sampleTitle.append('bbH200_CMS_scale_t_mutau_8TeVUp')
sampleTitle.append('bbH250')
sampleTitle.append('bbH250_CMS_eff_t_mssmHigh_etau_8TeVDown')
sampleTitle.append('bbH250_CMS_eff_t_mssmHigh_etau_8TeVUp')
sampleTitle.append('bbH250_CMS_eff_t_mssmHigh_mutau_8TeVDown')
sampleTitle.append('bbH250_CMS_eff_t_mssmHigh_mutau_8TeVUp')
sampleTitle.append('bbH250_CMS_scale_jDown')
sampleTitle.append('bbH250_CMS_scale_jUp')
sampleTitle.append('bbH250_CMS_scale_t_etau_8TeVDown')
sampleTitle.append('bbH250_CMS_scale_t_etau_8TeVUp')
sampleTitle.append('bbH250_CMS_scale_t_mutau_8TeVDown')
sampleTitle.append('bbH250_CMS_scale_t_mutau_8TeVUp')
sampleTitle.append('bbH300')
sampleTitle.append('bbH300_CMS_eff_t_mssmHigh_etau_8TeVDown')
sampleTitle.append('bbH300_CMS_eff_t_mssmHigh_etau_8TeVUp')
sampleTitle.append('bbH300_CMS_eff_t_mssmHigh_mutau_8TeVDown')
sampleTitle.append('bbH300_CMS_eff_t_mssmHigh_mutau_8TeVUp')
sampleTitle.append('bbH300_CMS_scale_jDown')
sampleTitle.append('bbH300_CMS_scale_jUp')
sampleTitle.append('bbH300_CMS_scale_t_etau_8TeVDown')
sampleTitle.append('bbH300_CMS_scale_t_etau_8TeVUp')
sampleTitle.append('bbH300_CMS_scale_t_mutau_8TeVDown')
sampleTitle.append('bbH300_CMS_scale_t_mutau_8TeVUp')
sampleTitle.append('bbH350')
sampleTitle.append('bbH350_CMS_eff_t_mssmHigh_etau_8TeVDown')
sampleTitle.append('bbH350_CMS_eff_t_mssmHigh_etau_8TeVUp')
sampleTitle.append('bbH350_CMS_eff_t_mssmHigh_mutau_8TeVDown')
sampleTitle.append('bbH350_CMS_eff_t_mssmHigh_mutau_8TeVUp')
sampleTitle.append('bbH350_CMS_scale_jDown')
sampleTitle.append('bbH350_CMS_scale_jUp')
sampleTitle.append('bbH350_CMS_scale_t_etau_8TeVDown')
sampleTitle.append('bbH350_CMS_scale_t_etau_8TeVUp')
sampleTitle.append('bbH350_CMS_scale_t_mutau_8TeVDown')
sampleTitle.append('bbH350_CMS_scale_t_mutau_8TeVUp')
sampleTitle.append('bbH400')
sampleTitle.append('bbH400_CMS_eff_t_mssmHigh_etau_8TeVDown')
sampleTitle.append('bbH400_CMS_eff_t_mssmHigh_etau_8TeVUp')
sampleTitle.append('bbH400_CMS_eff_t_mssmHigh_mutau_8TeVDown')
sampleTitle.append('bbH400_CMS_eff_t_mssmHigh_mutau_8TeVUp')
sampleTitle.append('bbH400_CMS_scale_jDown')
sampleTitle.append('bbH400_CMS_scale_jUp')
sampleTitle.append('bbH400_CMS_scale_t_etau_8TeVDown')
sampleTitle.append('bbH400_CMS_scale_t_etau_8TeVUp')
sampleTitle.append('bbH400_CMS_scale_t_mutau_8TeVDown')
sampleTitle.append('bbH400_CMS_scale_t_mutau_8TeVUp')
sampleTitle.append('bbH450')
sampleTitle.append('bbH450_CMS_eff_t_mssmHigh_etau_8TeVDown')
sampleTitle.append('bbH450_CMS_eff_t_mssmHigh_etau_8TeVUp')
sampleTitle.append('bbH450_CMS_eff_t_mssmHigh_mutau_8TeVDown')
sampleTitle.append('bbH450_CMS_eff_t_mssmHigh_mutau_8TeVUp')
sampleTitle.append('bbH450_CMS_scale_jDown')
sampleTitle.append('bbH450_CMS_scale_jUp')
sampleTitle.append('bbH450_CMS_scale_t_etau_8TeVDown')
sampleTitle.append('bbH450_CMS_scale_t_etau_8TeVUp')
sampleTitle.append('bbH450_CMS_scale_t_mutau_8TeVDown')
sampleTitle.append('bbH450_CMS_scale_t_mutau_8TeVUp')
sampleTitle.append('bbH500')
sampleTitle.append('bbH500_CMS_eff_t_mssmHigh_etau_8TeVDown')
sampleTitle.append('bbH500_CMS_eff_t_mssmHigh_etau_8TeVUp')
sampleTitle.append('bbH500_CMS_eff_t_mssmHigh_mutau_8TeVDown')
sampleTitle.append('bbH500_CMS_eff_t_mssmHigh_mutau_8TeVUp')
sampleTitle.append('bbH500_CMS_scale_jDown')
sampleTitle.append('bbH500_CMS_scale_jUp')
sampleTitle.append('bbH500_CMS_scale_t_etau_8TeVDown')
sampleTitle.append('bbH500_CMS_scale_t_etau_8TeVUp')
sampleTitle.append('bbH500_CMS_scale_t_mutau_8TeVDown')
sampleTitle.append('bbH500_CMS_scale_t_mutau_8TeVUp')
sampleTitle.append('bbH600')
sampleTitle.append('bbH600_CMS_eff_t_mssmHigh_etau_8TeVDown')
sampleTitle.append('bbH600_CMS_eff_t_mssmHigh_etau_8TeVUp')
sampleTitle.append('bbH600_CMS_eff_t_mssmHigh_mutau_8TeVDown')
sampleTitle.append('bbH600_CMS_eff_t_mssmHigh_mutau_8TeVUp')
sampleTitle.append('bbH600_CMS_scale_jDown')
sampleTitle.append('bbH600_CMS_scale_jUp')
sampleTitle.append('bbH600_CMS_scale_t_etau_8TeVDown')
sampleTitle.append('bbH600_CMS_scale_t_etau_8TeVUp')
sampleTitle.append('bbH600_CMS_scale_t_mutau_8TeVDown')
sampleTitle.append('bbH600_CMS_scale_t_mutau_8TeVUp')
sampleTitle.append('bbH700')
sampleTitle.append('bbH700_CMS_eff_t_mssmHigh_etau_8TeVDown')
sampleTitle.append('bbH700_CMS_eff_t_mssmHigh_etau_8TeVUp')
sampleTitle.append('bbH700_CMS_eff_t_mssmHigh_mutau_8TeVDown')
sampleTitle.append('bbH700_CMS_eff_t_mssmHigh_mutau_8TeVUp')
sampleTitle.append('bbH700_CMS_scale_jDown')
sampleTitle.append('bbH700_CMS_scale_jUp')
sampleTitle.append('bbH700_CMS_scale_t_etau_8TeVDown')
sampleTitle.append('bbH700_CMS_scale_t_etau_8TeVUp')
sampleTitle.append('bbH700_CMS_scale_t_mutau_8TeVDown')
sampleTitle.append('bbH700_CMS_scale_t_mutau_8TeVUp')
sampleTitle.append('bbH80')
sampleTitle.append('bbH800')
sampleTitle.append('bbH800_CMS_eff_t_mssmHigh_etau_8TeVDown')
sampleTitle.append('bbH800_CMS_eff_t_mssmHigh_etau_8TeVUp')
sampleTitle.append('bbH800_CMS_eff_t_mssmHigh_mutau_8TeVDown')
sampleTitle.append('bbH800_CMS_eff_t_mssmHigh_mutau_8TeVUp')
sampleTitle.append('bbH800_CMS_scale_jDown')
sampleTitle.append('bbH800_CMS_scale_jUp')
sampleTitle.append('bbH800_CMS_scale_t_etau_8TeVDown')
sampleTitle.append('bbH800_CMS_scale_t_etau_8TeVUp')
sampleTitle.append('bbH800_CMS_scale_t_mutau_8TeVDown')
sampleTitle.append('bbH800_CMS_scale_t_mutau_8TeVUp')
sampleTitle.append('bbH80_CMS_eff_t_mssmHigh_etau_8TeVDown')
sampleTitle.append('bbH80_CMS_eff_t_mssmHigh_etau_8TeVUp')
sampleTitle.append('bbH80_CMS_eff_t_mssmHigh_mutau_8TeVDown')
sampleTitle.append('bbH80_CMS_eff_t_mssmHigh_mutau_8TeVUp')
sampleTitle.append('bbH80_CMS_htt_higgsPtReweight_8TeVDown')
sampleTitle.append('bbH80_CMS_htt_higgsPtReweight_8TeVUp')
sampleTitle.append('bbH80_CMS_scale_jDown')
sampleTitle.append('bbH80_CMS_scale_jUp')
sampleTitle.append('bbH80_CMS_scale_t_etau_8TeVDown')
sampleTitle.append('bbH80_CMS_scale_t_etau_8TeVUp')
sampleTitle.append('bbH80_CMS_scale_t_mutau_8TeVDown')
sampleTitle.append('bbH80_CMS_scale_t_mutau_8TeVUp')
sampleTitle.append('bbH90')
sampleTitle.append('bbH900')
sampleTitle.append('bbH900_CMS_eff_t_mssmHigh_etau_8TeVDown')
sampleTitle.append('bbH900_CMS_eff_t_mssmHigh_etau_8TeVUp')
sampleTitle.append('bbH900_CMS_eff_t_mssmHigh_mutau_8TeVDown')
sampleTitle.append('bbH900_CMS_eff_t_mssmHigh_mutau_8TeVUp')
sampleTitle.append('bbH900_CMS_scale_jDown')
sampleTitle.append('bbH900_CMS_scale_jUp')
sampleTitle.append('bbH900_CMS_scale_t_etau_8TeVDown')
sampleTitle.append('bbH900_CMS_scale_t_etau_8TeVUp')
sampleTitle.append('bbH900_CMS_scale_t_mutau_8TeVDown')
sampleTitle.append('bbH900_CMS_scale_t_mutau_8TeVUp')
sampleTitle.append('bbH90_CMS_eff_t_mssmHigh_etau_8TeVDown')
sampleTitle.append('bbH90_CMS_eff_t_mssmHigh_etau_8TeVUp')
sampleTitle.append('bbH90_CMS_eff_t_mssmHigh_mutau_8TeVDown')
sampleTitle.append('bbH90_CMS_eff_t_mssmHigh_mutau_8TeVUp')
sampleTitle.append('bbH90_CMS_scale_jDown')
sampleTitle.append('bbH90_CMS_scale_jUp')
sampleTitle.append('bbH90_CMS_scale_t_etau_8TeVDown')
sampleTitle.append('bbH90_CMS_scale_t_etau_8TeVUp')
sampleTitle.append('bbH90_CMS_scale_t_mutau_8TeVDown')
sampleTitle.append('bbH90_CMS_scale_t_mutau_8TeVUp')
sampleTitle.append('data_obs')
sampleTitle.append('ggH100')
sampleTitle.append('ggH1000')
sampleTitle.append('ggH1000_CMS_eff_t_mssmHigh_etau_8TeVDown')
sampleTitle.append('ggH1000_CMS_eff_t_mssmHigh_etau_8TeVUp')
sampleTitle.append('ggH1000_CMS_eff_t_mssmHigh_mutau_8TeVDown')
sampleTitle.append('ggH1000_CMS_eff_t_mssmHigh_mutau_8TeVUp')
sampleTitle.append('ggH1000_CMS_htt_higgsPtReweight_8TeVDown')
sampleTitle.append('ggH1000_CMS_htt_higgsPtReweight_8TeVUp')
sampleTitle.append('ggH1000_CMS_htt_higgsPtReweight_scale_8TeVDown')
sampleTitle.append('ggH1000_CMS_htt_higgsPtReweight_scale_8TeVUp')
sampleTitle.append('ggH1000_CMS_scale_jDown')
sampleTitle.append('ggH1000_CMS_scale_jUp')
sampleTitle.append('ggH1000_CMS_scale_t_etau_8TeVDown')
sampleTitle.append('ggH1000_CMS_scale_t_etau_8TeVUp')
sampleTitle.append('ggH1000_CMS_scale_t_mutau_8TeVDown')
sampleTitle.append('ggH1000_CMS_scale_t_mutau_8TeVUp')
sampleTitle.append('ggH100_CMS_eff_t_mssmHigh_etau_8TeVDown')
sampleTitle.append('ggH100_CMS_eff_t_mssmHigh_etau_8TeVUp')
sampleTitle.append('ggH100_CMS_eff_t_mssmHigh_mutau_8TeVDown')
sampleTitle.append('ggH100_CMS_eff_t_mssmHigh_mutau_8TeVUp')
sampleTitle.append('ggH100_CMS_htt_higgsPtReweight_8TeVDown')
sampleTitle.append('ggH100_CMS_htt_higgsPtReweight_8TeVUp')
sampleTitle.append('ggH100_CMS_htt_higgsPtReweight_scale_8TeVDown')
sampleTitle.append('ggH100_CMS_htt_higgsPtReweight_scale_8TeVUp')
sampleTitle.append('ggH100_CMS_scale_jDown')
sampleTitle.append('ggH100_CMS_scale_jUp')
sampleTitle.append('ggH100_CMS_scale_t_etau_8TeVDown')
sampleTitle.append('ggH100_CMS_scale_t_etau_8TeVUp')
sampleTitle.append('ggH100_CMS_scale_t_mutau_8TeVDown')
sampleTitle.append('ggH100_CMS_scale_t_mutau_8TeVUp')
sampleTitle.append('ggH110')
sampleTitle.append('ggH110_CMS_eff_t_mssmHigh_etau_8TeVDown')
sampleTitle.append('ggH110_CMS_eff_t_mssmHigh_etau_8TeVUp')
sampleTitle.append('ggH110_CMS_eff_t_mssmHigh_mutau_8TeVDown')
sampleTitle.append('ggH110_CMS_eff_t_mssmHigh_mutau_8TeVUp')
sampleTitle.append('ggH110_CMS_htt_higgsPtReweight_8TeVDown')
sampleTitle.append('ggH110_CMS_htt_higgsPtReweight_8TeVUp')
sampleTitle.append('ggH110_CMS_htt_higgsPtReweight_scale_8TeVDown')
sampleTitle.append('ggH110_CMS_htt_higgsPtReweight_scale_8TeVUp')
sampleTitle.append('ggH110_CMS_scale_jDown')
sampleTitle.append('ggH110_CMS_scale_jUp')
sampleTitle.append('ggH110_CMS_scale_t_etau_8TeVDown')
sampleTitle.append('ggH110_CMS_scale_t_etau_8TeVUp')
sampleTitle.append('ggH110_CMS_scale_t_mutau_8TeVDown')
sampleTitle.append('ggH110_CMS_scale_t_mutau_8TeVUp')
sampleTitle.append('ggH120')
sampleTitle.append('ggH120_CMS_eff_t_mssmHigh_etau_8TeVDown')
sampleTitle.append('ggH120_CMS_eff_t_mssmHigh_etau_8TeVUp')
sampleTitle.append('ggH120_CMS_eff_t_mssmHigh_mutau_8TeVDown')
sampleTitle.append('ggH120_CMS_eff_t_mssmHigh_mutau_8TeVUp')
sampleTitle.append('ggH120_CMS_htt_higgsPtReweight_8TeVDown')
sampleTitle.append('ggH120_CMS_htt_higgsPtReweight_8TeVUp')
sampleTitle.append('ggH120_CMS_htt_higgsPtReweight_scale_8TeVDown')
sampleTitle.append('ggH120_CMS_htt_higgsPtReweight_scale_8TeVUp')
sampleTitle.append('ggH120_CMS_scale_jDown')
sampleTitle.append('ggH120_CMS_scale_jUp')
sampleTitle.append('ggH120_CMS_scale_t_etau_8TeVDown')
sampleTitle.append('ggH120_CMS_scale_t_etau_8TeVUp')
sampleTitle.append('ggH120_CMS_scale_t_mutau_8TeVDown')
sampleTitle.append('ggH120_CMS_scale_t_mutau_8TeVUp')
sampleTitle.append('ggH130')
sampleTitle.append('ggH130_CMS_eff_t_mssmHigh_etau_8TeVDown')
sampleTitle.append('ggH130_CMS_eff_t_mssmHigh_etau_8TeVUp')
sampleTitle.append('ggH130_CMS_eff_t_mssmHigh_mutau_8TeVDown')
sampleTitle.append('ggH130_CMS_eff_t_mssmHigh_mutau_8TeVUp')
sampleTitle.append('ggH130_CMS_htt_higgsPtReweight_8TeVDown')
sampleTitle.append('ggH130_CMS_htt_higgsPtReweight_8TeVUp')
sampleTitle.append('ggH130_CMS_htt_higgsPtReweight_scale_8TeVDown')
sampleTitle.append('ggH130_CMS_htt_higgsPtReweight_scale_8TeVUp')
sampleTitle.append('ggH130_CMS_scale_jDown')
sampleTitle.append('ggH130_CMS_scale_jUp')
sampleTitle.append('ggH130_CMS_scale_t_etau_8TeVDown')
sampleTitle.append('ggH130_CMS_scale_t_etau_8TeVUp')
sampleTitle.append('ggH130_CMS_scale_t_mutau_8TeVDown')
sampleTitle.append('ggH130_CMS_scale_t_mutau_8TeVUp')
sampleTitle.append('ggH140')
sampleTitle.append('ggH140_CMS_eff_t_mssmHigh_etau_8TeVDown')
sampleTitle.append('ggH140_CMS_eff_t_mssmHigh_etau_8TeVUp')
sampleTitle.append('ggH140_CMS_eff_t_mssmHigh_mutau_8TeVDown')
sampleTitle.append('ggH140_CMS_eff_t_mssmHigh_mutau_8TeVUp')
sampleTitle.append('ggH140_CMS_htt_higgsPtReweight_8TeVDown')
sampleTitle.append('ggH140_CMS_htt_higgsPtReweight_8TeVUp')
sampleTitle.append('ggH140_CMS_htt_higgsPtReweight_scale_8TeVDown')
sampleTitle.append('ggH140_CMS_htt_higgsPtReweight_scale_8TeVUp')
sampleTitle.append('ggH140_CMS_scale_jDown')
sampleTitle.append('ggH140_CMS_scale_jUp')
sampleTitle.append('ggH140_CMS_scale_t_etau_8TeVDown')
sampleTitle.append('ggH140_CMS_scale_t_etau_8TeVUp')
sampleTitle.append('ggH140_CMS_scale_t_mutau_8TeVDown')
sampleTitle.append('ggH140_CMS_scale_t_mutau_8TeVUp')
sampleTitle.append('ggH160')
sampleTitle.append('ggH160_CMS_eff_t_mssmHigh_etau_8TeVDown')
sampleTitle.append('ggH160_CMS_eff_t_mssmHigh_etau_8TeVUp')
sampleTitle.append('ggH160_CMS_eff_t_mssmHigh_mutau_8TeVDown')
sampleTitle.append('ggH160_CMS_eff_t_mssmHigh_mutau_8TeVUp')
sampleTitle.append('ggH160_CMS_htt_higgsPtReweight_8TeVDown')
sampleTitle.append('ggH160_CMS_htt_higgsPtReweight_8TeVUp')
sampleTitle.append('ggH160_CMS_htt_higgsPtReweight_scale_8TeVDown')
sampleTitle.append('ggH160_CMS_htt_higgsPtReweight_scale_8TeVUp')
sampleTitle.append('ggH160_CMS_scale_jDown')
sampleTitle.append('ggH160_CMS_scale_jUp')
sampleTitle.append('ggH160_CMS_scale_t_etau_8TeVDown')
sampleTitle.append('ggH160_CMS_scale_t_etau_8TeVUp')
sampleTitle.append('ggH160_CMS_scale_t_mutau_8TeVDown')
sampleTitle.append('ggH160_CMS_scale_t_mutau_8TeVUp')
sampleTitle.append('ggH180')
sampleTitle.append('ggH180_CMS_eff_t_mssmHigh_etau_8TeVDown')
sampleTitle.append('ggH180_CMS_eff_t_mssmHigh_etau_8TeVUp')
sampleTitle.append('ggH180_CMS_eff_t_mssmHigh_mutau_8TeVDown')
sampleTitle.append('ggH180_CMS_eff_t_mssmHigh_mutau_8TeVUp')
sampleTitle.append('ggH180_CMS_htt_higgsPtReweight_8TeVDown')
sampleTitle.append('ggH180_CMS_htt_higgsPtReweight_8TeVUp')
sampleTitle.append('ggH180_CMS_htt_higgsPtReweight_scale_8TeVDown')
sampleTitle.append('ggH180_CMS_htt_higgsPtReweight_scale_8TeVUp')
sampleTitle.append('ggH180_CMS_scale_jDown')
sampleTitle.append('ggH180_CMS_scale_jUp')
sampleTitle.append('ggH180_CMS_scale_t_etau_8TeVDown')
sampleTitle.append('ggH180_CMS_scale_t_etau_8TeVUp')
sampleTitle.append('ggH180_CMS_scale_t_mutau_8TeVDown')
sampleTitle.append('ggH180_CMS_scale_t_mutau_8TeVUp')
sampleTitle.append('ggH200')
sampleTitle.append('ggH200_CMS_eff_t_mssmHigh_etau_8TeVDown')
sampleTitle.append('ggH200_CMS_eff_t_mssmHigh_etau_8TeVUp')
sampleTitle.append('ggH200_CMS_eff_t_mssmHigh_mutau_8TeVDown')
sampleTitle.append('ggH200_CMS_eff_t_mssmHigh_mutau_8TeVUp')
sampleTitle.append('ggH200_CMS_htt_higgsPtReweight_8TeVDown')
sampleTitle.append('ggH200_CMS_htt_higgsPtReweight_8TeVUp')
sampleTitle.append('ggH200_CMS_htt_higgsPtReweight_scale_8TeVDown')
sampleTitle.append('ggH200_CMS_htt_higgsPtReweight_scale_8TeVUp')
sampleTitle.append('ggH200_CMS_scale_jDown')
sampleTitle.append('ggH200_CMS_scale_jUp')
sampleTitle.append('ggH200_CMS_scale_t_etau_8TeVDown')
sampleTitle.append('ggH200_CMS_scale_t_etau_8TeVUp')
sampleTitle.append('ggH200_CMS_scale_t_mutau_8TeVDown')
sampleTitle.append('ggH200_CMS_scale_t_mutau_8TeVUp')
sampleTitle.append('ggH250')
sampleTitle.append('ggH250_CMS_eff_t_mssmHigh_etau_8TeVDown')
sampleTitle.append('ggH250_CMS_eff_t_mssmHigh_etau_8TeVUp')
sampleTitle.append('ggH250_CMS_eff_t_mssmHigh_mutau_8TeVDown')
sampleTitle.append('ggH250_CMS_eff_t_mssmHigh_mutau_8TeVUp')
sampleTitle.append('ggH250_CMS_htt_higgsPtReweight_8TeVDown')
sampleTitle.append('ggH250_CMS_htt_higgsPtReweight_8TeVUp')
sampleTitle.append('ggH250_CMS_htt_higgsPtReweight_scale_8TeVDown')
sampleTitle.append('ggH250_CMS_htt_higgsPtReweight_scale_8TeVUp')
sampleTitle.append('ggH250_CMS_scale_jDown')
sampleTitle.append('ggH250_CMS_scale_jUp')
sampleTitle.append('ggH250_CMS_scale_t_etau_8TeVDown')
sampleTitle.append('ggH250_CMS_scale_t_etau_8TeVUp')
sampleTitle.append('ggH250_CMS_scale_t_mutau_8TeVDown')
sampleTitle.append('ggH250_CMS_scale_t_mutau_8TeVUp')
sampleTitle.append('ggH300')
sampleTitle.append('ggH300_CMS_eff_t_mssmHigh_etau_8TeVDown')
sampleTitle.append('ggH300_CMS_eff_t_mssmHigh_etau_8TeVUp')
sampleTitle.append('ggH300_CMS_eff_t_mssmHigh_mutau_8TeVDown')
sampleTitle.append('ggH300_CMS_eff_t_mssmHigh_mutau_8TeVUp')
sampleTitle.append('ggH300_CMS_htt_higgsPtReweight_8TeVDown')
sampleTitle.append('ggH300_CMS_htt_higgsPtReweight_8TeVUp')
sampleTitle.append('ggH300_CMS_htt_higgsPtReweight_scale_8TeVDown')
sampleTitle.append('ggH300_CMS_htt_higgsPtReweight_scale_8TeVUp')
sampleTitle.append('ggH300_CMS_scale_jDown')
sampleTitle.append('ggH300_CMS_scale_jUp')
sampleTitle.append('ggH300_CMS_scale_t_etau_8TeVDown')
sampleTitle.append('ggH300_CMS_scale_t_etau_8TeVUp')
sampleTitle.append('ggH300_CMS_scale_t_mutau_8TeVDown')
sampleTitle.append('ggH300_CMS_scale_t_mutau_8TeVUp')
sampleTitle.append('ggH350')
sampleTitle.append('ggH350_CMS_eff_t_mssmHigh_etau_8TeVDown')
sampleTitle.append('ggH350_CMS_eff_t_mssmHigh_etau_8TeVUp')
sampleTitle.append('ggH350_CMS_eff_t_mssmHigh_mutau_8TeVDown')
sampleTitle.append('ggH350_CMS_eff_t_mssmHigh_mutau_8TeVUp')
sampleTitle.append('ggH350_CMS_htt_higgsPtReweight_8TeVDown')
sampleTitle.append('ggH350_CMS_htt_higgsPtReweight_8TeVUp')
sampleTitle.append('ggH350_CMS_htt_higgsPtReweight_scale_8TeVDown')
sampleTitle.append('ggH350_CMS_htt_higgsPtReweight_scale_8TeVUp')
sampleTitle.append('ggH350_CMS_scale_jDown')
sampleTitle.append('ggH350_CMS_scale_jUp')
sampleTitle.append('ggH350_CMS_scale_t_etau_8TeVDown')
sampleTitle.append('ggH350_CMS_scale_t_etau_8TeVUp')
sampleTitle.append('ggH350_CMS_scale_t_mutau_8TeVDown')
sampleTitle.append('ggH350_CMS_scale_t_mutau_8TeVUp')
sampleTitle.append('ggH400')
sampleTitle.append('ggH400_CMS_eff_t_mssmHigh_etau_8TeVDown')
sampleTitle.append('ggH400_CMS_eff_t_mssmHigh_etau_8TeVUp')
sampleTitle.append('ggH400_CMS_eff_t_mssmHigh_mutau_8TeVDown')
sampleTitle.append('ggH400_CMS_eff_t_mssmHigh_mutau_8TeVUp')
sampleTitle.append('ggH400_CMS_htt_higgsPtReweight_8TeVDown')
sampleTitle.append('ggH400_CMS_htt_higgsPtReweight_8TeVUp')
sampleTitle.append('ggH400_CMS_htt_higgsPtReweight_scale_8TeVDown')
sampleTitle.append('ggH400_CMS_htt_higgsPtReweight_scale_8TeVUp')
sampleTitle.append('ggH400_CMS_scale_jDown')
sampleTitle.append('ggH400_CMS_scale_jUp')
sampleTitle.append('ggH400_CMS_scale_t_etau_8TeVDown')
sampleTitle.append('ggH400_CMS_scale_t_etau_8TeVUp')
sampleTitle.append('ggH400_CMS_scale_t_mutau_8TeVDown')
sampleTitle.append('ggH400_CMS_scale_t_mutau_8TeVUp')
sampleTitle.append('ggH450')
sampleTitle.append('ggH450_CMS_eff_t_mssmHigh_etau_8TeVDown')
sampleTitle.append('ggH450_CMS_eff_t_mssmHigh_etau_8TeVUp')
sampleTitle.append('ggH450_CMS_eff_t_mssmHigh_mutau_8TeVDown')
sampleTitle.append('ggH450_CMS_eff_t_mssmHigh_mutau_8TeVUp')
sampleTitle.append('ggH450_CMS_htt_higgsPtReweight_8TeVDown')
sampleTitle.append('ggH450_CMS_htt_higgsPtReweight_8TeVUp')
sampleTitle.append('ggH450_CMS_htt_higgsPtReweight_scale_8TeVDown')
sampleTitle.append('ggH450_CMS_htt_higgsPtReweight_scale_8TeVUp')
sampleTitle.append('ggH450_CMS_scale_jDown')
sampleTitle.append('ggH450_CMS_scale_jUp')
sampleTitle.append('ggH450_CMS_scale_t_etau_8TeVDown')
sampleTitle.append('ggH450_CMS_scale_t_etau_8TeVUp')
sampleTitle.append('ggH450_CMS_scale_t_mutau_8TeVDown')
sampleTitle.append('ggH450_CMS_scale_t_mutau_8TeVUp')
sampleTitle.append('ggH500')
sampleTitle.append('ggH500_CMS_eff_t_mssmHigh_etau_8TeVDown')
sampleTitle.append('ggH500_CMS_eff_t_mssmHigh_etau_8TeVUp')
sampleTitle.append('ggH500_CMS_eff_t_mssmHigh_mutau_8TeVDown')
sampleTitle.append('ggH500_CMS_eff_t_mssmHigh_mutau_8TeVUp')
sampleTitle.append('ggH500_CMS_htt_higgsPtReweight_8TeVDown')
sampleTitle.append('ggH500_CMS_htt_higgsPtReweight_8TeVUp')
sampleTitle.append('ggH500_CMS_htt_higgsPtReweight_scale_8TeVDown')
sampleTitle.append('ggH500_CMS_htt_higgsPtReweight_scale_8TeVUp')
sampleTitle.append('ggH500_CMS_scale_jDown')
sampleTitle.append('ggH500_CMS_scale_jUp')
sampleTitle.append('ggH500_CMS_scale_t_etau_8TeVDown')
sampleTitle.append('ggH500_CMS_scale_t_etau_8TeVUp')
sampleTitle.append('ggH500_CMS_scale_t_mutau_8TeVDown')
sampleTitle.append('ggH500_CMS_scale_t_mutau_8TeVUp')
sampleTitle.append('ggH600')
sampleTitle.append('ggH600_CMS_eff_t_mssmHigh_etau_8TeVDown')
sampleTitle.append('ggH600_CMS_eff_t_mssmHigh_etau_8TeVUp')
sampleTitle.append('ggH600_CMS_eff_t_mssmHigh_mutau_8TeVDown')
sampleTitle.append('ggH600_CMS_eff_t_mssmHigh_mutau_8TeVUp')
sampleTitle.append('ggH600_CMS_htt_higgsPtReweight_8TeVDown')
sampleTitle.append('ggH600_CMS_htt_higgsPtReweight_8TeVUp')
sampleTitle.append('ggH600_CMS_htt_higgsPtReweight_scale_8TeVDown')
sampleTitle.append('ggH600_CMS_htt_higgsPtReweight_scale_8TeVUp')
sampleTitle.append('ggH600_CMS_scale_jDown')
sampleTitle.append('ggH600_CMS_scale_jUp')
sampleTitle.append('ggH600_CMS_scale_t_etau_8TeVDown')
sampleTitle.append('ggH600_CMS_scale_t_etau_8TeVUp')
sampleTitle.append('ggH600_CMS_scale_t_mutau_8TeVDown')
sampleTitle.append('ggH600_CMS_scale_t_mutau_8TeVUp')
sampleTitle.append('ggH700')
sampleTitle.append('ggH700_CMS_eff_t_mssmHigh_etau_8TeVDown')
sampleTitle.append('ggH700_CMS_eff_t_mssmHigh_etau_8TeVUp')
sampleTitle.append('ggH700_CMS_eff_t_mssmHigh_mutau_8TeVDown')
sampleTitle.append('ggH700_CMS_eff_t_mssmHigh_mutau_8TeVUp')
sampleTitle.append('ggH700_CMS_htt_higgsPtReweight_8TeVDown')
sampleTitle.append('ggH700_CMS_htt_higgsPtReweight_8TeVUp')
sampleTitle.append('ggH700_CMS_htt_higgsPtReweight_scale_8TeVDown')
sampleTitle.append('ggH700_CMS_htt_higgsPtReweight_scale_8TeVUp')
sampleTitle.append('ggH700_CMS_scale_jDown')
sampleTitle.append('ggH700_CMS_scale_jUp')
sampleTitle.append('ggH700_CMS_scale_t_etau_8TeVDown')
sampleTitle.append('ggH700_CMS_scale_t_etau_8TeVUp')
sampleTitle.append('ggH700_CMS_scale_t_mutau_8TeVDown')
sampleTitle.append('ggH700_CMS_scale_t_mutau_8TeVUp')
sampleTitle.append('ggH80')
sampleTitle.append('ggH800')
sampleTitle.append('ggH800_CMS_eff_t_mssmHigh_etau_8TeVDown')
sampleTitle.append('ggH800_CMS_eff_t_mssmHigh_etau_8TeVUp')
sampleTitle.append('ggH800_CMS_eff_t_mssmHigh_mutau_8TeVDown')
sampleTitle.append('ggH800_CMS_eff_t_mssmHigh_mutau_8TeVUp')
sampleTitle.append('ggH800_CMS_htt_higgsPtReweight_8TeVDown')
sampleTitle.append('ggH800_CMS_htt_higgsPtReweight_8TeVUp')
sampleTitle.append('ggH800_CMS_htt_higgsPtReweight_scale_8TeVDown')
sampleTitle.append('ggH800_CMS_htt_higgsPtReweight_scale_8TeVUp')
sampleTitle.append('ggH800_CMS_scale_jDown')
sampleTitle.append('ggH800_CMS_scale_jUp')
sampleTitle.append('ggH800_CMS_scale_t_etau_8TeVDown')
sampleTitle.append('ggH800_CMS_scale_t_etau_8TeVUp')
sampleTitle.append('ggH800_CMS_scale_t_mutau_8TeVDown')
sampleTitle.append('ggH800_CMS_scale_t_mutau_8TeVUp')
sampleTitle.append('ggH80_CMS_eff_t_mssmHigh_etau_8TeVDown')
sampleTitle.append('ggH80_CMS_eff_t_mssmHigh_etau_8TeVUp')
sampleTitle.append('ggH80_CMS_eff_t_mssmHigh_mutau_8TeVDown')
sampleTitle.append('ggH80_CMS_eff_t_mssmHigh_mutau_8TeVUp')
sampleTitle.append('ggH80_CMS_htt_higgsPtReweight_8TeVDown')
sampleTitle.append('ggH80_CMS_htt_higgsPtReweight_8TeVUp')
sampleTitle.append('ggH80_CMS_htt_higgsPtReweight_scale_8TeVDown')
sampleTitle.append('ggH80_CMS_htt_higgsPtReweight_scale_8TeVUp')
sampleTitle.append('ggH80_CMS_scale_jDown')
sampleTitle.append('ggH80_CMS_scale_jUp')
sampleTitle.append('ggH80_CMS_scale_t_etau_8TeVDown')
sampleTitle.append('ggH80_CMS_scale_t_etau_8TeVUp')
sampleTitle.append('ggH80_CMS_scale_t_mutau_8TeVDown')
sampleTitle.append('ggH80_CMS_scale_t_mutau_8TeVUp')
sampleTitle.append('ggH90')
sampleTitle.append('ggH900')
sampleTitle.append('ggH900_CMS_eff_t_mssmHigh_etau_8TeVDown')
sampleTitle.append('ggH900_CMS_eff_t_mssmHigh_etau_8TeVUp')
sampleTitle.append('ggH900_CMS_eff_t_mssmHigh_mutau_8TeVDown')
sampleTitle.append('ggH900_CMS_eff_t_mssmHigh_mutau_8TeVUp')
sampleTitle.append('ggH900_CMS_htt_higgsPtReweight_8TeVDown')
sampleTitle.append('ggH900_CMS_htt_higgsPtReweight_8TeVUp')
sampleTitle.append('ggH900_CMS_htt_higgsPtReweight_scale_8TeVDown')
sampleTitle.append('ggH900_CMS_htt_higgsPtReweight_scale_8TeVUp')
sampleTitle.append('ggH900_CMS_scale_jDown')
sampleTitle.append('ggH900_CMS_scale_jUp')
sampleTitle.append('ggH900_CMS_scale_t_etau_8TeVDown')
sampleTitle.append('ggH900_CMS_scale_t_etau_8TeVUp')
sampleTitle.append('ggH900_CMS_scale_t_mutau_8TeVDown')
sampleTitle.append('ggH900_CMS_scale_t_mutau_8TeVUp')
sampleTitle.append('ggH90_CMS_eff_t_mssmHigh_etau_8TeVDown')
sampleTitle.append('ggH90_CMS_eff_t_mssmHigh_etau_8TeVUp')
sampleTitle.append('ggH90_CMS_eff_t_mssmHigh_mutau_8TeVDown')
sampleTitle.append('ggH90_CMS_eff_t_mssmHigh_mutau_8TeVUp')
sampleTitle.append('ggH90_CMS_htt_higgsPtReweight_8TeVDown')
sampleTitle.append('ggH90_CMS_htt_higgsPtReweight_8TeVUp')
sampleTitle.append('ggH90_CMS_htt_higgsPtReweight_scale_8TeVDown')
sampleTitle.append('ggH90_CMS_htt_higgsPtReweight_scale_8TeVUp')
sampleTitle.append('ggH90_CMS_scale_jDown')
sampleTitle.append('ggH90_CMS_scale_jUp')
sampleTitle.append('ggH90_CMS_scale_t_etau_8TeVDown')
sampleTitle.append('ggH90_CMS_scale_t_etau_8TeVUp')
sampleTitle.append('ggH90_CMS_scale_t_mutau_8TeVDown')
sampleTitle.append('ggH90_CMS_scale_t_mutau_8TeVUp')
sampleTitle.append('ggH_SM125')
sampleTitle.append('ggH_SM125_CMS_eff_t_mssmHigh_etau_8TeVDown')
sampleTitle.append('ggH_SM125_CMS_eff_t_mssmHigh_etau_8TeVUp')
sampleTitle.append('ggH_SM125_CMS_eff_t_mssmHigh_mutau_8TeVDown')
sampleTitle.append('ggH_SM125_CMS_eff_t_mssmHigh_mutau_8TeVUp')
sampleTitle.append('ggH_SM125_CMS_htt_higgsPtReweightSM_8TeVDown')
sampleTitle.append('ggH_SM125_CMS_htt_higgsPtReweightSM_8TeVUp')
sampleTitle.append('ggH_SM125_CMS_scale_jDown')
sampleTitle.append('ggH_SM125_CMS_scale_jUp')
sampleTitle.append('ggH_SM125_CMS_scale_t_etau_8TeVDown')
sampleTitle.append('ggH_SM125_CMS_scale_t_etau_8TeVUp')
sampleTitle.append('ggH_SM125_CMS_scale_t_mutau_8TeVDown')
sampleTitle.append('ggH_SM125_CMS_scale_t_mutau_8TeVUp')
sampleTitle.append('qqH_SM125')
sampleTitle.append('qqH_SM125_CMS_eff_t_mssmHigh_etau_8TeVDown')
sampleTitle.append('qqH_SM125_CMS_eff_t_mssmHigh_etau_8TeVUp')
sampleTitle.append('qqH_SM125_CMS_eff_t_mssmHigh_mutau_8TeVDown')
sampleTitle.append('qqH_SM125_CMS_eff_t_mssmHigh_mutau_8TeVUp')
sampleTitle.append('qqH_SM125_CMS_scale_jDown')
sampleTitle.append('qqH_SM125_CMS_scale_jUp')
sampleTitle.append('qqH_SM125_CMS_scale_t_etau_8TeVDown')
sampleTitle.append('qqH_SM125_CMS_scale_t_etau_8TeVUp')
sampleTitle.append('qqH_SM125_CMS_scale_t_mutau_8TeVDown')
sampleTitle.append('qqH_SM125_CMS_scale_t_mutau_8TeVUp')




#############################
# declare histogram dictionary

histogram_dict = {}


#######################
# declare files

for evT in range(0, len(eventType)):
  fileName = FileNamePrefix+"davis_htt_mssm_"+eventType[evT]+".root"
  dataCardFiles[fileName] = TFile( fileName, 'RECREATE', 'test' )

################################
# add directories to files

for evT in range(0, len(eventType)):
  fileName = FileNamePrefix+"davis_htt_mssm_"+eventType[evT]+".root"
  dataCardFiles[fileName].cd()
  for index in range(0, len(dataCardCategories)):
    directoryName = eventType[evT]+"_"+dataCardCategories[index]
    dataCardFiles[fileName].mkdir(directoryName)
    #TDirectoryFile(directoryName,directoryName)

#############################
# add histograms to dictionaries

binning_nominal_btag = [0 , 20 , 40 , 60 , 80 , 100 , 120 , 140 , 160 , 180 ,
200 , 250 , 300 , 350 , 400 , 500 , 700 , 1000, 1500]



binning_nominal_nobtag = [0 , 10 , 20 , 30 , 40 , 50 , 60 , 70 , 80 , 90 ,
100 , 110 , 120 , 130 , 140 , 150 , 160 , 170 , 180 , 190 ,
200 , 225 , 250 , 275 , 300 , 325 , 350 , 400 , 500 , 700 ,
1000, 1500]


for evT in range(0, len(eventType)):
  for dictIndx in range(0, len(dataCardCategories)):
    for sampleIndx in range(0, len(sampleType)):
      histName = eventType[evT]+"_"+sampleType[sampleIndx]+"_"+dataCardCategories[dictIndx]
      if 'fine_binning' in sampleType[sampleIndx]:
        histogram_dict[histName] = TH1F(histName,sampleTitle[sampleIndx],400,0,2000)
      else:
        if 'nobtag' in dataCardCategories[dictIndx] or 'inclusive' in dataCardCategories[dictIndx]:
          histogram_dict[histName] = TH1F(histName,sampleTitle[sampleIndx],len(binning_nominal_nobtag)-1,array('d',binning_nominal_nobtag))
        else:
          histogram_dict[histName] = TH1F(histName,sampleTitle[sampleIndx],len(binning_nominal_btag)-1,array('d',binning_nominal_btag))
      histogram_dict[histName].Sumw2()
      #histogram_dict[histName].SetDirectory(0)



def ShouldIWriteItHere(fileName,directoryName,sampleType,histName):
  writeIt = True
  if 'eleTau' in directoryName and '_mutau' in histName:
    writeIt = False
  if 'muTau' in directoryName and 'etau' in histName:
     writeIt = False
  if directoryName[-len('_btag'):] == '_btag':
    if 'tag_low' in histName:
      writeIt = False
    if 'tag_medium' in histName:
      writeIt = False
    if 'tag_high' in histName:
      writeIt = False
    if 'nobtag' in histName:
      writeIt = False
  if directoryName[-len('_btag_high'):] == '_btag_high':
    if 'tag_low' in histName:
      writeIt = False
    if 'tag_medium' in histName:
      writeIt = False
    if 'nobtag' in histName:
      writeIt = False
    if 'btag_8' in histName:
      writeIt = False
    if histName[-len('_btag'):] == '_btag':
      writeIt = False
  if directoryName[-len('_btag_low'):] == '_btag_low':
    if 'tag_high' in histName:
      writeIt = False
    if 'tag_medium' in histName:
      writeIt = False
    if 'nobtag' in histName:
      writeIt = False
    if 'btag_8' in histName:
      writeIt = False
    if histName[-len('_btag'):] == '_btag':
      writeIt = False
  if directoryName[-len('_nobtag'):] == '_nobtag':
    if 'tag_low' in histName:
      writeIt = False
    if 'tag_medium' in histName:
      writeIt = False
    if 'tag_high' in histName:
      writeIt = False
    if '_btag' in histName:
      writeIt = False
  if directoryName[-len('_nobtag_high'):] == '_nobtag_high':
    if 'tag_low' in histName:
      writeIt = False
    if 'tag_medium' in histName:
      writeIt = False
    if '_btag' in histName:
      writeIt = False
    if 'nobtag_8' in histName:
      writeIt = False
    if histName[-len('_nobtag'):] == '_nobtag':
      writeIt = False
  if directoryName[-len('_nobtag_medium'):] == '_nobtag_medium':
    if 'tag_high' in histName:
      writeIt = False
    if 'tag_low' in histName:
      writeIt = False
    if '_btag' in histName:
      writeIt = False
    if 'nobtag_8' in histName:
      writeIt = False
    if histName[-len('_nobtag'):] == '_nobtag':
      writeIt = False
  if directoryName[-len('_nobtag_low'):] == '_nobtag_low':
    if 'tag_high' in histName:
      writeIt = False
    if 'tag_medium' in histName:
      writeIt = False
    if '_btag' in histName:
      writeIt = False
    if 'nobtag_8' in histName:
      writeIt = False
    if histName[-len('_nobtag'):] == '_nobtag':
      writeIt = False
  if '_inclusive' in directoryName and '_btag' in histName:
    writeIt = False
  if '_inclusive' in directoryName and '_nobtag' in histName:
    writeIt = False
  if '_inclusive' in directoryName and 'fine_binning' in histName:
    writeIt = False
  if '_inclusive' in directoryName and 'TT_CMS_htt_ZLScale_mutau_8TeV' in histName:
    writeIt = False
  if '_inclusive' in directoryName and 'TT_CMS_htt_ZLScale_etau_8TeV' in histName:
    writeIt = False
  return writeIt


def WriteEverything():
  for evT in range(0, len(eventType)):
    fileName = FileNamePrefix+"davis_htt_mssm_"+eventType[evT]+".root"
    dataCardFiles[fileName].cd()
    for dictIndx in range(0, len(dataCardCategories)):
      directoryName = eventType[evT]+"_"+dataCardCategories[dictIndx]
      print 'changing dir to ',directoryName
      dataCardFiles[fileName].cd(directoryName)
      for sampleIndx in range(0, len(sampleType)):
        histName = eventType[evT]+"_"+sampleType[sampleIndx]+"_"+dataCardCategories[dictIndx]
        suffix = "_"+dataCardCategories[dictIndx]
        prefix = eventType[evT]+"_"
        writeAs = histName[:-len(suffix)]
        writeAs = writeAs[len(prefix):]
        #if ShouldIWriteItHere(fileName,directoryName,sampleType[sampleIndx],writeAs):
        histogram_dict[histName].SetName(writeAs)
        histogram_dict[histName].Write(writeAs)
    dataCardFiles[fileName].Close()
  return


# def WriteEverything():
#   for evT in range(0, len(eventType)):
#     fileName = "davis_htt_mssm_"+eventType[evT]+".root"
#     dataCardFiles[fileName].cd()
#     for dictIndx in range(0, len(dataCardCategories)):
#       directoryName = eventType[evT]+"_"+dataCardCategories[dictIndx]
#       dataCardFiles[fileName].cd(directoryName)
#       for sampleIndx in range(0, len(sampleType)):
#         histName = eventType[evT]+"_"+sampleType[sampleIndx]+"_"+dataCardCategories[dictIndx]
#         suffix = "_"+dataCardCategories[dictIndx]
#         prefix = eventType[evT]+"_"
#         writeAs = histName[:-len(suffix)]
#         writeAs = writeAs[len(prefix):]
#         histogram_dict[histName].SetName(writeAs)
#         histogram_dict[histName].Write(writeAs)
#     dataCardFiles[fileName].Close()
#   return
